/* Frontline Regions: deterministic hex strategy. Both sides use the same rules. */
(function(root){'use strict';const DIRS=[[1,0],[0,1],[-1,1],[-1,0],[0,-1],[1,-1]],TYPES=['tank','artillery','heli'];const clone=x=>JSON.parse(JSON.stringify(x));function distance(a,b){return (Math.abs(a.q-b.q)+Math.abs(a.r-b.r)+Math.abs(a.q+a.r-b.q-b.r))/2;}function rng(s){s.seed=(Math.imul(s.seed,1664525)+1013904223)>>>0;return s.seed/4294967296;}
function create(level=1,difficulty='normal'){const radius=level<5?2:3,s={version:1,level,difficulty,seed:(level*9173+271)>>>0,time:0,cells:[],orders:[],nextId:1,aiClock:3,status:'playing',stats:{sent:0,captured:0,lost:0},events:[]};for(let r=-radius;r<=radius;r++)for(let q=-radius;q<=radius;q++)if(Math.abs(q+r)<=radius){const i=s.cells.length;s.cells.push({id:i,q,r,owner:0,n:8+Math.floor(rng(s)*(level<5?8:18)),type:'tank',terrain:'land',cool:0});}s.cells.forEach(c=>{c.neighbors=s.cells.filter(n=>distance(c,n)===1).map(n=>n.id);c.type=level<3?'tank':(c.id+level)%7===0?'heli':(c.id+level)%5===0?'artillery':'tank';});const left=s.cells.filter(c=>c.q===-radius),right=s.cells.filter(c=>c.q===radius);left.forEach((c,i)=>{if(i===(left.length>>1)||level>2&&i===0){c.owner=1;c.n=level<5?65:48;c.type=i===0&&level>=6?'heli':'tank';}});right.forEach((c,i)=>{if(i===(right.length>>1)||level>2&&i===0){c.owner=2;c.n=level<5?30:45;c.type=i===0&&level>=6?'artillery':'tank';}});
if(level>=5){for(const c of s.cells){if(c.owner||Math.abs(c.r)<=1)continue;if((c.q===0||c.q===1)&&rng(s)<.7){c.terrain='water';c.n=0;}}}return s;}
function path(s,from,to,owner){const a=s.cells[from],b=s.cells[to];if(!a||!b||a.terrain==='water'||b.terrain==='water'||from===to)return null;const queue=[[from]],seen=new Set([from]);while(queue.length){const p=queue.shift(),c=s.cells[p[p.length-1]];for(const id of c.neighbors){if(seen.has(id)||s.cells[id].terrain==='water')continue;const next=p.concat(id);if(id===to)return next;if(s.cells[id].owner===owner){seen.add(id);queue.push(next);}}}return null;}
function route(s,from,to){const a=s.cells[from],b=s.cells[to];if(!a||!b||a.id===b.id||b.terrain==='water')return null;const d=distance(a,b);if(a.type==='heli'&&d<=3)return {path:[from,to],kind:'heli'};if(a.type==='artillery'&&d<=2&&d>1&&b.owner!==a.owner)return {path:[from,to],kind:'shell'};const p=path(s,from,to,a.owner);return p?{path:p,kind:a.type==='heli'?'heli':'tank'}:null;}
function command(s,from,to,fraction=.75,owner=1){if(s.status!=='playing')return {error:'The battle is over.'};const a=s.cells[from],b=s.cells[to];if(!a||a.owner!==owner)return {error:'Start from one of your blue bases.'};if(a.cool>0)return {error:'This base is regrouping.'};const r=route(s,from,to);if(!r)return {error:'No route. Capture neighboring land, or use a helicopter.'};const count=Math.floor(a.n*Math.max(.25,Math.min(1,fraction)));if(count<2)return {error:'Wait for at least 3 units to muster.'};a.n-=count;a.cool=.7;let length=0;for(let i=1;i<r.path.length;i++)length+=distance(s.cells[r.path[i-1]],s.cells[r.path[i]]);const duration=r.kind==='shell'?1.1:r.kind==='heli'?1.1+length*.7:1+length*1.7;const o={id:s.nextId++,from,to,owner,type:r.kind,count,path:r.path,t:0,duration};s.orders.push(o);if(owner===1)s.stats.sent+=count;return {order:o};}
function arrive(s,o){const b=s.cells[o.to];if(o.type==='shell'){if(b.owner!==o.owner){b.n=Math.max(0,b.n-o.count*.9);s.events.push({type:'blast',i:b.id,owner:o.owner});}return;}if(b.owner===o.owner){b.n=Math.min(150,b.n+o.count);return;}const power=o.count*(o.type==='heli'?.9:1);if(power>b.n){const old=b.owner;b.owner=o.owner;b.n=Math.max(1,power-b.n);b.cool=.5;if(o.owner===1)s.stats.captured++;else if(old===1)s.stats.lost++;s.events.push({type:'capture',i:b.id,owner:o.owner});}else{b.n=Math.max(0,b.n-power);s.events.push({type:'blast',i:b.id,owner:o.owner});}}
function ai(s){const owned=s.cells.filter(c=>c.owner===2&&c.n>=12&&c.cool<=0);let choice=null,best=-Infinity;for(const a of owned)for(const b of s.cells){if(b.owner===2||b.terrain==='water')continue;const r=route(s,a.id,b.id);if(!r)continue;const incoming=s.orders.filter(o=>o.owner===2&&o.to===b.id).reduce((n,o)=>n+o.count,0);if(incoming>b.n+5)continue;const count=Math.floor(a.n*.75),power=count*(r.kind==='heli'?.9:1);if(r.kind!=='shell'&&power<b.n+2)continue;const score=(b.owner===1?25:14)-b.n*.22-r.path.length*2+(r.kind==='shell'?-15:0)+rng(s)*4;if(score>best){best=score;choice={a:a.id,b:b.id};}}if(choice){command(s,choice.a,choice.b,.75,2);return;}const needy=owned.filter(c=>c.neighbors.some(i=>s.cells[i].owner===1));for(const b of needy)for(const a of owned)if(a.id!==b.id&&a.n>b.n+25&&path(s,a.id,b.id,2)){command(s,a.id,b.id,.5,2);return;}}
function step(s,dt){if(s.status!=='playing')return;dt=Math.max(0,Math.min(.1,dt));s.time+=dt;for(const c of s.cells){c.cool=Math.max(0,c.cool-dt);if(c.owner){const rate=c.type==='heli'?.70:c.type==='artillery'?.8:1.0;c.n=Math.min(c.n>90?150:90,c.n+dt*rate);}}for(const o of s.orders)o.t+=dt;const arrived=s.orders.filter(o=>o.t>=o.duration);s.orders=s.orders.filter(o=>o.t<o.duration);arrived.forEach(o=>arrive(s,o));s.aiClock-=dt;if(s.aiClock<=0){ai(s);s.aiClock=(s.difficulty==='relaxed'?5.5:Math.max(1.4,4-s.level*.085))*(.85+rng(s)*.3);}const friendly=s.cells.some(c=>c.owner===1)||s.orders.some(o=>o.owner===1&&o.type!=='shell'),enemy=s.cells.some(c=>c.owner===2)||s.orders.some(o=>o.owner===2&&o.type!=='shell');if(!enemy)s.status='won';else if(!friendly)s.status='lost';}
function summary(s){return [1,2].map(owner=>({bases:s.cells.filter(c=>c.owner===owner).length,units:Math.floor(s.cells.filter(c=>c.owner===owner).reduce((n,c)=>n+c.n,0)+s.orders.filter(o=>o.owner===owner).reduce((n,o)=>n+o.count,0))}));}
const api={create,clone,distance,path,route,command,step,summary,TYPES};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.FR=api;
})(typeof window!=='undefined'?window:globalThis);
