(function(root){'use strict';
const THEMES=[{name:'Cedar Front',bg:['#b7cbc4','#e0e4ce'],land:'#769474',edge:'#536c59',water:'#598f9c',tree:'#426251',texture:'meadow'},{name:'Copper Basin',bg:['#c9b79d','#ead9b7'],land:'#c0a477',edge:'#8d795d',water:'#58969f',tree:'#78845c',texture:'sand'},{name:'Alpine Line',bg:['#bdced4','#edf0e9'],land:'#c4d1d1',edge:'#839b9f',water:'#6b98af',tree:'#57716a',texture:'snow'}];const TEAM=['#b7b9a1','#4ca4c4','#cf735e'];
function create(canvas){const ctx=canvas.getContext('2d'),images={};for(const n of ['meadow','sand','snow','spruce']){const im=new Image();im.src='assets/'+n+'.webp';images[n]=im;}let w=400,h=800,R=35,cx=200,cy=400,centers=[],theme=THEMES[0],state=null;
function fit(s){state=s;const b=canvas.getBoundingClientRect();w=b.width;h=b.height;const ratio=Math.min(devicePixelRatio||1,2);canvas.width=w*ratio;canvas.height=h*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);const radius=Math.max(...s.cells.map(c=>Math.abs(c.q))),landscape=h<500;const availW=landscape?w-260:w-26,availH=landscape?h-160:h-330;R=Math.max(15,Math.min(availW/(3*radius+2.2),availH/((2*radius+1)*Math.sqrt(3)*.83+.8),65));cx=landscape?240+(w-250)/2:w/2;cy=landscape?h*.49:145+(h-290)/2;centers=s.cells.map(c=>({x:cx+c.q*R*1.5,y:cy+(c.r+c.q*.5)*Math.sqrt(3)*R*.83}));theme=THEMES[Math.floor((s.level-1)/10)%3];return {w,h,R,centers};}
function hex(x,y,r,sy=.83){ctx.beginPath();for(let k=0;k<6;k++){const a=k*Math.PI/3;const px=x+Math.cos(a)*r,py=y+Math.sin(a)*r*sy;k?ctx.lineTo(px,py):ctx.moveTo(px,py);}ctx.closePath();}
function round(x,y,ww,hh,r){ctx.beginPath();ctx.roundRect(x,y,ww,hh,r);}
function vehicle(x,y,type,owner,scale=1,angle=0,time=0){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ctx.rotate(angle);const col=TEAM[owner],dark=owner===1?'#326274':owner===2?'#825348':'#67705e';ctx.shadowColor='#172d3c45';ctx.shadowBlur=3;ctx.shadowOffsetY=3;if(type==='heli'){ctx.fillStyle='#293b3e';round(-12,-4,24,8,4);ctx.fill();ctx.fillRect(-5,-2,26,3);ctx.fillRect(17,-7,3,12);ctx.fillStyle=col;ctx.beginPath();ctx.ellipse(-6,0,10,6,0,0,7);ctx.fill();ctx.fillStyle='#2b4654';ctx.beginPath();ctx.ellipse(-11,0,5,4,0,0,7);ctx.fill();ctx.strokeStyle='#ecede59c';ctx.lineWidth=2;ctx.beginPath();const a=time*.025;ctx.moveTo(Math.cos(a)*23,Math.sin(a)*12);ctx.lineTo(-Math.cos(a)*23,-Math.sin(a)*12);ctx.moveTo(Math.cos(a+Math.PI/2)*23,Math.sin(a+Math.PI/2)*12);ctx.lineTo(-Math.cos(a+Math.PI/2)*23,-Math.sin(a+Math.PI/2)*12);ctx.stroke();}else{ctx.fillStyle='#2e3d3d';round(-15,-10,30,6,3);ctx.fill();round(-15,5,30,6,3);ctx.fill();ctx.shadowColor='transparent';ctx.strokeStyle='#6f7e78';ctx.lineWidth=1;for(let i=-12;i<15;i+=5){ctx.beginPath();ctx.moveTo(i,-9);ctx.lineTo(i,-5);ctx.moveTo(i,6);ctx.lineTo(i,10);ctx.stroke();}const g=ctx.createLinearGradient(0,-10,0,10);g.addColorStop(0,col);g.addColorStop(1,dark);ctx.fillStyle=g;round(-13,-6,25,14,3);ctx.fill();ctx.fillStyle=dark;round(-7,-5,14,11,3);ctx.fill();ctx.fillStyle=col;round(-7,-7,14,10,3);ctx.fill();ctx.fillStyle='#2e494b';ctx.fillRect(1,-4,type==='artillery'?26:18,3);ctx.fillStyle='#9cae99';ctx.fillRect(0,-5,type==='artillery'?25:17,2);ctx.fillStyle='#e4e5bc';ctx.fillRect(-10,3,4,2);}ctx.restore();}
function arrow(a,b,color,width=2,dash=false){const dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy);if(len<2)return;ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash?[5,5]:[]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([]);const u=.65,x=a.x+dx*u,y=a.y+dy*u,ang=Math.atan2(dy,dx);ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x+Math.cos(ang)*6,y+Math.sin(ang)*6);ctx.lineTo(x+Math.cos(ang+2.5)*6,y+Math.sin(ang+2.5)*6);ctx.lineTo(x+Math.cos(ang-2.5)*6,y+Math.sin(ang-2.5)*6);ctx.closePath();ctx.fill();}
function draw(s,view,time){theme=THEMES[Math.floor((s.level-1)/10)%3];const bg=ctx.createLinearGradient(0,0,w,h);bg.addColorStop(0,theme.bg[0]);bg.addColorStop(1,theme.bg[1]);ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);ctx.save();ctx.strokeStyle='#ffffff20';ctx.lineWidth=1;for(let y=0;y<h;y+=35){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y-w*.18);ctx.stroke();}ctx.restore();
// Soft terrain silhouettes frame the tabletop without obscuring territory boundaries.
ctx.save();for(let i=0;i<9;i++){const x=(i*173+41)%Math.max(1,w),y=(i*127+97)%Math.max(1,h);if(Math.abs(x-cx)<R*5.1&&Math.abs(y-cy)<R*5.5)continue;ctx.beginPath();ctx.ellipse(x,y,80+i*4,25+i*2,-.3,0,7);ctx.fillStyle='#51746108';ctx.fill();}ctx.restore();
const order=s.cells.map(c=>c.id).sort((a,b)=>centers[a].y-centers[b].y);for(const id of order){const c=s.cells[id],p=centers[id],water=c.terrain==='water';ctx.save();ctx.shadowColor='#1f3f3c29';ctx.shadowBlur=7;ctx.shadowOffsetY=6;hex(p.x,p.y+9,R*.99);ctx.fillStyle=water?'#487b8c':theme.edge;ctx.fill();ctx.shadowColor='transparent';hex(p.x,p.y,R*.98);ctx.fillStyle=water?theme.water:theme.land;ctx.fill();ctx.save();ctx.clip();const im=images[theme.texture];if(!water&&im.complete&&im.naturalWidth){ctx.globalAlpha=.67;const side=Math.min(im.naturalWidth,im.naturalHeight)*.42,sx=(id*53)%(im.naturalWidth-side),sy=(id*83)%(im.naturalHeight-side);ctx.drawImage(im,sx,sy,side,side,p.x-R,p.y-R,R*2,R*2);}if(water){ctx.strokeStyle='#c8f0ec70';ctx.lineWidth=1;for(let j=-2;j<=2;j++){ctx.beginPath();ctx.moveTo(p.x-R*.7,p.y+j*8);ctx.quadraticCurveTo(p.x,p.y+j*8+Math.sin(time*.001+j)*4,p.x+R*.7,p.y+j*8);ctx.stroke();}}else{ctx.globalAlpha=c.owner?.18:.06;ctx.fillStyle=TEAM[c.owner];ctx.fillRect(p.x-R,p.y-R,2*R,2*R);}ctx.restore();hex(p.x,p.y,R*.98);ctx.strokeStyle=water?'#b5dfe947':c.owner===1?'#72c8e5ad':c.owner===2?'#ecab927d':'#e3e9d47d';ctx.lineWidth=c.owner?1.5:1;ctx.stroke();if(view.sources.includes(id)){hex(p.x,p.y,R*.87);ctx.strokeStyle='#ffe0a1';ctx.lineWidth=3;ctx.stroke();}else if(view.sources.length&&view.sources.some(a=>FR.route(s,a,id))&&!water){hex(p.x,p.y,R*.90);ctx.strokeStyle=c.owner===1?'#d9f4e3aa':'#f9e6b591';ctx.lineWidth=1.5;ctx.setLineDash([3,4]);ctx.stroke();ctx.setLineDash([]);}if(view.target===id){hex(p.x,p.y,R*.86);ctx.fillStyle='#ffedb335';ctx.fill();ctx.strokeStyle='#ffe2a2';ctx.lineWidth=2;ctx.stroke();}ctx.restore();}
// Small vegetation and base pads are painted in depth order.
for(const id of order){const c=s.cells[id],p=centers[id];if(c.terrain==='water')continue;ctx.save();if(c.owner===0&&id%3===0&&theme!==THEMES[1]){const im=images.spruce;if(im.complete&&im.naturalWidth){const hh=R*.95,ww=hh*im.naturalWidth/im.naturalHeight;ctx.globalAlpha=.82;ctx.drawImage(im,p.x-R*.65-ww/2,p.y-R*.55-hh*.55,ww,hh);}}ctx.beginPath();ctx.ellipse(p.x,p.y-4,R*.51,R*.32,0,0,7);ctx.fillStyle='#394d4460';ctx.fill();ctx.strokeStyle=TEAM[c.owner]+'c0';ctx.lineWidth=2;ctx.stroke();vehicle(p.x,p.y-8,c.type,c.owner,Math.min(1.15,R/31),-.18,time);const bw=Math.max(29,R*.86),yy=p.y+R*.35;round(p.x-bw/2,yy-8,bw,20,7);ctx.fillStyle=c.owner===1?'#194f68ed':c.owner===2?'#713d34ed':'#4f6255e8';ctx.fill();ctx.strokeStyle='#ffffff39';ctx.lineWidth=1;ctx.stroke();ctx.font=`800 ${Math.max(11,Math.min(17,R*.43))}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#f7f5e6';ctx.fillText(Math.floor(c.n),p.x,yy+2);ctx.restore();}
for(const o of s.orders){const progress=Math.min(1,o.t/o.duration),scaled=progress*(o.path.length-1),k=Math.min(o.path.length-2,Math.floor(scaled)),u=scaled-k,a=centers[o.path[k]],b=centers[o.path[k+1]],x=a.x+(b.x-a.x)*u,y=a.y+(b.y-a.y)*u;ctx.save();if(o.owner===1)for(let j=1;j<o.path.length;j++)arrow(centers[o.path[j-1]],centers[o.path[j]],'#a5e4f063',1.3,true);if(o.type==='shell'){ctx.beginPath();ctx.arc(x,y-Math.sin(progress*Math.PI)*35,4,0,7);ctx.fillStyle='#fff0a6';ctx.shadowColor='#ffc15c';ctx.shadowBlur=10;ctx.fill();}else{const angle=Math.atan2(b.y-a.y,b.x-a.x);vehicle(x,y-(o.type==='heli'?12:2),o.type,o.owner,.45,angle,time);round(x-12,y+8,24,15,5);ctx.fillStyle=o.owner===1?'#22526dee':'#773e37ee';ctx.fill();ctx.fillStyle='#fff';ctx.font='800 9px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(o.count,x,y+15);}ctx.restore();}
if(view.target>=0)for(const from of view.sources){const r=FR.route(s,from,view.target);if(r)for(let j=1;j<r.path.length;j++)arrow(centers[r.path[j-1]],centers[r.path[j]],'#ffe2a7',2.8);}
for(const e of view.effects){const p=centers[e.i],t=(time-e.start)/600;if(t>1)continue;ctx.save();ctx.globalAlpha=1-t;ctx.beginPath();ctx.ellipse(p.x,p.y,R*(.3+t*.7),R*(.2+t*.6),0,0,7);ctx.strokeStyle=e.type==='capture'?TEAM[e.owner]:'#ffe0a0';ctx.lineWidth=5*(1-t);ctx.stroke();for(let k=0;k<6;k++){const a=k*Math.PI/3;ctx.fillStyle='#f5d69b';ctx.fillRect(p.x+Math.cos(a)*t*R,p.y+Math.sin(a)*t*R,3,3);}ctx.restore();}}
function hit(x,y){let best=-1,d=Infinity;centers.forEach((p,i)=>{const a=Math.hypot(x-p.x,(y-p.y)/.83);if(a<R*1.02&&a<d){d=a;best=i;}});return best;}
return {fit,draw,hit,get centers(){return centers},get radius(){return R},themes:THEMES};}
root.FRScene={create};})(window);
