(function(root){'use strict';
const PALETTE=[['#6ef0e2','#20b5bd','#168294'],['#ff91ad','#ec477c','#ac2d60'],['#b4f477','#70ce36','#40963d'],['#cc9dff','#9a65ed','#6543b4'],['#ffe891','#f2c443','#c49429'],['#85d5ff','#48a7eb','#2b72b4']];
const THEMES=[{name:'Sea glass',a:'#d8f1f4',b:'#eff5e7',c:'#b3d9e3',board:'#b5d7dc'},{name:'Rose quartz',a:'#f4e5e9',b:'#f9f0dc',c:'#d6c4e3',board:'#d9c8d7'},{name:'Moonstone',a:'#d7e1f1',b:'#eef0f6',c:'#acb9d4',board:'#bdcadd'}];
function make(canvas){const ctx=canvas.getContext('2d');let w=400,h=800,R=44,cy=400,cx=200,centers=[],tray=[],theme=0,layout={};
function resize(){const rect=canvas.getBoundingClientRect();w=rect.width;h=rect.height;const d=Math.min(devicePixelRatio||1,2);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);const wide=h<=540;R=wide?Math.min((w*.63-22)/8,(h-155)/6.4,58):Math.min((w-32)/8,(h-310)/6.4,72);R=Math.max(22,R);cx=wide?w*.32:w/2;cy=wide?h*.59:150+(h-300)/2;centers=HEX.CELLS.map(c=>({x:cx+c.q*1.5*R,y:cy+(c.r+c.q*.5)*Math.sqrt(3)*R*.82}));tray=wide?[{x:w*.68,y:h-115},{x:w*.80,y:h-115},{x:w*.92,y:h-115}]:[-1,0,1].map(n=>({x:w/2+n*Math.min(w*.285,145),y:h-117}));layout={w,h,R,wide,centers,tray,messageY:wide?151:h-242,trayLabelY:wide?h-204:h-203};return layout;}
function hex(x,y,r,scale=.82){ctx.beginPath();for(let k=0;k<6;k++){const a=k*Math.PI/3,xx=x+Math.cos(a)*r,yy=y+Math.sin(a)*r*scale;k?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy);}ctx.closePath();}
function rounded(x,y,width,height,r){ctx.beginPath();ctx.roundRect(x,y,width,height,r);}
function tile(x,y,r,color,alpha=1){const p=PALETTE[color];ctx.save();ctx.globalAlpha=alpha;hex(x,y+5,r);ctx.fillStyle=p[2];ctx.fill();const g=ctx.createLinearGradient(x-r,y-r,x+r,y+r);g.addColorStop(0,p[0]);g.addColorStop(.55,p[1]);g.addColorStop(1,p[2]);hex(x,y,r);ctx.fillStyle=g;ctx.fill();ctx.lineWidth=1.5;ctx.strokeStyle=p[0];ctx.stroke();hex(x,y-1,r*.87);ctx.lineWidth=1;ctx.strokeStyle='#ffffff58';ctx.stroke();ctx.beginPath();ctx.moveTo(x-r*.7,y-r*.51);ctx.lineTo(x-r*.22,y-r*.68);ctx.lineTo(x+r*.46,y-r*.57);ctx.lineWidth=2;ctx.strokeStyle='#ffffff60';ctx.stroke();ctx.restore();}
function stack(a,x,y,r=R*.88,alpha=1,count=true){if(!a.length)return;const step=Math.min(4.2,r*.095,68/Math.max(1,a.length));ctx.save();ctx.globalAlpha=alpha;ctx.shadowColor='#24465338';ctx.shadowBlur=9;ctx.shadowOffsetY=7;hex(x,y+6,r*.97);ctx.fillStyle='#30576435';ctx.fill();ctx.shadowColor='transparent';for(let i=0;i<a.length;i++)tile(x,y-i*step,r,a[i]);const n=HEX.run(a),topY=y-(a.length-1)*step;if(count){ctx.font=`850 ${Math.max(15,r*.49)}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#173d5250';ctx.fillText(n,x,topY+1);ctx.fillStyle='#ffffffee';ctx.fillText(n,x,topY-1);}ctx.restore();}
function draw(view,ms){const T=THEMES[theme];ctx.clearRect(0,0,w,h);const bg=ctx.createLinearGradient(0,0,w,h);bg.addColorStop(0,T.a);bg.addColorStop(.62,T.b);bg.addColorStop(1,T.c);ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);ctx.save();for(let i=0;i<5;i++){ctx.beginPath();ctx.ellipse(w*(.12+i*.23),h*(.4+(i%2)*.38),w*.35,h*.12,-.5,0,Math.PI*2);ctx.fillStyle='#ffffff18';ctx.fill();}ctx.restore();
const order=centers.map((c,i)=>i).sort((a,b)=>centers[a].y-centers[b].y);for(const i of order){const p=centers[i],locked=view.score<view.state.locks[i];ctx.save();ctx.shadowColor='#37586720';ctx.shadowBlur=11;ctx.shadowOffsetY=9;hex(p.x,p.y+12,R*.98);ctx.fillStyle=T.board;ctx.fill();ctx.shadowColor='transparent';hex(p.x,p.y+3,R*.96);ctx.fillStyle=locked?'#ffffff32':'#ffffff6d';ctx.fill();hex(p.x,p.y,R*.95);const g=ctx.createLinearGradient(p.x,p.y-R,p.x,p.y+R);g.addColorStop(0,locked?'#eef5f45c':'#faffffdb');g.addColorStop(1,locked?'#b1cfd445':'#cee5e9bb');ctx.fillStyle=g;ctx.fill();ctx.strokeStyle=locked?'#ffffff3d':'#ffffffed';ctx.lineWidth=1.5;ctx.stroke();if(locked){ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`800 ${R*.39}px system-ui`;ctx.fillStyle='#557c8b65';ctx.fillText(view.state.locks[i],p.x,p.y+3);ctx.beginPath();ctx.arc(p.x,p.y-R*.31,R*.07,Math.PI,0);ctx.lineWidth=1.7;ctx.strokeStyle='#64839165';ctx.stroke();rounded(p.x-R*.10,p.y-R*.30,R*.20,R*.14,2);ctx.fillStyle='#64839165';ctx.fill();}else if(!view.board[i].length){ctx.beginPath();ctx.arc(p.x,p.y,2,0,Math.PI*2);ctx.fillStyle='#6b9aa646';ctx.fill();}if(view.target===i||view.hint?.i===i){hex(p.x,p.y,R*.92);ctx.lineWidth=3;ctx.strokeStyle=view.hint?'#e5b44f':locked||view.board[i].length?'#d76572':'#268f9c';ctx.setLineDash(view.hint?[5,4]:[]);ctx.stroke();ctx.setLineDash([]);}ctx.restore();}
let display=view.board.map(a=>a.slice());const anim=view.anim;let t=0;if(anim){t=Math.min(1,(ms-anim.start)/anim.duration);if(anim.event.type==='slide')display[anim.event.from].splice(-anim.event.count);if(anim.event.type==='clear'||anim.event.type==='hammer')display[anim.event.i]=anim.event.board[anim.event.i].slice();}
for(const i of order){const p=centers[i];stack(display[i],p.x,p.y,R*.85);}
if(anim){const e=anim.event,u=t*t*(3-2*t);if(e.type==='slide'){const a=centers[e.from],b=centers[e.to],existing=view.board[e.to].length,base=view.board[e.from].length-e.count;const x=a.x+(b.x-a.x)*u,y=a.y+(b.y-a.y)*u-4*(base*(1-u)+existing*u)-Math.sin(t*Math.PI)*R*.65;stack(Array(e.count).fill(e.color),x,y,R*.85,1,false);}if(e.type==='clear'||e.type==='hammer'){const p=centers[e.i];ctx.save();ctx.globalAlpha=1-t;ctx.beginPath();ctx.ellipse(p.x,p.y-15,R*(.8+t*.7),R*(.6+t*.55),0,0,Math.PI*2);ctx.strokeStyle=PALETTE[e.color][1];ctx.lineWidth=5*(1-t);ctx.stroke();for(let k=0;k<12;k++){const a=k*Math.PI/6;ctx.fillStyle=PALETTE[e.color][k%2];ctx.beginPath();ctx.arc(p.x+Math.cos(a)*R*(.4+t),p.y-20+Math.sin(a)*R*(.4+t)-t*15,3*(1-t)+1,0,7);ctx.fill();}ctx.font='900 25px system-ui';ctx.textAlign='center';ctx.fillStyle='#277889';ctx.fillText(e.type==='clear'?'+'+e.count:'',p.x,p.y-55-t*30);ctx.restore();}}
for(let i=0;i<3;i++){const p=tray[i],r=Math.min(R*.94,layout.wide?35:48);ctx.save();const slotW=layout.wide?Math.max(78,w*.105):Math.min(w*.265,130);rounded(p.x-slotW/2,p.y-102,slotW,137,18);ctx.fillStyle=view.selected===i?'#ffffffce':'#ffffff55';ctx.fill();ctx.lineWidth=view.selected===i?2.5:1;ctx.strokeStyle=view.selected===i?'#278e9c':'#ffffffaa';ctx.stroke();ctx.beginPath();ctx.ellipse(p.x,p.y+10,r*1.1,r*.5,0,0,7);ctx.fillStyle='#ffffff72';ctx.fill();if(view.selected===i||view.hint?.slot===i){hex(p.x,p.y+2,r*1.1);ctx.lineWidth=2.5;ctx.strokeStyle=view.hint?.slot===i?'#d8ac4c':'#278e9c';ctx.stroke();}if(!(view.drag&&view.drag.slot===i))stack(view.state.tray[i],p.x,p.y,r);ctx.restore();}if(view.drag){ctx.beginPath();ctx.arc(view.drag.x,view.drag.y,5,0,Math.PI*2);ctx.fillStyle='#277889';ctx.fill();stack(view.state.tray[view.drag.slot],view.drag.x,view.drag.y-45,Math.min(R*.92,48),.94);}}
function cellAt(x,y){let best=-1,dist=Infinity;centers.forEach((p,i)=>{const n=Math.hypot(x-p.x,(y-p.y)/.82);if(n<R*.98&&n<dist){best=i;dist=n;}});return best;}
function stackAt(board,x,y){const order=centers.map((p,i)=>i).sort((a,b)=>centers[b].y-centers[a].y);for(const i of order){const a=board[i],p=centers[i];if(!a.length)continue;const step=Math.min(4.2,R*.0855,68/a.length),top=p.y-(a.length-1)*step;if(Math.abs(x-p.x)<R*.87&&y>top-R*.65&&y<p.y+R*.67)return i;}return -1;}
function trayAt(x,y){let found=-1,best=Infinity;const half=layout.wide?Math.max(42,w*.055):Math.min(w*.14,72);tray.forEach((p,i)=>{const dx=Math.abs(x-p.x);if(dx<=half+5&&y>=p.y-115&&y<=p.y+43&&dx<best){best=dx;found=i;}});return found;}
resize();return {resize,draw,cellAt,trayAt,stackAt,get layout(){return layout},setTheme(n){theme=n%THEMES.length},THEMES};}
root.HexRenderer={make,THEMES,PALETTE};
})(window);
