/* Lot Escape: bounded sliding-block search, independent of the rendering layer. */
var LotChallenge=(function(){'use strict';
function key(cars){return cars.map(function(c){return String.fromCharCode(65+(c.dir==='h'?c.x:c.y));}).join('');}
function carsAt(template,k){return template.map(function(c,i){return Object.assign({},c,c.dir==='h'?{x:k.charCodeAt(i)-65}:{y:k.charCodeAt(i)-65});});}
function moves(cars){var grid=new Int16Array(36).fill(-1),out=[];cars.forEach(function(c,i){for(var j=0;j<c.len;j++)grid[(c.y+(c.dir==='v'?j:0))*6+c.x+(c.dir==='h'?j:0)]=i;});cars.forEach(function(c,i){[-1,1].forEach(function(sign){for(var n=1;n<6;n++){var x=c.x+(c.dir==='h'?(sign>0?c.len+n-1:-n):0),y=c.y+(c.dir==='v'?(sign>0?c.len+n-1:-n):0);if(x<0||y<0||x>=6||y>=6||grid[y*6+x]!==-1)break;out.push({id:i,sign:sign,dist:n});}});});return out;}
function solve(cars,cap){cap=cap||80000;var start=key(cars),queue=[start],seen=new Map([[start,null]]),prev=new Map(),end=null;for(var head=0;head<queue.length;head++){var k=queue[head];if(k.charCodeAt(0)-65===4){end=k;break;}if(seen.size>cap)return null;var cc=carsAt(cars,k);for(var m of moves(cc)){var a=k.split('');a[m.id]=String.fromCharCode(k.charCodeAt(m.id)+m.sign*m.dist);var next=a.join('');if(seen.has(next))continue;seen.set(next,k);prev.set(next,m);queue.push(next);}}
if(!end)return null;var path=[];while(end!==start){path.push(prev.get(end));end=seen.get(end);}path.reverse();path.push({id:0,sign:1,dist:1,exit:true});return path;}
function create(n){var bank=LotChallengeBank,ix=Math.max(0,Math.min(bank.length-1,n-1)),b=bank[ix];return {challenge:true,n:ix+1,w:6,h:6,rocks:[],cars:b.cars.map(function(c,i){return {id:i,x:c[0],y:c[1],dir:c[2]?'v':'h',len:c[3],color:i===0?0:1+(i-1)%9,face:c[2]?-1:1,gone:false};}),par:b.par,moves:0,bumps:0,hist:[],won:false,hinted:false};}
function move(g,id,sign,dist){var c=g.cars[id];if(!c||g.won)return null;sign=sign||c.face;dist=Math.max(1,Math.round(dist||1));var exit=id===0&&sign===1&&c.x===4,valid=moves(g.cars).filter(function(m){return m.id===id&&m.sign===sign;}),max=valid.length?valid[valid.length-1].dist:0;if(!max&&!exit){g.bumps++;return {bump:true,sign:sign,blocker:-1};}g.hist.push({id:id,x:c.x,y:c.y,face:c.face,moves:g.moves});if(exit){c.gone=true;g.won=true;}else c[c.dir==='h'?'x':'y']+=sign*Math.min(dist,max);c.face=sign;g.moves++;return {dist:exit?1:Math.min(dist,max),exit:exit,sign:sign,won:g.won};}
function undo(g){var h=g.hist.pop();if(!h)return null;Object.assign(g.cars[h.id],{x:h.x,y:h.y,face:h.face,gone:false});g.moves=h.moves;g.won=false;return h.id;}
return {key:key,moves:moves,solve:solve,create:create,move:move,undo:undo};})();
if(typeof module!=='undefined')module.exports=LotChallenge;
