/* Bridge Works: deterministic 2D elastic trusses and rigid vehicles.
   Simulation coordinates are meters, y up. Rendered bridge depth is decorative.
   Wheel/road contact transfers equal-and-opposite loads to the supporting joints. */
(function(root){'use strict';
const DT=1/240,G=9.81;
const MAT={road:{name:'Road',cost:80,max:2.6,k:600000,tension:75000,compression:70000,mass:24,color:'#536574'},wood:{name:'Timber',cost:42,max:3.3,k:150000,tension:18500,compression:14000,mass:10,color:'#bf8c53'},steel:{name:'Steel',cost:105,max:5,k:460000,tension:65000,compression:54000,mass:20,color:'#6c99a8'},cable:{name:'Cable',cost:50,max:12,k:230000,tension:39000,compression:0,mass:3,color:'#c9d1d0'},concrete:{name:'Pillar',cost:130,max:4.2,k:600000,tension:18000,compression:120000,mass:50,color:'#b2b1a1'}};
const VEH={car:{mass:380,half:.72,r:.29,h:.40,speed:1.6},truck:{mass:1000,half:1.05,r:.35,h:.5,speed:1.25},tanker:{mass:1450,half:1.15,r:.38,h:.52,speed:1.15}};
const clone=x=>JSON.parse(JSON.stringify(x));
function design(L){return {nodes:L.anchors.map((a,i)=>({id:i,x:a[0],y:a[1],fixed:true})),beams:[],nextId:L.anchors.length};}
function cost(d){return Math.round(d.beams.reduce((v,b)=>{const a=d.nodes.find(n=>n.id===b.a),c=d.nodes.find(n=>n.id===b.b);return v+Math.hypot(a.x-c.x,a.y-c.y)*MAT[b.type].cost;},0));}
function at(d,x,y){return d.nodes.find(n=>Math.hypot(n.x-x,n.y-y)<.12);}
function add(d,A,B,type,L,free=false){const M=MAT[type];if(!M)return 'Choose a material.';const len=Math.hypot(B.x-A.x,B.y-A.y);if(len<.3)return 'Choose a different joint.';if(len>M.max+.01)return `${M.name} can span up to ${M.max} m. Add another joint.`;
if(type==='concrete'&&Math.abs(A.x-B.x)>.6)return 'Pillars must be vertical.';
if(!free&&L.materials&&!L.materials.includes(type))return 'This material is not available here.';
const a=at(d,A.x,A.y),b=at(d,B.x,B.y);if(a&&b&&d.beams.some(e=>(e.a===a.id&&e.b===b.id)||(e.a===b.id&&e.b===a.id)))return 'There is already a member between those joints.';
if(!free&&cost(d)+len*M.cost>L.budget+.5)return 'Over budget. Remove a member or choose a cheaper material.';
const na=a||{id:d.nextId++,x:A.x,y:A.y,fixed:false},nb=b||{id:d.nextId++,x:B.x,y:B.y,fixed:false};if(!a)d.nodes.push(na);if(!b)d.nodes.push(nb);d.beams.push({a:na.id,b:nb.id,type});return '';}
function remove(d,index){d.beams.splice(index,1);const used=new Set(d.beams.flatMap(b=>[b.a,b.b]));d.nodes=d.nodes.filter(n=>n.fixed||used.has(n.id));}
function example(L){const d=design(L),N=L.span/2,dy=L.rise||0;const top=x=>({x,y:x/L.span*dy}),low=x=>({x,y:x/L.span*dy-2});const material=L.materials.includes('steel')&&(L.vehicles.includes('truck')||L.vehicles.includes('tanker')||L.span>10)?'steel':'wood';
for(let i=0;i<N;i++){let x=i*2;add(d,top(x),top(x+2),'road',L,true);add(d,low(x),low(x+2),material,L,true);add(d,top(x),low(x+2),material,L,true);if(i>0)add(d,top(x),low(x),material,L,true);}return d;}
function create(L,d){const nodes=d.nodes.map(n=>({...n,ox:n.x,oy:n.y,vx:0,vy:0,fx:0,fy:0,mass:24})),map=new Map(nodes.map(n=>[n.id,n]));const beams=d.beams.map((b,i)=>{const a=map.get(b.a),c=map.get(b.b),len=Math.hypot(a.x-c.x,a.y-c.y),m=MAT[b.type];a.mass+=len*m.mass/2;c.mass+=len*m.mass/2;return {...b,i,A:a,B:c,len,k:m.k/len,stress:0,peak:0,damage:0,broken:false};});const bends=[];for(const n of nodes){const roads=beams.filter(b=>b.type==='road'&&(b.a===n.id||b.b===n.id));if(roads.length===2){const a=roads[0].A===n?roads[0].B:roads[0].A,c=roads[1].A===n?roads[1].B:roads[1].A;const angle=Math.atan2(a.y-n.y,a.x-n.x)-Math.atan2(c.y-n.y,c.x-n.x);bends.push({n,a,c,p:roads[0],q:roads[1],angle});}}return {L,nodes,beams,bends,cars:[],t:0,nextCar:0,passed:0,failed:false,won:false,events:[],peak:0,broken:0};}
function spawn(s,type){const v=VEH[type],x=-3.2;s.cars.push({...v,type,x,y:v.h+v.r+.08,vx:0,vy:0,a:0,av:0,fx:0,fy:0,torque:0,contact:0,done:false,stall:0});}
function nearest(px,py,a,b){let dx=b.x-a.x,dy=b.y-a.y,u=Math.max(0,Math.min(1,((px-a.x)*dx+(py-a.y)*dy)/(dx*dx+dy*dy||1)));return {x:a.x+dx*u,y:a.y+dy*u,u};}
function contact(s,c,offset){const ca=Math.cos(c.a),sa=Math.sin(c.a),rx=ca*offset+sa*c.h,ry=sa*offset-ca*c.h,wx=c.x+rx,wy=c.y+ry,wvx=c.vx-c.av*ry,wvy=c.vy+c.av*rx;let best=null;
if(wx<=.02||wx>=s.L.span-.02){const y=wx<=.02?0:s.L.rise||0;if(wy>y-.15&&wy<y+.07+c.r)best={nx:0,ny:1,depth:y+.07+c.r-wy,vx:0,vy:0};}
for(const b of s.beams){if(b.broken||b.type!=='road')continue;const q=nearest(wx,wy,b.A,b.B),dx=wx-q.x,dy=wy-q.y,dist=Math.hypot(dx,dy);if(dy<-.025||dist>c.r+.065)continue;const p={nx:dist>1e-6?dx/dist:0,ny:dist>1e-6?dy/dist:1,depth:c.r+.065-dist,vx:b.A.vx*(1-q.u)+b.B.vx*q.u,vy:b.A.vy*(1-q.u)+b.B.vy*q.u,b,u:q.u};if(p.ny>.3&&(!best||p.depth>best.depth))best=p;}
if(!best)return;const rel=(wvx-best.vx)*best.nx+(wvy-best.vy)*best.ny,F=Math.max(0,Math.min(70000,best.depth*85000-rel*2200)),fx=F*best.nx,fy=F*best.ny;c.fx+=fx;c.fy+=fy;c.torque+=rx*fy-ry*fx;c.contact++;if(best.b){best.b.A.fx-=fx*(1-best.u);best.b.A.fy-=fy*(1-best.u);best.b.B.fx-=fx*best.u;best.b.B.fy-=fy*best.u;}}
function step(s){if(s.won||s.failed)return;s.t+=DT;
if(s.nextCar<s.L.vehicles.length&&s.t>=1+s.nextCar*5.5){spawn(s,s.L.vehicles[s.nextCar++]);}
for(const n of s.nodes){n.fx=-n.vx*8;n.fy=-n.mass*G-n.vy*8;}
for(const b of s.beams)b.bend=0;for(const j of s.bends){if(j.p.broken||j.q.broken)continue;let a=Math.atan2(j.a.y-j.n.y,j.a.x-j.n.x)-Math.atan2(j.c.y-j.n.y,j.c.x-j.n.x)-j.angle;a=Math.atan2(Math.sin(a),Math.cos(a));const r=Math.abs(a)/.23;j.p.bend=Math.max(j.p.bend,r);j.q.bend=Math.max(j.q.bend,r);}for(const b of s.beams){if(b.broken)continue;const m=MAT[b.type],dx=b.B.x-b.A.x,dy=b.B.y-b.A.y,len=Math.hypot(dx,dy)||1e-6,nx=dx/len,ny=dy/len,stretch=len-b.len;let elastic=b.k*stretch;if(b.type==='cable')elastic=Math.max(0,elastic);let force=elastic+((b.B.vx-b.A.vx)*nx+(b.B.vy-b.A.vy)*ny)*220;if(b.type==='cable')force=Math.max(0,force);const limit=elastic>=0?m.tension:m.compression/Math.max(1,(b.len/(b.type==='wood'?2.8:4))**2);const ratio=Math.max(Math.abs(elastic)/Math.max(1,limit),b.bend||0);b.stress+=(ratio-b.stress)*Math.min(1,DT*15);b.peak=Math.max(b.peak,ratio);s.peak=Math.max(s.peak,b.stress);b.damage=ratio>1?b.damage+DT*(ratio-.85):Math.max(0,b.damage-DT*.5);if(b.damage>.12||ratio>3.5||len>b.len*1.35){b.broken=true;s.broken++;s.events.push({type:'break',x:(b.A.x+b.B.x)/2,y:(b.A.y+b.B.y)/2,material:b.type});continue;}b.A.fx+=force*nx;b.A.fy+=force*ny;b.B.fx-=force*nx;b.B.fy-=force*ny;}
for(const c of s.cars){if(c.done)continue;c.fx=0;c.fy=-c.mass*G;c.torque=-c.av*80;c.contact=0;contact(s,c,-c.half);contact(s,c,c.half);if(c.contact)c.fx+=Math.max(-c.mass*6,Math.min(c.mass*5,(c.speed-c.vx)*c.mass*5));c.vx+=c.fx/c.mass*DT;c.vy+=c.fy/c.mass*DT;c.av+=c.torque/(c.mass*(c.half*c.half+.3))*DT;c.x+=c.vx*DT;c.y+=c.vy*DT;c.a+=c.av*DT;
if(c.x>s.L.span+2){c.done=true;s.passed++;s.events.push({type:'pass'});}if(c.y<-4.5||Math.abs(c.a)>1.5){s.failed=true;s.events.push({type:'fail'});}if(c.x>-.5&&Math.abs(c.vx)<.12)c.stall+=DT;else c.stall=0;if(c.stall>9){s.failed=true;s.events.push({type:'stuck'});}}
for(const n of s.nodes){if(n.fixed){n.vx=n.vy=0;continue;}n.vx+=n.fx/n.mass*DT;n.vy+=n.fy/n.mass*DT;n.x+=n.vx*DT;n.y+=n.vy*DT;if(n.y<-7){n.y=-7;n.vx*=.97;n.vy=0;}if(!Number.isFinite(n.x+n.y)){s.failed=true;}}
if(s.passed===s.L.vehicles.length){s.won=true;s.events.push({type:'win'});}if(s.t>100){s.failed=true;s.events.push({type:'timeout'});}}
const API={DT,MAT,VEH,design,cost,at,add,remove,example,create,step,nearest,clone};if(typeof module!=='undefined')module.exports=API;else root.BW=API;
})(typeof window!=='undefined'?window:globalThis);
