import {build} from './scene.js';
const B=window.BW,LEVELS=window.BW_LEVELS,$=id=>document.getElementById(id),store=Goobs.store('bridge');
const meta=Object.assign({open:1,level:1,stars:{},best:{},drafts:{},sound:true,seen:false,autoJoints:true},store.get('meta',{})||{});
const canvas=$('draft'),ctx=canvas.getContext('2d'),money=n=>'$'+Math.round(n).toLocaleString();
let scene,L,d,sim=null,mode='build',tool='road',source=null,gesture=null,pointers=new Map(),pinch=null,undo=[],redo=[],stress=false,speed=1,last=0,acc=0,toastTimer,resultTimer,assisted=false,sandbox=false,loaded=false,ghost=false,ac=null,oldFocus=null;
function save(){store.set('meta',meta);}function draftKey(){return sandbox?'sandbox':L.id;}
function saveDraft(){meta.drafts[draftKey()]={design:B.clone(d),assisted};save();}
function tone(hz=450,dur=.08){if(!meta.sound)return;try{ac||=new(window.AudioContext||window.webkitAudioContext)();ac.resume();const o=ac.createOscillator(),g=ac.createGain();o.type='sine';o.frequency.value=hz;g.gain.setValueAtTime(.08,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+dur);o.connect(g);g.connect(ac.destination);o.start();o.stop(ac.currentTime+dur);}catch{}}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3200);}
function paused(){return !$('sheet').hidden||document.hidden;}
function button(id,text,cls=''){return `<button id="${id}" class="${cls}">${text}</button>`;}
function title(kicker,heading){return `<div class="eyebrow">${kicker}</div><h2 id="sheetTitle">${heading}</h2>`;}
function closeButton(){return button('dismiss','×','close');}function bind(id,fn){$(id)?.addEventListener('click',fn);}
function modal(html,wide=false){source=null;gesture=null;oldFocus=document.activeElement;$('card').className=wide?'wide':'';$('card').innerHTML=html;$('sheet').hidden=false;$('card').querySelector('button,select')?.focus();}
function close(){ $('sheet').hidden=true;oldFocus?.focus?.(); }
function menu(welcome=false){modal(`${welcome?'':closeButton()}<div class="eyebrow">DESIGN. BUILD. CROSS.</div><h2 id="sheetTitle" class="heroTitle">BRIDGE<br><span>WORKS.</span></h2><p>Make a connection that holds.<br>From the first timber span to the final heavy convoy.</p><div class="stats"><div><strong>24</strong>CONSTRUCTION SITES</div><div><strong>3</strong>LANDSCAPES</div><div><strong>5</strong>MATERIALS</div></div><div class="actions">${button('continue',welcome?'Start building →':'Back to the bridge →','primary')}<a class="menuBack" href="../../index.html">← Back to Goobs Games</a><div class="row">${button('sites','Construction sites')}${button('free','Free build')}</div><div class="row">${button('guide','How to Play')}${button('sound',meta.sound?'Sound on':'Sound off')}</div>${welcome?'':button('reset','Clear this design','quiet danger')}</div><p class="tiny">Offline bridge engineering · Bridge Works 1.4</p>`);bind('dismiss',close);bind('continue',()=>{close();if(!meta.seen){meta.seen=true;save();toast('The road is started. Use Timber to brace it underneath.');}});bind('sites',siteMenu);bind('free',freeMenu);bind('guide',manual);bind('sound',()=>{meta.sound=!meta.sound;save();$('sound').textContent=meta.sound?'Sound on':'Sound off';tone();});bind('reset',()=>{modal(`${title('NEW BLUEPRINT','Clear this design?')}<p>This removes your current members. Completed stages and best scores remain saved.</p><div class="actions">${button('clearConfirm','Clear design','danger')}${button('cancel','Keep building','primary')}</div>`);bind('cancel',close);bind('clearConfirm',()=>{if(mode!=='build')edit();snapshot();d=B.design(L);assisted=false;changed();close();});});}
function siteMenu(){modal(`${closeButton()}${title('THE CAMPAIGN','A bridge for every landscape.')}<p>Build within budget, get every vehicle across, and refine your design for three stars.</p>${[0,1,2].map(r=>`<h3 class="chapterTitle">${scene.themes[r].name.toUpperCase()}</h3><div class="levelGrid">${LEVELS.slice(r*8,r*8+8).map(l=>`<button data-level="${l.id}" ${l.id>meta.open?'disabled':''}>${l.id}<small>${meta.stars[l.id]?'★'.repeat(meta.stars[l.id]):'·'}</small></button>`).join('')}</div>`).join('')}`,true);bind('dismiss',close);$('card').querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{start(+b.dataset.level);close();});}
function freeMenu(){modal(`${closeButton()}${title('FREE BUILD','Your own crossing.')}<p>Every material is available, with no budget limit. Experiment with trusses, suspension cables, and piers.</p><label class="field">Landscape<select id="freeRegion"><option value="0">Cedar Valley</option><option value="1">Copper Canyon</option><option value="2">Alpine Reach</option></select></label><label class="field">Span<select id="freeSpan"><option value="8">8 meters</option><option value="12" selected>12 meters</option><option value="16">16 meters</option><option value="20">20 meters</option><option value="24">24 meters</option></select></label><label class="field">Load test<select id="freeVehicle"><option value="car">One car</option><option value="truck">Two trucks</option><option value="tanker">Heavy tanker</option></select></label>${button('createFree','Open construction site →','primary')}`);bind('dismiss',close);bind('createFree',()=>{const span=+$('freeSpan').value,region=+$('freeRegion').value,v=$('freeVehicle').value;start({id:0,name:'Your crossing',span,rise:0,region,materials:Object.keys(B.MAT),budget:999999,anchors:[[0,0],[span,0],[0,-2],[span,-2],[span/2,-4]],vehicles:v==='truck'?['truck','truck']:[v],hint:'Build whatever you imagine. Triangles give stiffness; cables need secure anchorage.'});close();});}
function manual(){modal(`${closeButton()}${title('FIELD MANUAL','Build with a plan.')}<div class="guide"><div><b>Draw the road</b><p>Auto joints is on by default. Tap two endpoints or drag a long section: intermediate joints and legal-length pieces are added for you. Lay road fills the crossing with connected road sections in one tap. You still choose the supports. Switch Auto joints off to place individual members. Undo removes the whole last action. Automatic placement has no star penalty.</p></div><div><b>Brace the span</b><p>Timber and steel support the road. Add a lower chord and diagonal members to make triangles. A flat chain of roads can fold under its own weight. Members connect only at their end joints; crossing lines do not join automatically.</p></div><div><b>Choose your material</b><p>Timber is economical but limited to short pieces. Steel takes heavier loads. Cables resist tension only. Concrete pillars must be vertical and need a connection to a foundation. Gold joints are fixed foundations.</p></div><div><b>Test, inspect, improve</b><p>Vehicles physically load the roadway. Stress colors turn green, yellow, then red. Members can buckle or snap. Return to Edit to restore your design exactly and improve it.</p></div><div><b>Work comfortably</b><p>Use Erase to remove a member, Undo to recover it, and Pan to move the view. Pinch or use +/− to zoom. Mouse wheel also zooms. Shortcuts: 1–5 materials, E erase, P pan, Ctrl/Cmd+Z undo.</p></div><div><b>Earn your stars</b><p>Get every vehicle across within budget. A crossing without broken members earns two stars; spending no more than 75% of the budget earns three. Loading an example limits that attempt to one star.</p></div></div>${button('manualClose','Ready to build','primary')}`,true);bind('dismiss',close);bind('manualClose',close);}
function hint(){if(mode!=='build')return;modal(`${closeButton()}${title('ENGINEER’S NOTE','Find the load path.')}<p>${L.hint}</p><p>Every loaded joint needs a stiff route back to a gold foundation. Large unsupported rectangles tend to fold; diagonals turn them into triangles.</p><div class="actions">${button('showGhost','Show a suggested framework','primary')}${button('loadExample','Load a working example','quiet')}${button('hintBack','Keep my design','quiet')}</div><p class="tiny">A suggested framework is a visual guide. Loading the full example replaces your design and limits this attempt to one star. Undo restores your previous work.</p>`);bind('dismiss',close);bind('hintBack',close);bind('showGhost',()=>{ghost=!ghost;close();toast(ghost?'Suggested framework shown in faint blue.':'Framework hidden.');});bind('loadExample',()=>{snapshot();d=B.example(L);assisted=true;ghost=false;changed();close();toast('Example loaded. Test it, then experiment with its supports.');});}
function start(which){clearTimeout(resultTimer);sandbox=typeof which==='object';L=sandbox?which:LEVELS[Math.max(0,Math.min(LEVELS.length-1,which-1))];mode='build';sim=null;source=null;gesture=null;pinch=null;pointers.clear();undo=[];redo=[];ghost=false;speed=1;assisted=false;
const saved=!sandbox&&meta.drafts[L.id];if(saved?.design?.nodes&&saved?.design?.beams){d=B.clone(saved.design);assisted=!!saved.assisted;}else{d=B.design(L);if(L.id===1){for(let x=0;x<L.span;x+=2)B.add(d,{x,y:0},{x:x+2,y:0},'road',L);}}
if(!sandbox){meta.level=L.id;save();}scene.setLevel(L,d);tool='road';$('chapter').textContent=scene.themes[L.region].name.toUpperCase()+(sandbox?' · FREE BUILD':` · ${String(L.id).padStart(2,'0')} / 24`);$('levelName').textContent=L.name;resize();ui();}
function snapshot(){undo.push({d:B.clone(d),assisted});if(undo.length>60)undo.shift();redo=[];}
function changed(){scene.setDesign(d);saveDraft();ui();tone(430,.045);}
function undoEdit(){if(mode!=='build'||!undo.length)return;redo.push({d:B.clone(d),assisted});const back=undo.pop();d=back.d;assisted=back.assisted;source=null;changed();}
function redoEdit(){if(mode!=='build'||!redo.length)return;undo.push({d:B.clone(d),assisted});const next=redo.pop();d=next.d;assisted=next.assisted;source=null;changed();}
function select(t){if(mode!=='build')return;tool=t;source=null;gesture=null;ui();}
function ui(){if(!L)return;$('buildAssist').hidden=mode!=='build';$('autoJoints').textContent='Auto joints: '+(meta.autoJoints?'On':'Off');$('autoJoints').setAttribute('aria-pressed',String(meta.autoJoints));const spent=B.cost(d);$('money').innerHTML=money(spent)+` <small>/ ${sandbox?'∞':money(L.budget)}</small>`;$('budgetFill').style.width=(sandbox?0:Math.min(100,spent/L.budget*100))+'%';$('memberCount').textContent=d.beams.length+' members';$('undo').disabled=!undo.length||mode!=='build';$('redo').disabled=!redo.length||mode!=='build';$('materials').hidden=mode!=='build';$('testHUD').hidden=mode==='build';$('speed').hidden=mode==='build';$('speed').textContent=speed+'×';$('test').textContent=mode==='build'?'▶ Test bridge':'↶ Edit bridge';$('erase').classList.toggle('active',tool==='erase');$('pan').classList.toggle('active',tool==='pan');$('hint').disabled=mode!=='build';$('erase').disabled=mode!=='build';$('pan').disabled=mode!=='build';$('stress').setAttribute('aria-pressed',String(stress));
$('materials').querySelectorAll('[data-tool]').forEach(b=>{b.classList.toggle('active',b.dataset.tool===tool);b.disabled=!L.materials.includes(b.dataset.tool);});$('vehicleBadge').textContent=L.vehicles.map(v=>v==='car'?'CAR':v==='truck'?'TRUCK':'HEAVY TANKER').join(' + ');
$('instruction').textContent=mode!=='build'?'Watch the load move through your bridge.':tool==='erase'?'Tap a member to remove it.':tool==='pan'?'Drag to move the view. Pinch or use +/− to zoom.':source?'Choose the next joint. Tap the starting joint to cancel.':L.id===1&&d.beams.length===3?'The road needs support. Add timber triangles underneath.':meta.autoJoints?'Tap two endpoints or drag. Intermediate joints are automatic.':'Tap a start and end joint, or drag between them.';}
function edit(){clearTimeout(resultTimer);mode='build';sim=null;source=null;gesture=null;scene.clearCars();scene.setDesign(d);acc=0;ui();}
function test(){if(mode!=='build'){edit();return;}if(!d.beams.some(b=>b.type==='road')){toast('Add a road before sending a vehicle.');return;}source=null;gesture=null;ghost=false;saveDraft();sim=B.create(L,d);mode='test';acc=0;scene.clearCars();scene.setDesign(d);ui();tone(660,.15);}
function result(){const win=sim.won,cost=B.cost(d),stars=assisted?1:sim.broken?1:cost<=L.budget*.75?3:2;mode=win?'won':'failed';if(win&&!sandbox){meta.stars[L.id]=Math.max(meta.stars[L.id]||0,stars);meta.best[L.id]=Math.min(meta.best[L.id]||Infinity,cost);meta.open=Math.min(24,Math.max(meta.open,L.id+1));save();}tone(win?880:180,.3);const first=sim.firstBreak;resultTimer=setTimeout(()=>{modal(`${title(win?'CROSSING COMPLETE':'BACK TO THE DRAWING BOARD',win?'A connection that holds.':'Every failure tells a story.')}<p>${win?`${sim.passed} vehicle${sim.passed===1?'':'s'} safely across ${L.span} meters.`:first?`A ${B.MAT[first.material].name.toLowerCase()} member failed near ${first.x.toFixed(1)} m. Add bracing around that joint or use a stronger material.`:'The vehicle could not reach the far bank. Check the road for gaps, steep sections, and unsupported joints.'}</p>${win?`<div class="stars">${'★'.repeat(stars)}<span style="opacity:.2">${'★'.repeat(3-stars)}</span></div>`:''}<div class="stats"><div><strong>${money(cost)}</strong>CONSTRUCTION COST</div><div><strong>${sim.broken}</strong>BROKEN MEMBERS</div><div><strong>${Math.round(sim.peak*100)}%</strong>PEAK LOAD</div></div><div class="actions">${win&&!sandbox&&L.id<24?button('nextSite','Next construction site →','primary'):button('editResult','Improve the design →','primary')}<div class="row">${button('returnEdit','Edit bridge')}${button('retest','Test again')}</div>${button('resultSites',sandbox?'Free-build settings':'Construction sites','quiet')}</div>`);bind('nextSite',()=>{start(L.id+1);close();});bind('editResult',()=>{edit();close();});bind('returnEdit',()=>{edit();close();});bind('retest',()=>{edit();close();test();});bind('resultSites',sandbox?freeMenu:siteMenu);},850);}
function resize(){if(!scene)return;const r=canvas.getBoundingClientRect();scene.resize(r.width,r.height);const ratio=Math.min(devicePixelRatio,2);canvas.width=Math.round(r.width*ratio);canvas.height=Math.round(r.height*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);source=null;gesture=null;}
function pt(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}
function snapped(p){let best=null,dist=Math.min(32,Math.max(18,.38/scene.scale));for(const n of d.nodes){const q=scene.project(n.x,n.y),delta=Math.hypot(q[0]-p.x,q[1]-p.y);if(delta<dist){dist=delta;best=n;}}if(best)return{x:best.x,y:best.y};const w=scene.unproject(p.x,p.y);return{x:Math.round(w.x*2)/2,y:Math.round(w.y*2)/2};}
function validPoint(p){return p.x>=-.01&&p.x<=L.span+.01&&p.y>=-4.01&&p.y<=L.rise+6.01;}
function addMember(a,b){if(!validPoint(a)||!validPoint(b)){toast('Build inside the grid, between the two banks.');return false;}const prev={d:B.clone(d),assisted};if(meta.autoJoints){const result=BW_AUTO.add(d,a,b,tool,L,sandbox);if(result.error){toast(result.error);tone(180);return false;}d=result.design;}else{const why=B.add(d,a,b,tool,L,sandbox);if(why){toast(why);tone(180);return false;}}undo.push(prev);if(undo.length>60)undo.shift();redo=[];source=meta.autoJoints?null:{...b};changed();return true;}
bind('autoJoints',()=>{meta.autoJoints=!meta.autoJoints;source=null;gesture=null;save();ui();toast(meta.autoJoints?'Draw a long section. Joints and pieces are placed automatically.':'Manual joints: build one member at a time.');});
bind('layRoad',()=>{if(mode!=='build')return;const result=BW_AUTO.add(d,{x:0,y:0},{x:L.span,y:L.rise},'road',L,sandbox);if(result.error){toast(result.error);return;}snapshot();d=result.design;source=null;changed();toast('Road laid with connected joints. Add supports, then test it.');});

function beamAt(p){let best=-1,dist=14;const map=new Map(d.nodes.map(n=>[n.id,n]));d.beams.forEach((b,i)=>{const a=scene.project(map.get(b.a).x,map.get(b.a).y),c=scene.project(map.get(b.b).x,map.get(b.b).y);const q=B.nearest(p.x,p.y,{x:a[0],y:a[1]},{x:c[0],y:c[1]}),v=Math.hypot(q.x-p.x,q.y-p.y);if(v<dist){dist=v;best=i;}});return best;}
canvas.addEventListener('pointerdown',e=>{if(mode!=='build'||paused())return;e.preventDefault();const p=pt(e);pointers.set(e.pointerId,p);canvas.setPointerCapture(e.pointerId);if(pointers.size===2){const a=[...pointers.values()];pinch={dist:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),zoom:scene.zoom,cx:(a[0].x+a[1].x)/2,cy:(a[0].y+a[1].y)/2};gesture=null;source=null;return;}if(pointers.size>1)return;gesture={id:e.pointerId,p,last:p,from:snapped(p),threshold:e.pointerType==='mouse'?9:20,moved:false};});
canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const p=pt(e);pointers.set(e.pointerId,p);if(pinch&&pointers.size===2){const a=[...pointers.values()];const cx=(a[0].x+a[1].x)/2,cy=(a[0].y+a[1].y)/2;scene.move(cx-pinch.cx,cy-pinch.cy);scene.setZoom(pinch.zoom*Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)/Math.max(20,pinch.dist),cx,cy);pinch.cx=cx;pinch.cy=cy;return;}if(!gesture||gesture.id!==e.pointerId)return;if(Math.hypot(p.x-gesture.p.x,p.y-gesture.p.y)>gesture.threshold)gesture.moved=true;if(tool==='pan'&&gesture.moved){scene.move(p.x-gesture.last.x,p.y-gesture.last.y);}else if(tool!=='erase'){gesture.to=snapped(p);if(gesture.moved){const len=Math.hypot(gesture.to.x-gesture.from.x,gesture.to.y-gesture.from.y);$('previewCost').textContent=len.toFixed(1)+' m · '+money(len*B.MAT[tool].cost);}}gesture.last=p;});
canvas.addEventListener('pointerup',e=>{const wasPinch=!!pinch;pointers.delete(e.pointerId);if(wasPinch){if(!pointers.size)pinch=null;gesture=null;return;}const g=gesture;gesture=null;$('previewCost').textContent='';if(!g||mode!=='build'||paused())return;const p=pt(e);if(tool==='pan')return;if(tool==='erase'){const i=beamAt(p);if(i>=0){snapshot();B.remove(d,i);source=null;changed();}return;}const end=g.moved?snapped(p):g.from;if(g.moved){addMember(g.from,end);}else if(source){if(Math.hypot(source.x-end.x,source.y-end.y)<.15){source=null;ui();}else addMember(source,end);}else{if(validPoint(end)){source=end;ui();}else toast('Start at a joint inside the grid.');}});
canvas.addEventListener('pointercancel',()=>{pointers.clear();gesture=null;pinch=null;source=null;});canvas.addEventListener('wheel',e=>{if(paused())return;e.preventDefault();const p=pt(e);scene.setZoom(scene.zoom*Math.exp(-Math.max(-80,Math.min(80,e.deltaY))*.0015),p.x,p.y);},{passive:false});
function line(a,b,color,width=1,dash=[]){const p=scene.project(a.x,a.y),q=scene.project(b.x,b.y);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.beginPath();ctx.moveTo(...p);ctx.lineTo(...q);ctx.stroke();ctx.setLineDash([]);}
function overlay(){const r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);if(mode!=='build'||!L)return;ctx.fillStyle='rgba(35,71,80,.22)';for(let x=0;x<=L.span;x++)for(let y=-4;y<=L.rise+6;y++){const q=scene.project(x,y);if(q[1]<100||q[1]>r.height-(r.width<600?215:108))continue;ctx.beginPath();ctx.arc(q[0],q[1],1.2,0,Math.PI*2);ctx.fill();}
if(ghost){const ref=B.example(L),map=new Map(ref.nodes.map(n=>[n.id,n]));for(const b of ref.beams)line(map.get(b.a),map.get(b.b),'rgba(91,149,191,.65)',2,[6,6]);}
for(const n of d.nodes){const p=scene.project(n.x,n.y);ctx.beginPath();ctx.arc(p[0],p[1],n.fixed?10:8,0,Math.PI*2);ctx.fillStyle=n.fixed?'#e4b761':'#f2f6ff';ctx.fill();ctx.lineWidth=1.5;ctx.strokeStyle=n.fixed?'#795f33':'#456d7a';ctx.stroke();}
let start=gesture?.moved?gesture.from:source,end=gesture?.moved?gesture.to:null;if(start){const p=scene.project(start.x,start.y);ctx.beginPath();ctx.arc(p[0],p[1],17,0,Math.PI*2);ctx.strokeStyle='#e5bc6d';ctx.lineWidth=2;ctx.stroke();if(end&&B.MAT[tool]){const len=Math.hypot(end.x-start.x,end.y-start.y);line(start,end,(meta.autoJoints||len<=B.MAT[tool].max)&&validPoint(end)?'#f0c46b':'#df674e',3,[7,5]);if(meta.autoJoints){for(const n of BW_AUTO.path(d,start,end,tool)){const q=scene.project(n.x,n.y);ctx.beginPath();ctx.arc(q[0],q[1],6,0,Math.PI*2);ctx.fillStyle='#f0c46b';ctx.fill();}}}}
}
function frame(ms){requestAnimationFrame(frame);const dt=Math.min(.075,last?(ms-last)/1000:0);last=ms;if(mode==='test'&&sim&&!paused()){acc+=dt*speed;let count=0;while(acc>=B.DT&&count<40&&mode==='test'){B.step(sim);acc-=B.DT;count++;for(const e of sim.events){if(e.type==='break'){sim.firstBreak||=e;scene.burst(e.x,e.y);tone(130,.06);}}sim.events=[];if(sim.won||sim.failed)result();}if(count===40)acc=0;$('crossed').textContent=sim.passed+' / '+L.vehicles.length+' vehicles';$('stressText').textContent=`Peak load ${Math.round(sim.peak*100)}% · ${sim.broken} broken members`;}
if(sim)scene.sync(sim,stress);overlay();scene.render(paused()?0:dt);}
$('materials').querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>select(b.dataset.tool));bind('erase',()=>select(tool==='erase'?'road':'erase'));bind('pan',()=>select(tool==='pan'?'road':'pan'));bind('undo',undoEdit);bind('redo',redoEdit);bind('hint',hint);bind('test',test);bind('menu',()=>menu());bind('stress',()=>{stress=!stress;ui();});bind('speed',()=>{speed=speed===1?2:1;ui();});bind('zoomIn',()=>scene.setZoom(scene.zoom*1.25));bind('zoomOut',()=>scene.setZoom(scene.zoom/1.25));bind('fit',()=>{scene.resetView();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(paused())close();else{source=null;menu();}return;}if(paused()||mode!=='build'||e.target.tagName==='SELECT')return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redoEdit():undoEdit();}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redoEdit();}else if('12345'.includes(e.key)){const t=Object.keys(B.MAT)[+e.key-1];if(L.materials.includes(t))select(t);}else if(e.key.toLowerCase()==='e')select('erase');else if(e.key.toLowerCase()==='p')select('pan');});
$('sheet').addEventListener('keydown',e=>{if(e.key!=='Tab')return;const list=[...$('card').querySelectorAll('button:not(:disabled),select,a[href]')];if(!list.length)return;if(e.shiftKey&&document.activeElement===list[0]){e.preventDefault();list[list.length-1].focus();}else if(!e.shiftKey&&document.activeElement===list[list.length-1]){e.preventDefault();list[0].focus();}});
window.addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{last=0;acc=0;gesture=null;pointers.clear();pinch=null;});window.addEventListener('pagehide',()=>{if(d)saveDraft();});
try{scene=build($('scene'));start(Math.max(1,Math.min(meta.open,meta.level)));$('loading').hidden=true;loaded=true;menu(true);requestAnimationFrame(frame);Goobs.markPlayed('bridge');Goobs.initUpdates();window.__bridge={B,get level(){return L},get design(){return d},get sim(){return sim},get mode(){return mode},get scene(){return scene},get meta(){return meta},start,test,edit,close,loadExample(){snapshot();d=B.example(L);assisted=true;changed();},select,undo:undoEdit,redo:redoEdit,add:addMember};}catch(e){console.error(e);$('loading').textContent='The 3D construction site could not start. Please reload or try another browser.';}
