import * as T from '../../shared/three.module.min.js';
const THEMES=[{name:'Cedar Valley',sky:0xb5d7e2,fog:0xc7dde0,grass:0x7d8d6c,rock:0xa1a299,water:0x337e86,tree:0x365b43,sun:0xffe9bc},{name:'Copper Canyon',sky:0xafd2dd,fog:0xe9c7aa,grass:0xc9a579,rock:0xb57754,water:0x43968b,tree:0x778456,sun:0xffd5a4},{name:'Alpine Reach',sky:0xb9d6e5,fog:0xdbe5e8,grass:0xe3e5df,rock:0x939e9e,water:0x477e9c,tree:0x354f4a,sun:0xfff0d9}];
function texture(w,h,fn){const c=document.createElement('canvas');c.width=w;c.height=h;fn(c.getContext('2d'),w,h);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;t.wrapS=t.wrapT=T.RepeatWrapping;return t;}
export function build(canvas){
const renderer=new T.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;renderer.setClearColor(0x000000,0);canvas.style.backgroundSize='cover';canvas.style.backgroundPosition='center';
const scene=new T.Scene(),camera=new T.OrthographicCamera(-10,10,7,-7,.1,250);const hemi=new T.HemisphereLight(0xe5f5ff,0x65755e,1.7);scene.add(hemi);const sun=new T.DirectionalLight(0xffe9bc,3.2);sun.position.set(-12,25,18);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.bias=-.0004;sun.shadow.normalBias=.035;scene.add(sun,sun.target);
const world=new T.Group(),bridge=new T.Group(),traffic=new T.Group(),particles=new T.Group();scene.add(world,bridge,traffic,particles);let level,theme,width=100,height=100,zoom=1,pan={x:0,y:0},scale=1,time=0,mode='build',records=[],bolts=[],cars=[],sparks=[];
const std=(color,roughness=.8,metalness=0)=>new T.MeshStandardMaterial({color,roughness,metalness});
const woodTex=texture(256,128,(c,w,h)=>{c.fillStyle='#c39765';c.fillRect(0,0,w,h);for(let i=0;i<100;i++){c.strokeStyle=i%3?'#79533228':'#f5d3a445';c.lineWidth=.5+Math.random();let y=Math.random()*h;c.beginPath();c.moveTo(0,y);c.bezierCurveTo(w*.3,y+4,w*.6,y-3,w,y);c.stroke();}});
const asphaltTex=texture(128,128,(c,w,h)=>{c.fillStyle='#526069';c.fillRect(0,0,w,h);for(let i=0;i<5000;i++){c.fillStyle=i%2?'#ffffff10':'#00000012';c.fillRect(Math.random()*w,Math.random()*h,1,1);}});
const rockTex=new T.TextureLoader().load('assets/limestone.webp');rockTex.colorSpace=T.SRGBColorSpace;rockTex.wrapS=rockTex.wrapT=T.RepeatWrapping;rockTex.anisotropy=4;
const grassTex=texture(256,256,(c,w,h)=>{c.fillStyle='#a8b79c';c.fillRect(0,0,w,h);for(let i=0;i<17000;i++){let x=Math.random()*w,y=Math.random()*h;c.strokeStyle=i%2?'#e3db9d30':'#304d3635';c.lineWidth=.6;c.beginPath();c.moveTo(x,y);c.lineTo(x+Math.random()*3-1.5,y-Math.random()*4);c.stroke();}});
const treeG=new T.PlaneGeometry(1,1),treeMap=new T.TextureLoader().load('assets/spruce.webp');treeMap.colorSpace=T.SRGBColorSpace;
const treeM=new T.MeshBasicMaterial({map:treeMap,transparent:true,alphaTest:.15,depthWrite:true,side:T.DoubleSide,color:0xb4c0a7});
grassTex.repeat.set(12,6);
const woodM=new T.MeshStandardMaterial({map:woodTex,roughness:.85}),steelM=std(0x7796a0,.33,.65),cableM=std(0xc8d0cb,.3,.8),concreteM=std(0xb9b7ab,.94),roadM=new T.MeshStandardMaterial({map:asphaltTex,roughness:.94}),boltM=std(0xdbe3dd,.25,.85),darkM=std(0x273744,.45,.55),yellowM=std(0xf1c96a,.5),glassM=std(0x344f61,.17,.4);
const unitBox=new T.BoxGeometry(1,1,1),sphere=new T.SphereGeometry(1,10,8),cylinder=new T.CylinderGeometry(1,1,1,10);
function mesh(parent,geo,mat,x,y,z,sx=1,sy=1,sz=1){const m=new T.Mesh(geo,mat);m.position.set(x,y,z);m.scale.set(sx,sy,sz);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function box(parent,mat,x,y,z,w,h,d){return mesh(parent,unitBox,mat,x,y,z,w,h,d);}
function clear(group){while(group.children.length)group.remove(group.children[0]);}
function makeTerrain(){clear(world);theme=THEMES[level.region];scene.background=null;canvas.style.backgroundImage='url(assets/'+['valley','canyon','alpine'][level.region]+'.webp)';scene.fog=new T.Fog(theme.fog,40,135);hemi.groundColor.setHex(0x798278);sun.color.setHex(theme.sun);sun.target.position.set(level.span/2,0,0);sun.position.set(level.span/2-14,25,18);Object.assign(sun.shadow.camera,{left:-level.span-7,right:level.span+7,top:20,bottom:-20,near:1,far:80});sun.shadow.camera.updateProjectionMatrix();
const rock=new T.MeshStandardMaterial({color:theme.rock,map:rockTex,bumpMap:rockTex,bumpScale:.13,roughness:.98}),grass=new T.MeshStandardMaterial({color:theme.grass,map:level.region===2?null:grassTex,roughness:.98});let seed=1234+level.region*500;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
for(const side of [-1,1]){const cx=side<0?-15:level.span+15,top=side<0?0:level.rise;const profile=new T.Shape();profile.moveTo(-30,0);profile.lineTo(0,0);profile.lineTo(-.2,-.8);profile.lineTo(-.05,-1.8);profile.lineTo(-.4,-3.2);profile.lineTo(-.7,-5);profile.lineTo(-1.2,-8);profile.lineTo(-2,-20);profile.lineTo(-30,-20);profile.closePath();const cliffGeo=new T.ExtrudeGeometry(profile,{depth:8,bevelEnabled:false,steps:1});const uv=cliffGeo.attributes.uv;for(let u=0;u<uv.count;u++)uv.setXY(u,uv.getX(u)/5,uv.getY(u)/5);const cliff=new T.Mesh(cliffGeo,rock);cliff.position.set(side<0?0:level.span,top,-6.5);cliff.scale.x=side<0?1:-1;cliff.castShadow=true;cliff.receiveShadow=true;world.add(cliff);box(world,grass,cx,top-.02,-2.5,30,.12,8);
for(let j=0;j<18;j++){const x=side<0?-.3-random()*2:level.span+.3+random()*2;mesh(world,new T.DodecahedronGeometry(1,1),rock,x,top-3-random()*3,random()*7-6,.5+random(),.6+random(),.7+random());}
// Abutments and safety markers frame the connection points.
box(world,concreteM,side<0?-.23:level.span+.23,top-.55,0,.48,1.1,2.5);box(world,roadM,side<0?-7:level.span+7,top+.025,0,14,.1,1.9);
for(let x=1;x<15;x+=1.6){const xx=side<0?-x:level.span+x;box(world,yellowM,xx,top+.084,0,.6,.016,.045);}
for(const z of [-1.15,1.15]){box(world,concreteM,side<0?-.5:level.span+.5,top+.25,z,.2,.5,.2);box(world,yellowM,side<0?-.5:level.span+.5,top+.48,z,.22,.06,.22);}}
// Mountain terrain: several ridges, natural variation, and snow by altitude.
const mountain=new T.PlaneGeometry(180,110,100,65);mountain.rotateX(-Math.PI/2);const pos=mountain.attributes.position,colors=[];const grassC=new T.Color(theme.grass),rockC=new T.Color(theme.rock),snowC=new T.Color(0xf1f0e8);for(let i=0;i<pos.count;i++){let x=pos.getX(i)+level.span/2,z=pos.getZ(i)-73;let ridge=8+5*Math.sin(x*.11+z*.035)+4*Math.sin(x*.23-z*.14)+2*Math.cos(x*.47+z*.18);let valley=Math.exp(-1*((x-level.span/2)/9)**2)*7;let y=Math.max(-5,ridge-valley+Math.sin(z*.15)*3);pos.setXYZ(i,x,y,z);let color=grassC.clone().lerp(rockC,Math.min(1,Math.max(0,(y-5)/10)));if(y>(level.region===2?7:14))color.lerp(snowC,Math.min(1,(y-(level.region===2?7:14))/3));color.multiplyScalar(.75+random()*.16);colors.push(color.r,color.g,color.b);}mountain.setAttribute('color',new T.Float32BufferAttribute(colors,3));mountain.computeVertexNormals();const range=new T.Mesh(mountain,new T.MeshStandardMaterial({vertexColors:true,roughness:1}));range.receiveShadow=true;// Distant scenery is a high-detail photographic panorama.
mountain.dispose();range.material.dispose();
const water=new T.Mesh(new T.PlaneGeometry(level.span+5,35,1,1),new T.ShaderMaterial({transparent:false,uniforms:{time:{value:0},col:{value:new T.Color(theme.water)}},vertexShader:'varying vec2 p;void main(){p=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform float time;uniform vec3 col;varying vec2 p;void main(){float a=sin(p.x*80.+sin(p.y*170.+time*.2)*.4+time*.3);float b=sin(p.y*380.-time*.5+p.x*11.);float wave=pow(max(0.,a*b),18.);vec3 c=col+vec3(wave*.035)+vec3(sin(p.y*25.+p.x*16.)*.013);gl_FragColor=vec4(c,1.);\n#include <tonemapping_fragment>\n#include <colorspace_fragment>\n}'}));water.rotation.x=-Math.PI/2;water.position.set(level.span/2,-5.7,4);water.userData.water=true;water.visible=false;world.add(water);
const treeTrunk=std(level.region===1?0x726b49:0x6e5946),leaf=std(theme.tree),leaf2=std(level.region===2?0xd3dfd9:level.region===1?0x89955e:0x638356);
const trunks=new T.InstancedMesh(new T.CylinderGeometry(.08,.14,1,7),treeTrunk,180),foliage=new T.InstancedMesh(new T.ConeGeometry(.9,2.7,10),leaf,180),tips=new T.InstancedMesh(new T.ConeGeometry(.61,1.8,10),leaf2,180);const dummy=new T.Object3D();let count=0;
for(let i=0;i<180;i++){let side=i%2?-1:1,x=side<0?-1.8-random()*26:level.span+1.8+random()*26,z=-3-random()*38,h=side<0?0:level.rise,s=.65+random()*.85;if(level.region===1&&i%3)continue;dummy.position.set(x,h+.5*s,z);dummy.scale.set(s,s,s);dummy.updateMatrix();trunks.setMatrixAt(count,dummy.matrix);dummy.position.y=h+(level.region===1?.9:1.6)*s;dummy.scale.set(s,level.region===1?s*.6:s,s);dummy.updateMatrix();foliage.setMatrixAt(count,dummy.matrix);dummy.position.y=h+(level.region===1?1.3:2.6)*s;dummy.updateMatrix();tips.setMatrixAt(count,dummy.matrix);count++;}for(const im of [trunks,foliage,tips]){im.geometry.dispose();}
if(level.region!==1){const trees=new T.InstancedMesh(treeG,treeM,36);const tm=new T.Object3D();for(let i=0;i<36;i++){const side=i%2?-1:1,x=side<0?-2-random()*17:level.span+2+random()*17,z=-.5-random()*5,h=side<0?0:level.rise,sz=1.7+random()*2.3;tm.position.set(x,h+sz/2,z);tm.scale.set(sz*.68,sz,1);tm.updateMatrix();trees.setMatrixAt(i,tm.matrix);}world.add(trees);}
// A riverside work site gives the scene a human scale.
const hut=new T.Group();hut.position.set(-5,0,-5);box(hut,std(0xb4aa8b),0,.8,0,2.8,1.6,1.8);const roof=mesh(hut,new T.CylinderGeometry(1.8,1.8,2.2,3),std(0x526771),0,1.8,0,1,1,1);roof.rotation.z=Math.PI/2;roof.rotation.y=Math.PI/2;box(hut,glassM,.65,.95,1,.6,.55,.04);box(hut,woodM,-.45,.55,.95,.55,1.1,.06);world.add(hut);
for(const a of level.anchors.slice(4)){box(world,concreteM,a[0],(-6+a[1])/2,0,.9,a[1]+6,2.1);box(world,yellowM,a[0],a[1]+.02,0,1,.08,2.2);}
}
function member(b,map){const a=map.get(b.a),c=map.get(b.b),group=new T.Group(),m=(b.type==='wood'?woodM:b.type==='steel'?steelM:b.type==='cable'?cableM:b.type==='concrete'?concreteM:roadM).clone();group.userData.material=m;bridge.add(group);
if(b.type==='road'){box(group,m,0,0,0,1,.13,1.8);for(const z of [-.94,.94]){box(group,steelM,0,-.11,z,1,.14,.075);}box(group,yellowM,0,.077,0,.32,.012,.05);}
else for(const z of [-.95,.95]){if(b.type==='steel'){box(group,m,0,0,z,1,.16,.08);box(group,m,0,.10,z,1,.04,.22);box(group,m,0,-.10,z,1,.04,.22);}else if(b.type==='cable'){const cable=mesh(group,cylinder,m,0,0,z,.035,1,.035);cable.rotation.z=Math.PI/2;}else box(group,m,0,0,z,1,b.type==='concrete'?.35:.16,b.type==='concrete'?.36:.18);}
const rec={group,m,b};setMember(rec,a,c);return rec;}
function setMember(r,a,b){const len=Math.hypot(b.x-a.x,b.y-a.y);r.group.position.set((a.x+b.x)/2,(a.y+b.y)/2,0);r.group.rotation.z=Math.atan2(b.y-a.y,b.x-a.x);r.group.scale.x=len;}
function setDesign(d){records.forEach(r=>r.m.dispose());clear(bridge);records=[];bolts=[];const map=new Map(d.nodes.map(n=>[n.id,n]));records=d.beams.map(b=>member(b,map));for(const n of d.nodes){const g=new T.Group();for(const z of [-.96,.96])mesh(g,sphere,n.fixed?yellowM:boltM,0,0,z,n.fixed?.14:.085,n.fixed?.14:.085,.06);g.position.set(n.x,n.y,0);bridge.add(g);bolts.push({group:g,id:n.id});}}
function makeCar(c){const group=new T.Group(),paint=std(c.type==='car'?0xecb750:c.type==='truck'?0xb96847:0xa4b7b9,.34,.22),wheels=[];box(group,darkM,0,-.17,0,c.half*2+.4,.2,1.1);
if(c.type==='car'){box(group,paint,0,.07,0,1.9,.44,1.1);box(group,paint,-.15,.45,0,1.02,.42,1.0);box(group,glassM,.03,.47,.515,.53,.27,.015);box(group,glassM,-.55,.47,.515,.34,.27,.015);box(group,glassM,.38,.47,0,.02,.29,.9);box(group,paint,.04,.45,.53,.04,.38,.03);}
else{box(group,paint,.76,.34,0,.95,1.0,1.15);box(group,glassM,.8,.63,.59,.57,.37,.02);box(group,glassM,1.25,.63,0,.02,.4,1.0);if(c.type==='truck'){box(group,std(0xe1d7bb),-.55,.52,0,1.8,1.2,1.2);for(let x=-1.3;x<.1;x+=.3)box(group,steelM,x,.55,.62,.025,1.1,.025);}else{let tank=mesh(group,new T.CylinderGeometry(.65,.65,2.1,20),std(0xcbd3d3,.27,.72),-.55,.6,0,1,1,1);tank.rotation.z=Math.PI/2;box(group,yellowM,-.55,.6,.66,1.8,.12,.02);}}
for(const x of [-c.half,c.half])for(const z of [-.64,.64]){const wheel=new T.Group();const tire=mesh(wheel,new T.CylinderGeometry(c.r,c.r,.18,18),std(0x202b2b,.9),0,0,0);tire.rotation.x=Math.PI/2;const hub=mesh(wheel,new T.CylinderGeometry(c.r*.52,c.r*.52,.20,12),boltM,0,0,0);hub.rotation.x=Math.PI/2;wheel.position.set(x,-c.h,z);group.add(wheel);wheels.push(wheel);}for(const z of [-.38,.38])box(group,std(0xfff1c4,.25),c.type==='car'?1:1.26,.13,z,.035,.13,.18);traffic.add(group);return {group,wheels};}
function sync(s,stress=false){const nodes=new Map(s.nodes.map(n=>[n.id,n]));records.forEach((r,i)=>{const b=s.beams[i];r.group.visible=!b.broken;if(!b.broken){setMember(r,b.A,b.B);if(stress){const c=new T.Color(b.stress<.5?0x51c7a2:b.stress<.85?0xe4be55:0xec6243);r.m.color.copy(c);r.m.emissive.copy(c).multiplyScalar(.12);}else{r.m.color.copy((b.type==='wood'?woodM:b.type==='steel'?steelM:b.type==='cable'?cableM:b.type==='concrete'?concreteM:roadM).color);r.m.emissive.setHex(0);}}});bolts.forEach(b=>{const n=nodes.get(b.id);b.group.position.set(n.x,n.y,0);});while(cars.length<s.cars.length)cars.push(makeCar(s.cars[cars.length]));s.cars.forEach((c,i)=>{cars[i].group.position.set(c.x,c.y,0);cars[i].group.rotation.z=c.a;cars[i].group.visible=!c.done;cars[i].wheels.forEach(w=>w.rotation.z=-c.x/c.r);});}
function burst(x,y){for(let i=0;i<10;i++){const m=mesh(particles,unitBox,woodM,x,y,.95,.07,.07,.07);sparks.push({m,vx:(Math.random()-.5)*3,vy:Math.random()*3,life:1.2});}}
function setLevel(L,d){level=L;makeTerrain();clear(traffic);cars=[];clear(particles);sparks=[];zoom=1;pan={x:0,y:0};setDesign(d);fit();}
function fit(){if(!level)return;const mobile=width<=600,short=height<=480,left=mobile?18:155,right=18,top=short?78:105,bottom=mobile?245:short?105:150,availableW=Math.max(200,width-left-right),availableH=Math.max(150,height-top-bottom);scale=Math.max((level.span+2)/availableW,(level.rise+6.5)/availableH)/zoom;const cx=level.span/2+pan.x-(left-right)*scale/2,cy=level.rise/2-.65+pan.y+(top-bottom)*scale/2;camera.position.set(cx,cy+7,36);camera.lookAt(cx,cy,0);camera.left=-width*scale/2;camera.right=width*scale/2;camera.top=height*scale/2;camera.bottom=-height*scale/2;camera.updateProjectionMatrix();camera.updateMatrixWorld();}
function resize(w,h){width=w;height=h;renderer.setSize(w,h,false);fit();}
function project(x,y,z=.96){const p=new T.Vector3(x,y,z).project(camera);return [(p.x+1)*width/2,(1-p.y)*height/2];}
const ray=new T.Raycaster();function unproject(x,y){ray.setFromCamera(new T.Vector2(x/width*2-1,1-y/height*2),camera);const r=ray.ray,k=(.96-r.origin.z)/r.direction.z;return {x:r.origin.x+r.direction.x*k,y:r.origin.y+r.direction.y*k};}
function setZoom(z,x,y){const anchor=Number.isFinite(x)&&Number.isFinite(y)?unproject(x,y):null;zoom=Math.min(3.5,Math.max(.7,z));fit();if(anchor){const after=unproject(x,y);pan.x+=anchor.x-after.x;pan.y+=anchor.y-after.y;fit();}return zoom;}function move(dx,dy){pan.x-=dx*scale;pan.y+=dy*scale;fit();}
function render(dt){time+=dt;world.children.forEach(m=>{if(m.userData.water)m.material.uniforms.time.value=time;});for(let i=sparks.length-1;i>=0;i--){const p=sparks[i];p.life-=dt;p.vy-=9.8*dt;p.m.position.x+=p.vx*dt;p.m.position.y+=p.vy*dt;p.m.rotation.z+=dt*4;if(p.life<=0){particles.remove(p.m);sparks.splice(i,1);}}renderer.render(scene,camera);}
return {setLevel,setDesign,sync,resize,project,unproject,setZoom,move,fit,burst,render,resetView(){zoom=1;pan={x:0,y:0};fit();},clearCars(){clear(traffic);cars=[];},get zoom(){return zoom},get scale(){return scale},scene,camera,renderer,themes:THEMES};
}
