(()=>{'use strict';const B=FK,$=id=>document.getElementById(id),store=Goobs.store('farkle'),fmt=n=>n.toLocaleString();let s=store.get('state',null),sound=store.get('sound',true),busy=false,aiAt=0,notice='',audio;
if(!s||s.version!==1||!Array.isArray(s.players))s=null;
const faces={1:[4],2:[0,8],3:[0,4,8],4:[0,2,6,8],5:[0,2,4,6,8],6:[0,2,3,5,6,8]};
function save(){store.set('state',s);}function beep(low=false){if(!sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=low?140:520;g.gain.setValueAtTime(.055,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.16);o.start();o.stop(audio.currentTime+.17);}catch(e){}}
function modal(html){$('panel').innerHTML=html;$('sheet').hidden=false;$('panel').querySelector('button,select,a')?.focus();}function close(){$('sheet').hidden=true;aiAt=Date.now()+700;render();$('menu').focus();}
function menu(){modal('<span class="eyebrow">GOOBS TABLETOP</span><h1 id="title">Farkle</h1><p>Six dice. A little nerve. Keep scoring dice, then bank your points—or risk them on another roll.</p><div class="buttons">'+(s?'<button id="resume" class="primary">'+(s.phase==='over'?'View results':'Resume game')+'</button>':'')+'<button id="new" class="'+(!s?'primary':'')+'">New game</button><button id="learn">How to play & scoring</button></div><a class="exit" href="../../index.html">‹ Exit to Games</a>');if(s)$('resume').onclick=()=>{close();if(s.phase==='over')results();};$('new').onclick=setup;$('learn').onclick=()=>rules(true);}
function setup(){const o=store.get('options',{})||{};modal('<button class="close" id="back" aria-label="Back to menu">×</button><span class="eyebrow">MAKE IT YOUR TABLE</span><h2 id="title">New game</h2><label class="field">Play<select id="mode"><option value="cpu">Against computer</option><option value="local">Pass & play</option></select></label><label class="field" id="playersField">Players<select id="players">'+[2,3,4,5,6].map(n=>'<option>'+n+'</option>').join('')+'</select></label><label class="field">Target score<select id="target"><option value="10000">10,000 · Classic</option><option value="5000">5,000 · Quick</option></select></label><label class="field">First bank minimum<select id="opening"><option value="500">500 points</option><option value="0">No minimum</option></select></label><label class="field">Three 1s score<select id="ones"><option value="300">300 points</option><option value="1000">1,000 points</option></select></label><p class="tiny">Reaching the target starts one final turn for every other player. Highest score wins.</p><div class="buttons"><button class="primary" id="start">Let’s roll</button></div>');$('mode').value=o.mode||'cpu';$('players').value=o.players||2;$('target').value=o.goal||10000;$('opening').value=o.opening??500;$('ones').value=o.ones||300;const mode=()=>$('playersField').hidden=$('mode').value==='cpu';$('mode').onchange=mode;mode();$('back').onclick=menu;$('start').onclick=()=>start({mode:$('mode').value,players:+$('players').value,goal:+$('target').value,opening:+$('opening').value,ones:+$('ones').value});}
function start(o){busy=false;store.set('options',o);s=B.create(o);notice='';save();close();}
function rules(fromMenu=false){const ones=s?s.options.ones:store.get('options',{}).ones||300;modal('<button class="close" id="back" aria-label="Close scoring chart">×</button><span class="eyebrow">KEEP • ROLL • BANK</span><h2 id="title">How to play</h2><p>Roll, then tap any scoring dice to keep them. <b>Keep & roll</b> risks your turn’s points with the remaining dice. <b>Bank</b> saves them and ends your turn. Select best highlights the highest-scoring selection.</p><table class="ruleTable">'+[['Single 1','100'],['Single 5','50'],['Three 1s',fmt(ones)],['Three 2s–6s','Face × 100'],['Four / five / six of a kind','1,000 / 2,000 / 3,000'],['Straight 1–6','1,500'],['Three pairs','1,500'],['Four of a kind + a pair','1,500'],['Two triplets','2,500']].map(r=>'<tr><td>'+r[0]+'</td><td>'+r[1]+'</td></tr>').join('')+'</table><p><b>Hot dice:</b> score all six dice and you may roll all six again, adding to the same turn. You can also bank instead.</p><p><b>Farkle:</b> roll no scoring dice and lose every unbanked point. Combinations must come from one roll; kept dice cannot join later combinations.</p><p>Your first bank needs '+(s?fmt(s.options.opening):'500')+' points. After someone reaches the target, everyone else gets one final turn. Highest total wins; tied leaders share the win.</p>');$('back').onclick=fromMenu?menu:close;}
function results(){modal('<span class="eyebrow">THE TABLE HAS SPOKEN</span><h2 id="title">'+s.winners.map(i=>s.players[i].name).join(' & ')+' '+(s.winners.length>1?'tie!':'win'+(s.players[s.winners[0]].name==='You'?'':'s')+'!')+'</h2><div class="results">'+s.players.map((p,i)=>'<div>'+ (s.winners.includes(i)?'★ ':'')+p.name+' <strong>'+fmt(p.total)+'</strong></div>').join('')+'</div><p>Best bank: '+fmt(s.bestTurn)+' points.</p><div class="buttons"><button id="again" class="primary">Play again</button><button id="change">Change setup</button></div><a class="exit" href="../../index.html">‹ Exit to Games</a>');$('again').onclick=()=>start({...s.options,players:s.players.length});$('change').onclick=setup;}
function render(){const t=s||B.create(),p=t.players[t.current],v=B.selectedScore(t),cpu=p.cpu,locked=busy||cpu||!s;const end=t.phase==='end'||t.phase==='over';$('scoreRules').innerHTML=[['Single 1','100'],['Single 5','50'],['Three 1s',fmt(t.options.ones)],['Three 2s–6s','Face × 100'],['Four of a kind','1,000'],['Five of a kind','2,000'],['Six of a kind','3,000'],['Straight 1–6','1,500'],['3 pairs / 4 + pair','1,500'],['Two triplets','2,500']].map(r=>'<div><span>'+r[0]+'</span><b>'+r[1]+'</b></div>').join('');$('scores').className=t.players.length>4?'many':'';$('scores').innerHTML=t.players.map((p,i)=>'<div class="scorecard '+(i===t.current?'active':'')+'"><span>'+p.name+'</span><strong>'+fmt(p.total)+'</strong><small>'+(p.total?'BANKED':'NOT ON THE BOARD')+'</small></div>').join('');$('round').textContent=t.finalRemaining!==null?'FINAL ROUND · '+t.finalRemaining+' TURN'+(t.finalRemaining===1?'':'S')+' LEFT':'ROUND '+t.round;$('turnLabel').textContent=end?'TURN COMPLETE':p.name.toUpperCase()+(p.name==='You'?'R TURN':'’S TURN');$('pot').textContent=fmt(t.pot+(v.valid?v.points:0));$('potCaption').textContent=v.valid?'TURN TOTAL · '+fmt(v.points)+' SELECTED':'POINTS AT RISK';$('dice').innerHTML=t.dice.map(d=>'<button class="die '+(d.held?'held ':'')+(t.selected.includes(d.id)?'selected ':'')+(busy&&!d.held?'rolling':'')+'" data-id="'+d.id+'" aria-label="Die '+(d.id+1)+': '+d.value+(d.held?', kept':'')+'" aria-pressed="'+t.selected.includes(d.id)+'" '+(locked||t.phase!=='choose'||d.held?'disabled':'')+'>'+Array.from({length:9},(_,i)=>'<span class="pip '+(faces[d.value].includes(i)?'on':'')+'"></span>').join('')+'</button>').join('');
let msg=notice||'Roll to start your turn.',detail='Keep scoring dice or bank your points.';if(t.phase==='choose'){msg=v.valid?fmt(v.points)+' points selected':v.label;detail=p.total===0&&t.pot+(v.valid?v.points:0)<t.options.opening?'First bank needs '+fmt(t.options.opening)+' points.':'Tap dice to select or deselect them.';}if(end&&t.last){msg=t.last.farkle?'Farkle! '+fmt(t.last.lost)+' points lost.':fmt(t.last.banked)+' points banked!';detail=t.phase==='over'?'Game complete.':t.players[(t.current+1)%t.players.length].name+' plays next.';}if(busy){msg='Rolling…';detail='';}$('selection').textContent=msg;$('detail').textContent=detail;$('suggest').disabled=locked||t.phase!=='choose';$('roll').textContent=t.phase==='over'?'View results':t.phase==='end'?'Next: '+t.players[(t.current+1)%t.players.length].name:t.phase==='choose'?'Keep & roll':'Roll '+t.dice.filter(d=>!d.held).length+' dice';$('roll').disabled=busy||cpu&&t.phase!=='end'&&t.phase!=='over'||t.phase==='choose'&&!v.valid;$('bank').disabled=locked||!B.canBank(t);$('bank').textContent='Bank'+(v.valid?' '+fmt(t.pot+v.points):' points');$('goal').textContent='TARGET '+fmt(t.options.goal)+' · THEN FINAL ROUND';$('sound').textContent='Sound '+(sound?'on':'off');}
function finish(){save();render();if(s.phase==='over'){if(!s.recorded){s.recorded=true;const m=store.get('meta',{games:0,wins:0});m.games++;if(s.options.mode==='cpu'&&s.winners.includes(0))m.wins++;store.set('meta',m);save();}results();}}
function roll(){if(busy||!s||s.phase!=='ready')return;busy=true;const rollingState=s,result=B.roll(s);save();render();beep();const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,items=[...$('dice').querySelectorAll('.rolling')];let longest=0;
function face(el,value){el.querySelectorAll('.pip').forEach((pip,i)=>pip.classList.toggle('on',faces[value].includes(i)));}
items.forEach((el,i)=>{const id=+el.dataset.id,final=s.dice[id].value,duration=reduced?180:780+i*65,sign=id%2?1:-1;longest=Math.max(longest,duration);if(!reduced){face(el,1+Math.floor(Math.random()*6));el.animate([{transform:'perspective(500px) translate(0,0) rotateX(0deg) rotateY(0deg) rotateZ(0deg)',offset:0},{transform:'perspective(500px) translate('+sign*9+'px,-17px) rotateX(150deg) rotateY('+sign*120+'deg) rotateZ('+sign*22+'deg)',offset:.28},{transform:'perspective(500px) translate('+(-sign*5)+'px,-7px) rotateX(290deg) rotateY('+sign*270+'deg) rotateZ('+(-sign*14)+'deg)',offset:.57},{transform:'perspective(500px) translate(0,2px) rotateX(360deg) rotateY('+sign*360+'deg) rotateZ(4deg)',offset:.8},{transform:'perspective(500px) translate(0,-4px) rotateX(360deg) rotateY('+sign*360+'deg) rotateZ(-2deg)',offset:.9},{transform:'perspective(500px) translate(0,0) rotateX(360deg) rotateY('+sign*360+'deg) rotateZ(0deg)',offset:1}],{duration,easing:'cubic-bezier(.2,.6,.35,1)'});const cycle=setInterval(()=>{if(s!==rollingState){clearInterval(cycle);return;}face(el,1+Math.floor(Math.random()*6));},75);setTimeout(()=>{clearInterval(cycle);face(el,final);el.classList.remove('rolling');},duration-110);}});
setTimeout(()=>{if(s!==rollingState)return;busy=false;notice=result.farkle?'Farkle!':'Choose your scoring dice.';if(result.farkle)beep(true);else beep();aiAt=Date.now()+850;finish();},longest+30);}

function keepRoll(){const r=B.keep(s);if(r.error)return;notice=r.hot?'Hot dice! All six are back in play.':'';roll();}
function bank(){const r=B.bank(s);if(r.error)return;beep();aiAt=Date.now()+1100;finish();}
$('dice').onclick=e=>{const d=e.target.closest('[data-id]');if(d&&!busy&&!s.players[s.current].cpu){B.toggle(s,+d.dataset.id);save();render();}};$('suggest').onclick=()=>{s.selected=B.best(s.dice.filter(d=>!d.held),s.options.ones).ids;save();render();};$('roll').onclick=()=>{if(s.phase==='over')results();else if(s.phase==='end'){B.next(s);notice='';aiAt=Date.now()+650;finish();}else if(s.phase==='choose')keepRoll();else roll();};$('bank').onclick=bank;$('menu').onclick=menu;$('rules').onclick=()=>rules();$('sound').onclick=()=>{sound=!sound;store.set('sound',sound);beep();render();};
let aiSelected=false;setInterval(()=>{if(!s||busy||!$('sheet').hidden||document.hidden||Date.now()<aiAt||!s.players[s.current].cpu||s.phase==='over')return;aiAt=Date.now()+900;if(s.phase==='ready'){aiSelected=false;roll();}else if(s.phase==='choose'){const c=B.cpuChoice(s);if(!aiSelected){s.selected=c.ids;aiSelected=true;save();render();}else{aiSelected=false;c.bank?bank():keepRoll();}}else if(s.phase==='end'){B.next(s);aiSelected=false;notice='';finish();}},150);
document.addEventListener('keydown',e=>{if(!$('sheet').hidden||busy||!s||s.players[s.current].cpu)return;const key=e.key.toLowerCase();if(/^[1-6]$/.test(key)){B.toggle(s,+key-1);save();render();}else if(key==='r'&&!$('roll').disabled)$('roll').click();else if(key==='b'&&!$('bank').disabled)bank();});
window.__farkle={get state(){return s;},start,render,roll,bank,keepRoll};render();menu();
})();
