/* Farkle scoring applies only to dice from the current roll. */
(function(root){'use strict';const clone=x=>JSON.parse(JSON.stringify(x));
function score(values,ones=300){if(!values.length)return {points:0,valid:false,label:'Select scoring dice'};const c=Array(7).fill(0);for(const v of values){if(!Number.isInteger(v)||v<1||v>6)return {points:0,valid:false,label:'Invalid die'};c[v]++;}const counts=c.slice(1).filter(Boolean).sort((a,b)=>a-b);if(values.length===6){if(counts.length===6)return {points:1500,valid:true,label:'Straight · 1–6'};if(counts.join()==='2,2,2')return {points:1500,valid:true,label:'Three pairs'};if(counts.join()==='2,4')return {points:1500,valid:true,label:'Four of a kind + pair'};if(counts.join()==='3,3')return {points:2500,valid:true,label:'Two triplets'};}let points=0,labels=[];for(let v=1;v<=6;v++){let n=c[v];if(!n)continue;if(n>=3){const p=n===6?3000:n===5?2000:n===4?1000:v===1?ones:v*100;points+=p;labels.push(n+' × '+v);}else if(v===1||v===5){points+=n*(v===1?100:50);labels.push(n+' × '+v);}else return {points:0,valid:false,label:'Every selected die must score'};}return {points,valid:true,label:labels.join(' + ')};}
function best(dice,ones){let chosen=[],points=0;for(let mask=1;mask<(1<<dice.length);mask++){const ids=[],vals=[];dice.forEach((d,i)=>{if(mask&(1<<i)){ids.push(d.id);vals.push(d.value);}});const v=score(vals,ones);if(v.valid&&(v.points>points||v.points===points&&ids.length>chosen.length)){points=v.points;chosen=ids;}}return {ids:chosen,points};}
function create(opts={}){const mode=opts.mode||'cpu',n=mode==='cpu'?2:Math.max(2,Math.min(6,+opts.players||2));return {version:1,options:{mode,goal:+opts.goal===5000?5000:10000,opening:+opts.opening===0?0:500,ones:+opts.ones===1000?1000:300},players:Array.from({length:n},(_,i)=>({name:mode==='cpu'?(i?'Computer':'You'):'Player '+(i+1),cpu:mode==='cpu'&&i===1,total:0})),current:0,dice:Array.from({length:6},(_,id)=>({id,value:1,held:false})),selected:[],pot:0,phase:'ready',round:1,finalRemaining:null,trigger:null,log:[],last:null,rolls:0,bestTurn:0,winners:[]};}
function selectedScore(s){return score(s.dice.filter(d=>!d.held&&s.selected.includes(d.id)).map(d=>d.value),s.options.ones);}
function toggle(s,id){if(s.phase!=='choose'||s.dice[id]?.held)return false;s.selected=s.selected.includes(id)?s.selected.filter(i=>i!==id):s.selected.concat(id);return true;}
function keep(s){const v=selectedScore(s);if(s.phase!=='choose'||!v.valid)return {error:'Select a scoring group first.'};s.dice.forEach(d=>{if(s.selected.includes(d.id))d.held=true;});s.pot+=v.points;s.selected=[];const hot=s.dice.every(d=>d.held);if(hot)s.dice.forEach(d=>d.held=false);s.phase='ready';return {points:v.points,hot};}
function canBank(s){const v=selectedScore(s);return s.phase==='choose'&&v.valid&&(s.players[s.current].total>0||s.pot+v.points>=s.options.opening);}
function end(s,banked,lost=0){const player=s.players[s.current];if(banked)player.total+=banked;s.bestTurn=Math.max(s.bestTurn,banked);s.last={player:s.current,banked,lost,farkle:!banked};s.log.unshift({name:player.name,...s.last});s.log=s.log.slice(0,10);if(s.finalRemaining===null&&player.total>=s.options.goal){s.trigger=s.current;s.finalRemaining=s.players.length-1;}else if(s.finalRemaining!==null)s.finalRemaining--;s.selected=[];s.pot=0;if(s.finalRemaining===0){const max=Math.max(...s.players.map(p=>p.total));s.winners=s.players.map((p,i)=>p.total===max?i:-1).filter(i=>i>=0);s.phase='over';}else s.phase='end';}
function roll(s,random=Math.random){if(s.phase!=='ready')return {error:'Keep scoring dice before rolling again.'};for(const d of s.dice)if(!d.held)d.value=1+Math.floor(random()*6);s.rolls++;s.selected=[];if(!best(s.dice.filter(d=>!d.held),s.options.ones).points){const lost=s.pot;end(s,0,lost);return {farkle:true,lost};}s.phase='choose';return {farkle:false};}
function bank(s){if(!canBank(s))return {error:'Your first bank must be at least '+s.options.opening+'.'};const r=keep(s),points=s.pot;end(s,points);return {points,hot:r.hot};}
function next(s){if(s.phase!=='end')return false;s.current=(s.current+1)%s.players.length;if(s.current===0)s.round++;s.dice.forEach(d=>{d.held=false;});s.pot=0;s.selected=[];s.phase='ready';return true;}
function cpuChoice(s){const available=s.dice.filter(d=>!d.held),choice=best(available,s.options.ones),total=s.pot+choice.points,left=available.length-choice.ids.length;const me=s.players[s.current],lead=Math.max(...s.players.map(p=>p.total));const eligible=me.total>0||total>=s.options.opening;const mustChase=s.finalRemaining!==null&&me.total+total<=lead;const bank=eligible&&!mustChase&&(me.total+total>=s.options.goal||total>=1000||left===1&&total>=250||left===2&&total>=400||left===3&&total>=600);return {...choice,bank};}
const api={clone,score,best,create,toggle,selectedScore,keep,canBank,roll,bank,next,cpuChoice};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.FK=api;
})(typeof window!=='undefined'?window:globalThis);
