// Development-only checks; never loaded or cached by the game.
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');let baseline=true;

const TEST_ROOT=path.resolve(__dirname,'../../..');
const BASELINE_ROOT=process.env.DOUBLE_TAKE_BASELINE;
const OUTPUT=process.env.DOUBLE_TAKE_TEST_OUTPUT||path.join(TEST_ROOT,'test-results','spotdiff');
fs.mkdirSync(path.join(OUTPUT,'screens'),{recursive:true});
function out(name){return path.join(OUTPUT,name);}
assert(BASELINE_ROOT,'Set DOUBLE_TAKE_BASELINE to the unchanged 0.2.0 project root.');
const server=http.createServer((req,res)=>{let p=path.join((baseline?BASELINE_ROOT:TEST_ROOT),decodeURIComponent(req.url.split('?')[0]));if(p.endsWith('/'))p+='index.html';try{res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.html')?'text/html':p.endsWith('.css')?'text/css':p.endsWith('.webp')?'image/webp':'application/octet-stream');res.end(fs.readFileSync(p))}catch{res.statusCode=404;res.end('missing')}}).listen(8773,'127.0.0.1');
(async()=>{const opts={headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox'],viewport:{width:375,height:667}},profile=fs.mkdtempSync(out('offline-profile-'));let ctx=await chromium.launchPersistentContext(profile,opts),page=await ctx.newPage();let errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8773/');await page.evaluate(()=>navigator.serviceWorker.ready);await page.goto('http://127.0.0.1:8773/games/spotdiff/');await page.locator('#btnCloseHelp').click();let p=await page.evaluate(()=>__spotdiff.spot(0,0));await page.mouse.click(p.x,p.y);await page.evaluate(()=>dispatchEvent(new Event('pagehide')));let saved=await page.evaluate(()=>localStorage.getItem('spotdiff.game'));
await page.waitForFunction(()=>!!navigator.serviceWorker.controller);baseline=false;await page.evaluate(async()=>{const reg=await navigator.serviceWorker.getRegistration();await reg.update();});await page.locator('.updatebar.show').click();await page.waitForFunction(()=>typeof CruiseArt!=='undefined'&&CruiseArt.ready);assert.deepEqual(JSON.parse(await page.evaluate(()=>localStorage.getItem('spotdiff.game'))).found,JSON.parse(saved).found);
let cache=await page.evaluate(async()=>{let names=await caches.keys(),c=await caches.open('goobs-spotdiff-0.4.0'),files=[];for(let req of await c.keys())files.push({url:new URL(req.url).pathname,bytes:(await(await c.match(req)).arrayBuffer()).byteLength});return{names,files};});assert.equal(cache.files.length,77);assert(!cache.names.includes('goobs-spotdiff-0.2.0'));await page.evaluate(()=>{Goobs.setAds(false);__spotdiff.startLevel(2);});await page.waitForFunction(()=>__spotdiff.lv.renderer==='photo-cafe-v1'&&__spotdiff.crispReady());p=await page.evaluate(()=>__spotdiff.spot(0,0));await page.mouse.click(p.x,p.y);await page.evaluate(()=>dispatchEvent(new Event('pagehide')));saved=await page.evaluate(()=>localStorage.getItem('spotdiff.game'));await ctx.close();
ctx=await chromium.launchPersistentContext(profile,opts);await ctx.setOffline(true);page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));let responses=[];page.on('response',r=>responses.push({url:new URL(r.url()).pathname,sw:r.fromServiceWorker(),status:r.status()}));await page.goto('http://127.0.0.1:8773/games/spotdiff/');await page.waitForFunction(()=>PhotoTour.ready&&__spotdiff.crispReady());assert.equal(await page.evaluate(()=>localStorage.getItem('spotdiff.game')),saved);assert.equal(await page.evaluate(()=>__spotdiff.lv.renderer),'photo-cafe-v1');assert((await page.evaluate(()=>__spotdiff.state().found))[0]);assert(responses.filter(r=>/cruise|spotdiff/.test(r.url)).every(r=>r.sw&&r.status===200));await page.screenshot({path:out('screens/offline.png')});
p=await page.evaluate(()=>__spotdiff.spot(1,1));await page.mouse.click(p.x,p.y);assert((await page.evaluate(()=>__spotdiff.state().found))[1]);await page.locator('#btnHome').click();await page.waitForURL('http://127.0.0.1:8773/');
const backup=await page.evaluate(()=>__backup.make());assert(backup.local['spotdiff.game']);assert(backup.local['spotdiff.stats']);await page.evaluate(()=>{for(const k of Object.keys(localStorage))if(k.startsWith('spotdiff.'))localStorage.removeItem(k);});await page.locator('#fileRestore').setInputFiles({name:'pilot-test-backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.locator('#btnRestoreGo').click();await page.waitForFunction(()=>!!localStorage.getItem('spotdiff.game'));assert.equal(await page.evaluate(()=>localStorage.getItem('spotdiff.game')),backup.local['spotdiff.game']);await page.goto('http://127.0.0.1:8773/games/spotdiff/');await page.waitForFunction(()=>PhotoTour.ready&&__spotdiff.lv.renderer==='photo-cafe-v1');assert((await page.evaluate(()=>__spotdiff.state().found))[1]);assert.equal(errors.length,0);
const report={passed:true,checks:['Upgrade from 0.2.0 installs all 77 group entries and preserves in-progress save','Old Double Take cache removed; other cache groups retained','Photographic puzzle saved; browser process closed and reopened with network offline','Page, renderer and local artwork all served by service worker','Offline difference tap and return to menu work','Existing backup exported and restored, including Double Take stats, settings and progress'],cache,responses,errors};fs.writeFileSync(out('offline-verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report.checks,null,2));await ctx.close();server.close()})().catch(e=>{console.error(e);process.exit(1)});
