// Development-only photographic variant visibility and bounds checks.
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../../..');const output=process.env.DOUBLE_TAKE_TEST_OUTPUT||path.join(root,'test-results/spotdiff');fs.mkdirSync(path.join(output,'screens'),{recursive:true});const server=http.createServer((req,res)=>{let p=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(p.endsWith('/'))p+='index.html';try{res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.html')?'text/html':p.endsWith('.css')?'text/css':p.endsWith('.webp')?'image/webp':'application/octet-stream');res.end(fs.readFileSync(p))}catch{res.statusCode=404;res.end('missing')}}).listen(8780,'127.0.0.1');
(async()=>{let browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox']});let p=await browser.newPage({viewport:{width:1200,height:900},serviceWorkers:'block'});await p.goto('http://127.0.0.1:8780/games/spotdiff/');await p.waitForFunction(()=>PhotoCruise.ready&&__spotdiff.lv);await p.locator('#btnCloseHelp').click();
const result=await p.evaluate(()=>{let regions=PhotoCruise.REGIONS,zero=Object.fromEntries(regions.map(z=>[z.id,0])),c=document.createElement('canvas');c.width=355;c.height=237;let x=c.getContext('2d',{willReadFrequently:true});function render(values){x.setTransform(355/900,0,0,355/900,0,0);PhotoCruise.draw(x,{a:values,b:values,mirror:false},'a');return x.getImageData(0,0,355,237).data;}let rows=[],thumbs=[];for(const z of regions){let renders=[];for(let v=0;v<z.states;v++){renders.push(render({...zero,[z.id]:v}));let big=document.createElement('canvas');big.width=1536;big.height=1024;let bx=big.getContext('2d');bx.scale(1536/900,1536/900);PhotoCruise.draw(bx,{a:{...zero,[z.id]:v}},'a');let thumb=document.createElement('canvas');thumb.width=z.box[2];thumb.height=z.box[3];thumb.getContext('2d').drawImage(big,-z.box[0],-z.box[1]);thumbs.push({id:z.id,v,data:thumb.toDataURL()});}
for(let a=0;a<z.states;a++)for(let b=a+1;b<z.states;b++){let count=0,outside=0,s=355/1536;for(let yy=0;yy<237;yy++)for(let xx=0;xx<355;xx++){let i=(yy*355+xx)*4,delta=Math.max(...[0,1,2].map(k=>Math.abs(renders[a][i+k]-renders[b][i+k])));if(delta>=16){count++;if(xx<Math.floor(z.box[0]*s)-1||xx>Math.ceil((z.box[0]+z.box[2])*s)+1||yy<Math.floor(z.box[1]*s)-1||yy>Math.ceil((z.box[1]+z.box[3])*s)+1)outside++;}}rows.push({id:z.id,a,b,count,outside});}}
return{rows,thumbs};});
fs.writeFileSync(path.join(output,'variant-check.json'),JSON.stringify(result.rows,null,2));assert(result.rows.every(x=>x.outside===0&&x.count>100));console.log(result.rows.toSorted((a,b)=>a.count-b.count).slice(0,12));
let html='<style>body{font:14px sans-serif;margin:12px;background:#ddd}section{display:flex;gap:15px;align-items:center;margin-bottom:15px}img{width:210px;height:140px;object-fit:contain;background:#fafafa}h3{width:85px;font-size:15px}figure{margin:0}figcaption{text-align:center}</style>';
for(const id of [...new Set(result.thumbs.map(x=>x.id))])html+='<section><h3>'+id+'</h3>'+result.thumbs.filter(x=>x.id===id).map(t=>'<figure><img src="'+t.data+'"><figcaption>'+t.v+'</figcaption></figure>').join('')+'</section>';
await p.setContent(html);await p.screenshot({path:path.join(output,'screens/variants.png'),fullPage:true});await browser.close();server.close();})().catch(e=>{console.error(e);process.exit(1)});
