// Development-only checks; never loaded or cached by the game.
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');let baseline=true;

const TEST_ROOT=path.resolve(__dirname,'../../..');
const BASELINE_ROOT=process.env.DOUBLE_TAKE_BASELINE;
const OUTPUT=process.env.DOUBLE_TAKE_TEST_OUTPUT||path.join(TEST_ROOT,'test-results','spotdiff');
fs.mkdirSync(path.join(OUTPUT,'screens'),{recursive:true});
function out(name){return path.join(OUTPUT,name);}
assert(BASELINE_ROOT,'Set DOUBLE_TAKE_BASELINE to the unchanged 0.2.0 project root.');
const server=http.createServer((req,res)=>{let p=path.join((baseline?BASELINE_ROOT:TEST_ROOT),decodeURIComponent(req.url.split('?')[0]));if(p.endsWith('/'))p+='index.html';try{res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.html')?'text/html':p.endsWith('.css')?'text/css':p.endsWith('.webp')?'image/webp':'application/octet-stream');res.end(fs.readFileSync(p))}catch{res.statusCode=404;res.end('missing')}}).listen(8772,'127.0.0.1');
async function measure(page){return page.evaluate(()=>{let out=[];const w=355,h=237,s=w/900,c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d',{willReadFrequently:true});function render(sc,side){x.setTransform(s,0,0,s,0,0);x.clearRect(0,0,900,600);SceneArt.drawScene(x,sc,side);return x.getImageData(0,0,w,h).data;}
for(let d=0;d<4;d++)for(let n=1;n<=150;n++){if(DT.themeFor(n)!=='cruise')continue;const l=DT.level(n,d);for(let diff of l.diffs){let sc=JSON.parse(JSON.stringify(l.scene));sc.items.forEach(it=>{if(it.id!==diff.id)delete it.alt});let a=render(sc,'a'),b=render(sc,'b'),box=diff.box,count=0,strength=0;for(let yy=Math.max(0,Math.floor(box.y*s));yy<Math.min(h,Math.ceil((box.y+box.h)*s));yy++)for(let xx=Math.max(0,Math.floor(box.x*s));xx<Math.min(w,Math.ceil((box.x+box.w)*s));xx++){let i=(yy*w+xx)*4,m=Math.max(Math.abs(a[i]-b[i]),Math.abs(a[i+1]-b[i+1]),Math.abs(a[i+2]-b[i+2]));if(m>=16)count++;strength+=m;}out.push({n,d,k:diff.k,kind:diff.kind,count,strength});}}
return out;});}
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox']});const page=await browser.newPage({serviceWorkers:'block'});await page.goto('http://127.0.0.1:8772/games/spotdiff/');const before=await measure(page);baseline=false;await page.reload();await page.waitForFunction(()=>CruiseArt.ready);const after=await measure(page);assert.equal(after.length,before.length);const rows=after.map((a,i)=>({...a,before:before[i].count,ratio:Math.round(a.count/before[i].count*100)/100}));assert(rows.length>=400);assert(rows.every(r=>r.count>=25&&r.ratio>=.5),'A sampled difference became too faint');fs.writeFileSync(out('pixel-check.json'),JSON.stringify(rows,null,2));console.log(JSON.stringify({differences:rows.length,kinds:[...new Set(rows.map(r=>r.kind))],weakest:rows.toSorted((a,b)=>a.ratio-b.ratio).slice(0,25),invisible:rows.filter(r=>r.count<4)},null,2));await browser.close();server.close()})().catch(e=>{console.error(e);process.exit(1)});
