// Photographic tour: saved renderer contracts, bounded visible differences,
// phone taps, desktop input, restart, settings and no-scroll layouts.
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../../..'),out=process.env.DOUBLE_TAKE_TEST_OUTPUT||path.join(root,'test-results/spotdiff');fs.mkdirSync(path.join(out,'screens'),{recursive:true});
const server=http.createServer((req,res)=>{let p=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(p.endsWith('/'))p+='index.html';try{res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.html')?'text/html':p.endsWith('.css')?'text/css':p.endsWith('.webp')?'image/webp':'application/octet-stream');res.end(fs.readFileSync(p));}catch{res.statusCode=404;res.end();}}).listen(8790,'127.0.0.1');
(async()=>{
const b=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']}),p=await b.newPage({viewport:{width:375,height:667},hasTouch:true,isMobile:true,serviceWorkers:'block'});const errors=[],external=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:8790')&&!r.url().startsWith('data:'))external.push(r.url());});
await p.goto('http://127.0.0.1:8790/games/spotdiff/');await p.waitForFunction(()=>PhotoTour.ready&&__spotdiff.lv);await p.locator('#btnCloseHelp').click();
const seeds=await p.evaluate(()=>{let total=0;for(let d=0;d<4;d++)for(let n=1;n<=500;n++){let l=PhotoTour.level(n,d);if(JSON.stringify(l)!==JSON.stringify(PhotoTour.level(n,d)))throw Error('not deterministic');if(l.diffs.length!==DT.diffCount(n,d))throw Error('count');for(let z of l.diffs){if(z.box.x<0||z.box.y<0||z.box.x+z.box.w>900||z.box.y+z.box.h>600)throw Error('bounds');if(l.scene.a[z.id]===l.scene.b[z.id])throw Error('unchanged target');}total++;}return total;});
const pixels=await p.evaluate(()=>{const rows=[],images=[];for(const e of PhotoTourData){let zero=Object.fromEntries(e.regions.map(z=>[z.id,0])),c=document.createElement('canvas');c.width=355;c.height=237;let x=c.getContext('2d',{willReadFrequently:true});function render(values){x.setTransform(355/900,0,0,355/900,0,0);PhotoTour.draw(x,{renderer:e.id,a:values,mirror:false},'a');return x.getImageData(0,0,355,237).data;}let original=render(zero);for(const z of e.regions){let changed=render({...zero,[z.id]:1}),count=0,outside=0,s=355/1536;for(let y=0;y<237;y++)for(let xx=0;xx<355;xx++){let i=(y*355+xx)*4,delta=Math.max(...[0,1,2].map(k=>Math.abs(original[i+k]-changed[i+k])));if(delta>=16){count++;if(xx<Math.floor(z.box[0]*s)-1||xx>Math.ceil((z.box[0]+z.box[2])*s)+1||y<Math.floor(z.box[1]*s)-1||y>Math.ceil((z.box[1]+z.box[3])*s)+1)outside++;}}rows.push({scene:e.key,id:z.id,count,outside});}
let big=document.createElement('canvas');big.width=900;big.height=600;PhotoTour.draw(big.getContext('2d'),{renderer:e.id,a:Object.fromEntries(e.regions.map(z=>[z.id,1])),mirror:false},'a');images.push({key:e.key,data:big.toDataURL()});}return{rows,images};});
fs.writeFileSync(path.join(out,'tour-pixels.json'),JSON.stringify(pixels.rows,null,2));for(const im of pixels.images)fs.writeFileSync(path.join(out,'screens/tour-'+im.key+'-all.png'),Buffer.from(im.data.split(',')[1],'base64'));assert(pixels.rows.every(x=>x.outside===0&&x.count>60),JSON.stringify(pixels.rows.filter(x=>x.outside||x.count<=60)));
const layouts=[];for(const[w,h]of[[320,480],[375,540],[375,667],[375,812],[390,844],[414,896],[568,320],[667,375],[812,375],[896,414],[768,1024],[1024,768],[1440,900]]){await p.setViewportSize({width:w,height:h});await p.waitForTimeout(180);let r=await p.evaluate(()=>({scroll:[document.documentElement.scrollWidth,document.documentElement.scrollHeight],a:document.querySelector('#picA').getBoundingClientRect().toJSON(),b:document.querySelector('#picB').getBoundingClientRect().toJSON(),top:document.querySelector('.top').getBoundingClientRect().bottom,bottom:document.querySelector('.toolbar').getBoundingClientRect().top}));assert.deepEqual(r.scroll,[w,h]);for(const pic of[r.a,r.b])assert(pic.x>=0&&pic.right<=w+.1&&pic.y>=r.top-.1&&pic.bottom<=r.bottom+.1);layouts.push([w,h]);}
await p.setViewportSize({width:375,height:667});const scenes=[];for(let n=1;n<=6;n++){await p.evaluate(n=>__spotdiff.startLevel(n),n);await p.waitForTimeout(200);const renderer=await p.evaluate(()=>__spotdiff.lv.renderer);await p.screenshot({path:path.join(out,'screens/spotdiff-'+n+'-phone.png')});let point=await p.evaluate(()=>__spotdiff.spot(0,0));await p.touchscreen.tap(point.x,point.y);assert(await p.evaluate(()=>__spotdiff.state().found[0]));await p.evaluate(()=>dispatchEvent(new Event('pagehide')));const before=await p.evaluate(()=>({scene:__spotdiff.lv.scene,state:__spotdiff.state(),stats:__spotdiff.stats()}));await p.reload();await p.waitForFunction(()=>PhotoTour.ready&&__spotdiff.lv);assert.deepEqual(await p.evaluate(()=>__spotdiff.lv.scene),before.scene);assert.deepEqual(await p.evaluate(()=>__spotdiff.state().found),before.state.found);assert.deepEqual(await p.evaluate(()=>__spotdiff.stats()),before.stats);scenes.push({n,renderer,saved:true});}
// A cruise puzzle at a level now assigned to another place must resume as cruise.
await p.evaluate(()=>__spotdiff.startLevel(2));
const fixture=await p.evaluate(()=>{let l=PhotoCruise.level(2,__spotdiff.settings().diff);return {level:2,renderer:l.renderer,sig:PhotoCruise.signature(l),found:[0],wrong:1,hints:1,secs:21};});
await p.addInitScript(f=>{if(!sessionStorage.getItem('cruise-fixture-done')){localStorage.setItem('spotdiff.game',JSON.stringify(f));sessionStorage.setItem('cruise-fixture-done','1');}},fixture);
await p.reload();await p.waitForFunction(()=>PhotoTour.ready&&__spotdiff.lv);assert.equal(await p.evaluate(()=>__spotdiff.lv.renderer),'photo-cruise-v1');assert.equal(await p.evaluate(()=>__spotdiff.state().hints),1);
await p.evaluate(()=>__spotdiff.startLevel(4));await p.setViewportSize({width:1440,height:900});await p.waitForTimeout(200);let point=await p.evaluate(()=>__spotdiff.spot(1,1));await p.mouse.click(point.x,point.y);assert(await p.evaluate(()=>__spotdiff.state().found[1]));await p.mouse.move(point.x,point.y);await p.mouse.wheel(0,-400);await p.waitForTimeout(300);assert(await p.evaluate(()=>__spotdiff.view.z>1));
await p.locator('#ggMenuBtn').click();await p.locator('#btnSettings').click();await p.locator('#setScenes button[data-photo="0"]').click();await p.locator('#btnCloseSettings').click();await p.evaluate(()=>__spotdiff.startLevel(3));assert.equal(await p.evaluate(()=>!!__spotdiff.lv.renderer),false);
assert.deepEqual(errors,[]);assert.deepEqual(external,[]);fs.writeFileSync(path.join(out,'tour-check.json'),JSON.stringify({seeds,variants:pixels.rows.length,layouts,scenes,cruiseSave:true,desktopMouseZoom:true,originalMode:true,errors,external},null,2));await b.close();server.close();console.log('PASS tour: '+seeds+' seeds, '+pixels.rows.length+' visible bounded changes, 13 layouts, six saved scenes, old cruise save, touch/mouse, settings');
})().catch(e=>{console.error(e);process.exit(1)});
