/* Fortress Feud 1.0.0 */
(function(){'use strict';
const E=FeudEngine,$=id=>document.getElementById(id),store=Goobs.store('castle'),VERSION='1.0.1';
let profile=store.get('feudProfile',{level:1,wins:0}),cells=store.get('feudBuild',E.design()),team=store.get('feudCrew',['gunner','bomber','ranger','engineer']),material='stone',battle=null,selected=null,view=0,paused=false,aiDelay=0,acc=0,last=0,resultShown=false,sound=store.get('feudSound',false),audio=null,toastTimer=0;
const backgrounds=['meadow','valley','coast'].map(n=>{const i=new Image();i.src='assets/sling-'+n+'-v1.webp';return i;});
const portraits=(id)=>`<i class="portrait" style="--color:${E.crew.find(c=>c.id===id).color}"></i>`;
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2200);}
function beep(type){if(!sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type==='impact'?'triangle':'sine';o.frequency.setValueAtTime(type==='impact'?100:250,audio.currentTime);o.frequency.exponentialRampToValueAtTime(35,audio.currentTime+.18);g.gain.setValueAtTime(.12,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.25);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.25);}catch{}}
function modal(title,body,actions){paused=true;$('close').hidden=battle?.stage==='over';$('dialogTitle').textContent=title;$('dialogBody').innerHTML=body;$('dialogActions').replaceChildren();for(const [label,fn,gold]of actions){const b=document.createElement('button');b.textContent=label;if(gold)b.className='gold';b.onclick=()=>{close();fn();};$('dialogActions').append(b);}if(!$('dialog').open)$('dialog').showModal();}
function close(){$('dialog').close();paused=false;last=performance.now();}
$('close').onclick=close;$('dialog').addEventListener('cancel',e=>{if(battle?.stage==='over')e.preventDefault();else paused=false;});
function help(){modal('How to play',`<p><b>Build your defenses.</b> Tap the castle grid to add or replace blocks. Wood is cheap, stone is sturdy, and iron is toughest. Select Erase to remove a top block. The golden keep stays at the center; it is your main target to protect.</p><p><b>Draft four fighters.</b> Tap a selected fighter to make room for another. Each brings a different shot. An Engineer repairs 16 keep health whenever they fire.</p><p><b>Take turns firing.</b> Pick a living fighter, adjust angle and power, then Fire. The first three battles show a full practice trajectory. Later, the dotted line shows only the start of your shot. A high angle can clear a wall; lower angles hit its face. Friendly blocks can stop your own shots, too.</p><p><b>Win</b> by destroying the rival keep or defeating all four fighters. Falling walls can bring fighters down. Your rival shoots back after the rubble settles. The first three battles are gentler; later fortresses gain stone, iron, and more accurate defenders.</p><p>Use View to inspect either castle. Progress and each completed turn save automatically. Leaving during a shot resumes at the start of that shot. There are no timers or limited lives.</p><p class="version">Fortress Feud ${VERSION} · Castle Havoc 3.0.1</p>`,[['Back',()=>{},true]]);}
$('setupHelp').onclick=help;
$('menu').onclick=()=>modal('Take a breather',`<p>${battle?'Battle '+battle.level+' · Round '+battle.round:'Your fortress is waiting.'}</p>`,[['Continue',()=>{},true],['How to play',help],['Sound: '+(sound?'On':'Off'),()=>{sound=!sound;store.set('feudSound',sound);$('menu').click();}],...(battle?[['Rebuild & retry',()=>modal('Rebuild this fortress?','<p>This replaces the saved battle. Your campaign progress stays.</p>',[['Keep playing',()=>{},true],['Rebuild',()=>{store.del('feudBattle');battle=null;showSetup();}]])]]:[])]);
function saveBuild(){store.set('feudBuild',cells);store.set('feudCrew',team);}
function showSetup(){battle=null;$('setup').hidden=false;$('setupActions').hidden=false;$('battle').hidden=true;$('campaign').textContent='CAMPAIGN · BATTLE '+profile.level;$('resume').hidden=!store.get('feudBattle',null);renderDraft();renderBuilder();}
function renderDraft(){$('crewCount').textContent=team.length+' / 4';$('draftCards').innerHTML=E.crew.map(c=>`<button class="draft-card ${team.includes(c.id)?'selected':''}" data-role="${c.id}" aria-pressed="${team.includes(c.id)}">${portraits(c.id)}<b>${c.name} ${team.includes(c.id)?'✓':''}</b><small>${c.hint}</small></button>`).join('');$('draftCards').querySelectorAll('button').forEach(b=>b.onclick=()=>{const id=b.dataset.role;if(team.includes(id))team=team.filter(x=>x!==id);else if(team.length<4)team.push(id);else{$('crewCount').textContent='Remove one to swap';return;}saveBuild();renderDraft();});$('begin').disabled=team.length!==4||!E.valid(cells)||E.cost(cells)>160;$('startHint').textContent=team.length!==4?'Choose '+(4-team.length)+' more fighter'+(team.length===3?'':'s')+' to start.':E.cost(cells)>160?'Reduce your castle cost to 160 coins.':!E.valid(cells)?'Support every block from below.':'Ready to play. Customizing is optional.';}
for(const [id,m]of Object.entries({...E.materials,erase:{cost:0}})){const b=document.createElement('button');b.textContent=id==='erase'?'Erase':id[0].toUpperCase()+id.slice(1)+' · '+m.cost;b.dataset.mat=id;b.onclick=()=>{material=id;renderBuilder();};$('materials').append(b);}
function fit(canvas){const r=canvas.getBoundingClientRect(),d=Math.min(2,window.devicePixelRatio||1);if(canvas.width!==Math.round(r.width*d)||canvas.height!==Math.round(r.height*d)){canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);}const ctx=canvas.getContext('2d');ctx.setTransform(d,0,0,d,0,0);return{ctx,w:r.width,h:r.height};}
function renderBuilder(){if($('setup').hidden)return;const{ctx:c,w,h}=fit($('blueprint')),size=Math.min((w-36)/9,(h-26)/6),left=(w-size*9)/2,bottom=h-16;c.clearRect(0,0,w,h);c.fillStyle='#162f32';c.fillRect(0,0,w,h);for(let x=0;x<9;x++)for(let y=0;y<6;y++){c.strokeStyle='#65868238';c.strokeRect(left+x*size+1,bottom-(y+1)*size+1,size-2,size-2);}for(const cell of cells){if(cell.x===4&&cell.y<2)continue;drawBlock(c,left+cell.x*size+1,bottom-(cell.y+1)*size+1,size-2,size-2,cell.mat,1,cell.x+cell.y);}c.fillStyle='#ddb666';c.fillRect(left+4*size,bottom-2*size,size,2*size);c.fillStyle='#513e2d';c.font=`bold ${Math.max(8,size*.3)}px system-ui`;c.textAlign='center';c.fillText('KEEP',left+4.5*size,bottom-size*.85);c.fillStyle='#ac956b';c.fillRect(left-4,bottom,9*size+8,5);$('budget').textContent=E.cost(cells)+' / 160 coins';$('materials').querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b.dataset.mat===material));renderDraft();}
let buildTouch=null;
$('blueprint').addEventListener('pointerdown',e=>{buildTouch={id:e.pointerId,x:e.clientX,y:e.clientY};});
$('blueprint').addEventListener('pointercancel',()=>{buildTouch=null;});
$('blueprint').addEventListener('pointermove',e=>{if(buildTouch&&Math.hypot(e.clientX-buildTouch.x,e.clientY-buildTouch.y)>10)buildTouch=null;});
$('blueprint').addEventListener('pointerup',e=>{const tap=buildTouch;buildTouch=null;if(!tap||tap.id!==e.pointerId||Math.hypot(e.clientX-tap.x,e.clientY-tap.y)>10)return;const r=$('blueprint').getBoundingClientRect(),size=Math.min((r.width-36)/9,(r.height-26)/6),x=Math.floor((e.clientX-r.left-(r.width-size*9)/2)/size),y=Math.floor((r.height-16-(e.clientY-r.top))/size);if(x<0||x>8||y<0||y>5||x===4&&y<2)return;const old=cells.find(c=>c.x===x&&c.y===y);let next=cells.filter(c=>c!==old);if(material!=='erase')next.push({x,y,mat:material});if(!E.valid(next)){$('buildTip').textContent='Support each block from below. Remove top blocks first.';return;}if(E.cost(next)>160){$('buildTip').textContent='Over budget. Try wood, or remove another block.';return;}cells=next;saveBuild();$('buildTip').textContent='Tap squares to reinforce. Build from the ground up.';renderBuilder();});
$('template').onchange=()=>{cells=E.design(+$('template').value);saveBuild();renderBuilder();};$('resetBuild').onclick=()=>{$('template').onchange();};
function launch(saved){if(saved?.roster)team=saved.roster.slice();battle=new E.Battle(saved?saved.level:profile.level,cells,team,saved);resultShown=false;$('setup').hidden=true;$('setupActions').hidden=true;$('battle').hidden=false;view=innerWidth<600?2:0;updateViewLabel();selected=battle.living(0,'crew')[0]?.id;aiDelay=0;acc=0;sync();saveTurn();if(battle.winner!==null)showResult();}
$('begin').onclick=()=>{if(store.get('feudBattle',null))modal('Start a fresh battle?','<p>Your unfinished battle will be replaced.</p>',[['Resume saved battle',()=>launch(store.get('feudBattle',null)),true],['Start fresh',()=>launch()]]);else launch();};$('resume').onclick=()=>launch(store.get('feudBattle',null));
function saveTurn(){if(battle&&battle.stage!=='flight')store.set('feudBattle',battle.snapshot());}
function sync(){if(!battle)return;for(let side=0;side<2;side++){$('hp'+side).textContent=battle.health(side);$('meter'+side).value=battle.health(side);$('meter'+side).max=battle.keep(side)?.maxHp||180;}$('turnText').textContent=battle.stage==='over'?'Battle complete':battle.stage==='flight'?'Watch the shot…':battle.turn?'Rival is aiming…':'Your turn · Round '+battle.round;$('battleLabel').textContent='BATTLE '+battle.level;const living=battle.living(0,'crew');if(!living.some(o=>o.id===selected))selected=living[0]?.id;$('fighters').innerHTML=team.map(id=>{const unit=living.find(o=>o.role===id),role=E.crew.find(c=>c.id===id);return`<button data-id="${unit?.id||0}" ${!unit?'disabled':''} class="${unit?.id===selected?'selected':''}" aria-pressed="${unit?.id===selected}">${portraits(id)}${role.name}<small>${unit?Math.ceil(unit.hp)+' HP':'Defeated'}</small></button>`;}).join('');$('fighters').querySelectorAll('button').forEach(b=>b.onclick=()=>{selected=+b.dataset.id;sync();});const unit=living.find(o=>o.id===selected),role=E.crew.find(c=>c.id===unit?.role);$('fire').textContent='Fire '+(role?.weapon.toLowerCase()||'shot');const disabled=battle.turn!==0||battle.stage!=='aim';$('fire').disabled=disabled;$('angle').disabled=disabled;$('power').disabled=disabled;$('shotHint').textContent=role?role.hint+' · '+(battle.level<=3?'Aim high to clear your walls.':'Friendly walls can block your shot.'):'No fighters left';}
for(const id of ['angle','power'])$(id).oninput=()=>{$(id+'Out').value=$(id).value+(id==='angle'?'°':'%');};
$('fire').onclick=()=>{if(battle?.fire(selected,+$('angle').value,+$('power').value)){saveBuild();view=0;updateViewLabel();sync();}};
function updateViewLabel(){$('view').textContent='View: '+['Both castles','Your castle','Rival castle'][view];}
$('view').onclick=()=>{view=(view+1)%3;updateViewLabel();};
function showResult(){if(resultShown)return;resultShown=true;const won=battle.winner===0,draw=battle.winner===2;if(won){profile.level=Math.max(profile.level,battle.level+1);profile.wins++;store.set('feudProfile',profile);}store.del('feudBattle');modal(won?'Victory!':draw?'Mutual destruction':'Your fortress fell',`<div class="result">${won?'⚑':'♜'}</div><p>${won?'The rival fortress is defeated. Your crew is ready for the next challenge.':draw?'Both fortresses fell in the same exchange. Rebuild and try again.':'Reinforce the keep, change your crew, or try a higher arc.'}</p><p>Battle ${battle.level} · ${battle.round} rounds</p>`,[[won?'Build for battle '+profile.level:'Rebuild & retry',showSetup,true]]);}
function drawBlock(c,x,y,w,h,mat,health,seed){const m=E.materials[mat];c.fillStyle=m.color;c.fillRect(x,y,w,h);const g=c.createLinearGradient(x,y,x+w,y+h);g.addColorStop(0,'#ffffff24');g.addColorStop(.5,'#00000000');g.addColorStop(1,'#00000025');c.fillStyle=g;c.fillRect(x,y,w,h);c.strokeStyle=mat==='iron'?'#d4e7e166':'#342e2855';c.lineWidth=Math.max(.6,w*.035);c.strokeRect(x+.5,y+.5,w-1,h-1);c.strokeStyle='#ffffff35';c.beginPath();c.moveTo(x+2,y+2);c.lineTo(x+w-2,y+2);c.stroke();if(mat==='wood'){c.strokeStyle='#58371855';c.lineWidth=.6;for(let i=1;i<4;i++){c.beginPath();c.moveTo(x+2,y+h*i/4);c.bezierCurveTo(x+w*.3,y+h*i/4-2,x+w*.6,y+h*i/4+2,x+w-2,y+h*i/4);c.stroke();}}else if(mat==='iron'){c.fillStyle='#dee4d699';for(const px of [.18,.82])for(const py of [.18,.82]){c.beginPath();c.arc(x+w*px,y+h*py,Math.max(.7,w*.05),0,7);c.fill();}}else{c.strokeStyle='#6b6c633a';c.lineWidth=.65;c.beginPath();c.moveTo(x+w*.15,y+h*.7);c.lineTo(x+w*.4,y+h*.55);c.lineTo(x+w*.8,y+h*.62);c.stroke();}if(health<.65){c.strokeStyle='#273635';c.lineWidth=1;c.beginPath();c.moveTo(x+w*.5,y);c.lineTo(x+w*.32,y+h*.4);c.lineTo(x+w*.62,y+h*.6);c.lineTo(x+w*.35,y+h);c.stroke();}}
function render(){if(!battle)return;const{ctx:c,w,h}=fit($('field'));c.clearRect(0,0,w,h);const bg=backgrounds[Math.floor((battle.level-1)/5)%3];if(bg.complete&&bg.naturalWidth){const scale=Math.max(w/bg.width,h/bg.height);c.drawImage(bg,(w-bg.width*scale)/2,(h-bg.height*scale)/2,bg.width*scale,bg.height*scale);}else{const g=c.createLinearGradient(0,0,0,h);g.addColorStop(0,'#8ebbb9');g.addColorStop(1,'#d5d4a9');c.fillStyle=g;c.fillRect(0,0,w,h);}
 const shot=battle.shot&&!battle.shot.dead?battle.shot.body.getPosition():null;const extent=shot?Math.max(12,shot.y+3):12,scale=Math.min(w/(view?13:34),(h-48)/extent),cx=view===1?-10:view===2?10:0,base=h-28;const sx=x=>w/2+(x-cx)*scale,sy=y=>base-y*scale;
 c.fillStyle='#596d4b';c.fillRect(0,base,w,h-base);c.fillStyle='#d4c199';c.fillRect(0,base,w,4);c.fillStyle='#746a52';c.fillRect(0,base+4,w,3);for(let side=0;side<2;side++){const x=sx(side?10:-10);c.fillStyle=side?'#9b5150':'#376d76';c.fillRect(x-4.8*scale,base,9.6*scale,5);c.fillStyle='#f8edce';c.font='bold 9px system-ui';c.textAlign='center';c.fillText(side?'RIVAL':'YOUR FORTRESS',x,h-9);}
 for(const o of battle.objects){if(o.dead)continue;const p=o.body.getPosition(),x=sx(p.x),y=sy(p.y);c.save();c.translate(x,y);c.rotate(-o.body.getAngle());if(o.kind==='block')drawBlock(c,-o.w*scale/2,-o.h*scale/2,o.w*scale,o.h*scale,o.mat,o.hp/o.maxHp,o.id);else if(o.kind==='keep'){const ww=o.w*scale,hh=o.h*scale;c.fillStyle=o.side?'#b35e54':'#3f7d83';c.fillRect(-ww/2,-hh/2,ww,hh);c.fillStyle='#dcc68f';c.fillRect(-ww/2,-hh/2,ww,3);for(let i=0;i<3;i++)c.fillRect(-ww/2+i*ww/2.6,-hh/2-ww*.13,ww*.23,ww*.2);c.fillStyle='#173639';c.beginPath();c.roundRect(-ww*.19,-hh*.05,ww*.38,hh*.55,[ww*.2,ww*.2,0,0]);c.fill();c.fillStyle='#f3d079';c.font=`bold ${Math.max(8,scale*.45)}px serif`;c.textAlign='center';c.fillText('♛',0,-hh*.14);c.fillStyle='#243937';c.fillRect(-ww/2,hh/2+2,ww,2);c.fillStyle='#f3d079';c.fillRect(-ww/2,hh/2+2,ww*o.hp/o.maxHp,2);}else if(o.kind==='crew'){const r=E.crew.find(c=>c.id===o.role),s=scale;c.fillStyle='#213a36';c.fillRect(-s*.22,s*.1,s*.16,s*.35);c.fillRect(s*.06,s*.1,s*.16,s*.35);c.fillStyle=r.color;c.fillRect(-s*.28,-s*.17,s*.56,s*.43);c.fillStyle='#ebc998';c.beginPath();c.arc(0,-s*.3,s*.24,0,7);c.fill();c.fillStyle='#8d9f99';c.fillRect(-s*.29,-s*.52,s*.58,s*.17);c.fillStyle=o.side?'#b75248':'#377e94';c.fillRect(-s*.06,-s*.65,s*.12,s*.19);c.fillStyle='#253a38';c.fillRect((o.side?-.17:.09)*s,-s*.34,s*.06,s*.06);c.strokeStyle='#485c58';c.lineWidth=s*.18;c.beginPath();c.moveTo(0,-s*.02);c.lineTo((o.side?-1:1)*s*.48,-s*.17);c.stroke();if(o.id===selected&&battle.turn===0){c.strokeStyle='#ffe2a0';c.lineWidth=1.5;c.beginPath();c.ellipse(0,s*.46,s*.42,s*.14,0,0,7);c.stroke();}c.fillStyle='#223e39';c.fillRect(-s*.32,-s*.95,s*.64,2);c.fillStyle=o.side?'#e69779':'#dbe197';c.fillRect(-s*.32,-s*.95,s*.64*o.hp/o.maxHp,2);}else if(o.kind==='shot'){c.shadowColor='#f6d39c';c.shadowBlur=10;c.fillStyle=o.role==='alchemist'?'#f3a567':'#394e51';c.beginPath();c.arc(0,0,o.radius*scale,0,7);c.fill();c.fillStyle='#ffffde';c.beginPath();c.arc(-o.radius*scale*.3,-o.radius*scale*.3,o.radius*scale*.25,0,7);c.fill();}c.restore();}
 if(battle.turn===0&&battle.stage==='aim'){const u=battle.objects.find(o=>o.id===selected&&!o.dead);if(u){const p=battle.origin(u),v=battle.velocity(0,+$('angle').value,+$('power').value);c.fillStyle='#fff4bb';for(let t=.08;t<(battle.level<=3?4:.8);t+=.09){if(p.y+v.y*t-5*t*t<0)break;c.globalAlpha=battle.level<=3?.65:1-t;c.beginPath();c.arc(sx(p.x+v.x*t),sy(p.y+v.y*t-5*t*t),2,0,7);c.fill();}c.globalAlpha=1;}}
 for(const e of battle.effects){c.globalAlpha=Math.max(0,e.life);c.fillStyle=e.color;c.beginPath();c.arc(sx(e.x),sy(e.y),e.r*scale*(1.2-e.life*.6),0,7);c.fill();c.globalAlpha=1;}
}
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000||0);last=now;if(!battle||paused||document.hidden)return;acc+=dt;while(acc>=1/60){acc-=1/60;battle.step(1/60);}if(battle.stage==='aim'&&battle.turn===1){aiDelay+=dt;if(aiDelay>1.3){const a=battle.aimAI();if(a)battle.fire(a.id,a.angle,a.power);aiDelay=0;sync();}}for(const e of battle.events.splice(0)){if(e.type==='turn'){if(innerWidth<600&&battle.turn===0){view=2;updateViewLabel();}sync();saveTurn();if(battle.winner!==null)showResult();else toast(battle.turn?'Rival’s turn':'Your turn');}else beep(e.type);}render();}
window.addEventListener('resize',()=>{renderBuilder();render();});document.addEventListener('visibilitychange',()=>{last=performance.now();acc=0;});window.addEventListener('pagehide',saveBuild);Goobs.markPlayed('castle');Goobs.initUpdates();showSetup();requestAnimationFrame(frame);
window.FortressFeud={get battle(){return battle;},launch,showSetup,version:VERSION};
})();
