/* Fortress Feud 1.1.0 */
(function(){'use strict';
const E=FeudEngine,$=id=>document.getElementById(id),store=Goobs.store('castle'),VERSION='1.3.0';
let profile=store.get('feudProfile',{level:1,wins:0}),cells=[],team=[],target={x:10,y:1},arc='high',aimAngle=60,aimPower=25,camera=null,aimDrag=null,battle=null,selected=null,view=0,paused=false,aiDelay=0,acc=0,last=0,resultShown=false,sound=store.get('feudSound',false),audio=null,toastTimer=0;
const backgrounds=['meadow','valley','coast'].map(n=>{const i=new Image();i.src='assets/sling-'+n+'-v1.webp';return i;});
const portraits=(id)=>`<i class="portrait" style="--color:${E.crew.find(c=>c.id===id).color}"></i>`;
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2200);}
function beep(type){if(!sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type==='impact'?'triangle':'sine';o.frequency.setValueAtTime(type==='impact'?100:250,audio.currentTime);o.frequency.exponentialRampToValueAtTime(35,audio.currentTime+.18);g.gain.setValueAtTime(.12,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.25);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.25);}catch{}}
function modal(title,body,actions){paused=true;$('close').hidden=battle?.stage==='over';$('dialogTitle').textContent=title;$('dialogBody').innerHTML=body;$('dialogActions').replaceChildren();for(const [label,fn,gold]of actions){const b=document.createElement('button');b.textContent=label;if(gold)b.className='gold';b.onclick=()=>{close();fn();};$('dialogActions').append(b);}if(!$('dialog').open)GoobsDialog.open($('dialog'));}
function close(){GoobsDialog.close($('dialog'));paused=false;last=performance.now();}
$('close').onclick=close;$('dialog').addEventListener('cancel',e=>{if(battle?.stage==='over')e.preventDefault();else paused=false;});
function help(){modal('How to play',`<p><b>Your castles are ready.</b> Every battle starts with prebuilt fortresses and a ready-made crew. There is no building, budget, or drafting step.</p><p><b>1. Pick a fighter.</b> Tap one of your four crew buttons. Each survivor brings a different weapon. The Engineer repairs 16 keep health before firing.</p><p><b>2. Aim at the rival castle.</b> Tap a wall, a fighter, or the keep. Drag to adjust the target. The dotted line shows your shot up to its first obstacle. Use <b>High shot</b> to lob over defenses, or <b>Low shot</b> to attack a wall directly. Your own walls can block a shot too.</p><p><b>3. Fire.</b> Watch the impact and collapse, then the computer fires back. Target supporting blocks to bring towers and defenders down.</p><p><b>Win</b> by destroying the rival keep or defeating all its fighters. The first three battles are gentler; later castles have tougher walls and more accurate rivals.</p><p>View switches between the whole battlefield and close-ups. On a keyboard, focus the battlefield and use arrow keys to move the target, Enter to fire. Completed turns save automatically; leaving mid-shot resumes at the start of that shot.</p><p class="version">Fortress Feud ${VERSION} · Castle Havoc 3.3.0</p>`,[['Back',()=>{},true]]);}
$('menu').onclick=()=>modal('Take a breather',`<p>Battle ${battle.level} · Round ${battle.round}</p>`,[['Continue',()=>{},true],['How to play',help],['Sound: '+(sound?'On':'Off'),()=>{sound=!sound;store.set('feudSound',sound);$('menu').click();}],['Restart battle',()=>modal('Restart this battle?','<p>Both prebuilt castles will be restored. Your campaign progress stays.</p>',[['Keep playing',()=>{},true],['Restart',()=>launch(null,battle.level)]])]]);
function prebuilt(n){const plan=E.design((n-1)%3);for(const c of plan)if(n>7&&(c.x===4||(c.x+c.y+n)%5===0))c.mat='iron';return plan;}
function readyCrew(n){return n<4?['gunner','bomber','ranger','engineer']:n%3===1?['gunner','bomber','mortar','engineer']:n%3===2?['gunner','ranger','alchemist','mortar']:['gunner','bomber','alchemist','engineer'];}
function fit(canvas){const r=canvas.getBoundingClientRect(),d=Math.min(2,window.devicePixelRatio||1);if(canvas.width!==Math.round(r.width*d)||canvas.height!==Math.round(r.height*d)){canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);}const ctx=canvas.getContext('2d');ctx.setTransform(d,0,0,d,0,0);return{ctx,w:r.width,h:r.height};}
function launch(saved,n=profile.level){n=saved?.level||n;cells=prebuilt(n);team=saved?.roster?.slice()||readyCrew(n);battle=new E.Battle(n,cells,team,saved);FeudArt.prepare(battle,saved?.architecture);resultShown=false;view=innerWidth<600?2:0;updateViewLabel();selected=battle.living(0,'crew')[0]?.id;target=saved?.aimTarget||{x:10,y:1};arc=saved?.aimArc==='low'?'low':'high';aiDelay=0;acc=0;sync();saveTurn();if(battle.winner!==null)showResult();}
function setAim(){const u=battle?.living(0,'crew').find(o=>o.id===selected);if(!u)return;const p=battle.origin(u),dx=target.x-p.x,dy=target.y-p.y;if(dx<=0)return;let best=null;const preferred=arc==='high'?67:30;for(let a=12;a<=80;a++){const rad=a*Math.PI/180,den=2*Math.cos(rad)**2*(dx*Math.tan(rad)-dy);if(den<=0)continue;const speed=Math.sqrt(10*dx*dx/den),power=(speed-10)/.24;if(power<5||power>100)continue;const score=Math.abs(a-preferred);if(!best||score<best.score)best={angle:a,power,score};}if(best){aimAngle=best.angle;aimPower=best.power;}$('arc').textContent=arc==='high'?'High shot ⤴':'Low shot →';}
function aimAt(e){if(!camera||paused||battle.turn!==0||battle.stage!=='aim')return;const r=$('field').getBoundingClientRect(),x=camera.cx+(e.clientX-r.left-camera.w/2)/camera.scale,y=(camera.base-(e.clientY-r.top))/camera.scale;if(x<3){toast('Tap the rival castle to choose your target.');return;}target={x:Math.max(3,Math.min(24,x)),y:Math.max(.3,Math.min(14,y))};setAim();saveTurn();}
$('field').addEventListener('pointerdown',e=>{if(e.button>0)return;aimDrag=e.pointerId;$('field').setPointerCapture(e.pointerId);aimAt(e);});
$('field').addEventListener('pointermove',e=>{if(aimDrag===e.pointerId)aimAt(e);});
$('field').addEventListener('pointerup',()=>{aimDrag=null;});$('field').addEventListener('pointercancel',()=>{aimDrag=null;});
$('field').addEventListener('keydown',e=>{if(paused||battle.turn!==0||battle.stage!=='aim')return;if(e.key==='Enter'||e.key===' '){e.preventDefault();$('fire').click();return;}const d={ArrowLeft:[-.3,0],ArrowRight:[.3,0],ArrowUp:[0,.3],ArrowDown:[0,-.3]}[e.key];if(d){e.preventDefault();target={x:Math.max(3,Math.min(24,target.x+d[0])),y:Math.max(.3,Math.min(14,target.y+d[1]))};setAim();saveTurn();}});
$('arc').onclick=()=>{arc=arc==='high'?'low':'high';setAim();saveTurn();};
function saveTurn(){if(battle&&battle.stage!=='flight')store.set('feudBattle',{...battle.snapshot(),aimTarget:target,aimArc:arc,architecture:FeudArt.snapshot()});}
function sync(){if(!battle)return;for(let side=0;side<2;side++){$('hp'+side).textContent=battle.health(side);$('meter'+side).value=battle.health(side);$('meter'+side).max=battle.keep(side)?.maxHp||180;}$('turnText').textContent=battle.stage==='over'?'Battle complete':battle.stage==='flight'?'Watch the shot…':battle.turn?'Rival is aiming…':'Your turn · Round '+battle.round;$('battleLabel').textContent='BATTLE '+battle.level;const living=battle.living(0,'crew');if(!living.some(o=>o.id===selected))selected=living[0]?.id;$('fighters').innerHTML=team.map(id=>{const unit=living.find(o=>o.role===id),role=E.crew.find(c=>c.id===id);return`<button data-id="${unit?.id||0}" ${!unit?'disabled':''} class="${unit?.id===selected?'selected':''}" aria-pressed="${unit?.id===selected}">${portraits(id)}${role.name}<small>${unit?Math.ceil(unit.hp)+' HP':'Defeated'}</small></button>`;}).join('');$('fighters').querySelectorAll('button').forEach(b=>b.onclick=()=>{selected=+b.dataset.id;sync();});const unit=living.find(o=>o.id===selected),role=E.crew.find(c=>c.id===unit?.role);$('fire').textContent='Fire '+(role?.weapon.toLowerCase()||'shot');const disabled=battle.turn!==0||battle.stage!=='aim';$('fire').disabled=disabled;$('arc').disabled=disabled;setAim();$('shotHint').textContent=role?role.hint+' · Tap or drag on the rival castle to aim.':'No fighters left';}
$('fire').onclick=()=>{if(battle?.fire(selected,aimAngle,aimPower)){view=0;updateViewLabel();sync();}};
function updateViewLabel(){$('view').textContent='View: '+['Both castles','Your castle','Rival castle'][view];}
$('view').onclick=()=>{view=(view+1)%3;updateViewLabel();};
function showResult(){if(resultShown)return;resultShown=true;const won=battle.winner===0,draw=battle.winner===2;if(won){profile.level=Math.max(profile.level,battle.level+1);profile.wins++;store.set('feudProfile',profile);}store.del('feudBattle');modal(won?'Victory!':draw?'Mutual destruction':'Your fortress fell',`<div class="result">${won?'⚑':'♜'}</div><p>${won?'The rival fortress is defeated. Your crew is ready for the next challenge.':draw?'Both fortresses fell in the same exchange. Try a different target and fire again.':'Try hitting the tower supports, or switch fighters and shot arc.'}</p><p>Battle ${battle.level} · ${battle.round} rounds</p>`,[[won?'Next battle →':'Try again',()=>launch(null,won?profile.level:battle.level),true]]);}
function render(){if(!battle)return;const{ctx:c,w,h}=fit($('field'));c.clearRect(0,0,w,h);const bg=backgrounds[Math.floor((battle.level-1)/5)%3];if(bg.complete&&bg.naturalWidth){const scale=Math.max(w/bg.width,h/bg.height);c.drawImage(bg,(w-bg.width*scale)/2,(h-bg.height*scale)/2,bg.width*scale,bg.height*scale);}else{const g=c.createLinearGradient(0,0,0,h);g.addColorStop(0,'#8ebbb9');g.addColorStop(1,'#d5d4a9');c.fillStyle=g;c.fillRect(0,0,w,h);}
 const shot=battle.shot&&!battle.shot.dead?battle.shot.body.getPosition():null;const extent=shot?Math.max(12,shot.y+3):12,scale=Math.min(w/(view?13:34),(h-48)/extent),cx=view===1?-10:view===2?10:0,base=h-28;camera={w,scale,cx,base};const sx=x=>w/2+(x-cx)*scale,sy=y=>base-y*scale;
 c.fillStyle='#596d4b';c.fillRect(0,base,w,h-base);c.fillStyle='#d4c199';c.fillRect(0,base,w,4);c.fillStyle='#746a52';c.fillRect(0,base+4,w,3);for(let side=0;side<2;side++){const x=sx(side?10:-10);c.fillStyle=side?'#9b5150':'#376d76';c.fillRect(x-4.8*scale,base,9.6*scale,5);c.fillStyle='#f8edce';c.font='bold 9px system-ui';c.textAlign='center';c.fillText(side?'RIVAL':'YOUR FORTRESS',x,h-9);}
 FeudArt.foundation(c,sx,base,scale);
 for(const o of battle.objects){if(o.dead)continue;const p=o.body.getPosition(),x=sx(p.x),y=sy(p.y);c.save();c.translate(x,y);c.rotate(-o.body.getAngle());if(o.kind==='block')FeudArt.block(c,o,scale);else if(o.kind==='keep')FeudArt.keep(c,o,scale);else if(o.kind==='crew'){const r=E.crew.find(c=>c.id===o.role),s=scale;c.fillStyle='#213a36';c.fillRect(-s*.22,s*.1,s*.16,s*.35);c.fillRect(s*.06,s*.1,s*.16,s*.35);c.fillStyle=r.color;c.fillRect(-s*.28,-s*.17,s*.56,s*.43);c.fillStyle='#ebc998';c.beginPath();c.arc(0,-s*.3,s*.24,0,7);c.fill();c.fillStyle='#8d9f99';c.fillRect(-s*.29,-s*.52,s*.58,s*.17);c.fillStyle=o.side?'#b75248':'#377e94';c.fillRect(-s*.06,-s*.65,s*.12,s*.19);c.fillStyle='#253a38';c.fillRect((o.side?-.17:.09)*s,-s*.34,s*.06,s*.06);c.strokeStyle='#485c58';c.lineWidth=s*.18;c.beginPath();c.moveTo(0,-s*.02);c.lineTo((o.side?-1:1)*s*.48,-s*.17);c.stroke();if(o.id===selected&&battle.turn===0){c.strokeStyle='#ffe2a0';c.lineWidth=1.5;c.beginPath();c.ellipse(0,s*.46,s*.42,s*.14,0,0,7);c.stroke();}c.fillStyle='#223e39';c.fillRect(-s*.32,-s*.95,s*.64,2);c.fillStyle=o.side?'#e69779':'#dbe197';c.fillRect(-s*.32,-s*.95,s*.64*o.hp/o.maxHp,2);}else if(o.kind==='shot'){c.shadowColor='#f6d39c';c.shadowBlur=10;c.fillStyle=o.role==='alchemist'?'#f3a567':'#394e51';c.beginPath();c.arc(0,0,o.radius*scale,0,7);c.fill();c.fillStyle='#ffffde';c.beginPath();c.arc(-o.radius*scale*.3,-o.radius*scale*.3,o.radius*scale*.25,0,7);c.fill();}c.restore();}
 if(battle.turn===0&&battle.stage==='aim'){const u=battle.objects.find(o=>o.id===selected&&!o.dead);if(u){const p=battle.origin(u),v=battle.velocity(0,aimAngle,aimPower);let prev=planck.Vec2(p.x,p.y),hit=null;c.fillStyle='#fff4bb';c.strokeStyle='#274d4b';c.lineWidth=1;for(let t=.045;t<7;t+=.045){const next=planck.Vec2(p.x+v.x*t,p.y+v.y*t-5*t*t);battle.world.rayCast(prev,next,(f,point,normal,fraction)=>{const obj=f.getBody().getUserData();if(obj?.id===selected)return -1;hit={x:point.x,y:point.y};return fraction;});if(hit||next.y<0)break;if(Math.round(t/.045)%2===0){c.beginPath();c.arc(sx(next.x),sy(next.y),2.2,0,7);c.fill();c.stroke();}prev=next;}if(hit){c.strokeStyle='#f5b879';c.lineWidth=2;c.beginPath();c.arc(sx(hit.x),sy(hit.y),6,0,7);c.stroke();}c.strokeStyle='#fff0b4';c.lineWidth=2;c.beginPath();c.arc(sx(target.x),sy(target.y),10,0,7);c.moveTo(sx(target.x)-15,sy(target.y));c.lineTo(sx(target.x)+15,sy(target.y));c.moveTo(sx(target.x),sy(target.y)-15);c.lineTo(sx(target.x),sy(target.y)+15);c.stroke();}}
 for(const e of battle.effects){c.globalAlpha=Math.max(0,e.life);c.fillStyle=e.color;c.beginPath();c.arc(sx(e.x),sy(e.y),e.r*scale*(1.2-e.life*.6),0,7);c.fill();c.globalAlpha=1;}
}
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000||0);last=now;if(!battle||paused||document.hidden)return;acc+=dt;while(acc>=1/60){acc-=1/60;battle.step(1/60);}if(battle.stage==='aim'&&battle.turn===1){aiDelay+=dt;if(aiDelay>1.3){const a=battle.aimAI();if(a)battle.fire(a.id,a.angle,a.power);aiDelay=0;sync();}}for(const e of battle.events.splice(0)){if(e.type==='turn'){if(innerWidth<600&&battle.turn===0){view=2;updateViewLabel();}sync();saveTurn();if(battle.winner!==null)showResult();else toast(battle.turn?'Rival’s turn':'Your turn');}else beep(e.type);}render();}
window.addEventListener('resize',render);document.addEventListener('visibilitychange',()=>{last=performance.now();acc=0;});Goobs.markPlayed('castle');Goobs.initUpdates();launch(store.get('feudBattle',null));requestAnimationFrame(frame);
window.FortressFeud={get battle(){return battle;},launch,get target(){return {...target};},get aim(){return {angle:aimAngle,power:aimPower};},get camera(){return camera;},version:VERSION};
})();
