/* Fortress Feud 1.0.0 — deterministic turn boundaries, real rigid-body fortresses. */
(function(root){
'use strict';
const P=typeof planck!=='undefined'?planck:require('../../shared/planck.min.js'), V=P.Vec2;
const materials={wood:{cost:2,hp:38,density:.7,color:'#aa6941'},stone:{cost:4,hp:78,density:1.5,color:'#b5aea0'},iron:{cost:7,hp:140,density:2.4,color:'#829ba3'}};
const crew=[{id:'gunner',name:'Gunner',weapon:'Cannonball',hint:'Heavy direct hit',color:'#e9b758',radius:.26,blast:1.3,damage:95}, {id:'bomber',name:'Bomber',weapon:'Burst shell',hint:'Wide blast',color:'#e48e57',radius:.28,blast:2.5,damage:72},{id:'ranger',name:'Ranger',weapon:'Iron bolt',hint:'Fast, narrow strike',color:'#80b394',radius:.18,blast:.8,damage:145},{id:'alchemist',name:'Alchemist',weapon:'Ember flask',hint:'Burns nearby blocks',color:'#b29ad6',radius:.26,blast:2,damage:80},{id:'mortar',name:'Mortar',weapon:'Siege bomb',hint:'Heavy overhead blast',color:'#94bacc',radius:.34,blast:1.8,damage:120},{id:'engineer',name:'Engineer',weapon:'Scrap shot',hint:'Repairs keep before firing',color:'#d4bf92',radius:.23,blast:1.3,damage:65}];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function design(type=0){let cells=[];const heights=type===1?[4,4,2,2,3,2,2,4,4]:type===2?[2,3,4,4,2,4,4,3,2]:[4,4,3,2,2,2,3,4,4];for(let x=0;x<9;x++)for(let y=0;y<heights[x];y++)cells.push({x,y,mat:'stone'});return cells;}
const cost=cells=>cells.reduce((n,c)=>n+materials[c.mat].cost,0);
function valid(cells){if(!cells.length)return false;const keys=new Set(cells.map(c=>c.x+','+c.y));return cells.every(c=>c.y===0||keys.has(c.x+','+(c.y-1)));}
function opponent(level){const cells=design((level-1)%3);for(const c of cells){c.mat=level<=3?(c.y>0?'wood':'stone'):level<8?'stone':(c.x===4||((c.x+c.y+level)%4===0)?'iron':'stone');}if(level>4)for(const x of [0,1,7,8])cells.push({x,y:4,mat:level>=10?'iron':'stone'});if(level>11)for(const x of [0,1,7,8])cells.push({x,y:5,mat:'iron'});return cells;}
class Battle{
 constructor(level,cells,team,save){this.level=level;this.roster=team;this.world=new P.World(V(0,-10));this.objects=[];this.nextId=1;this.effects=[];this.turn=0;this.round=1;this.stage='aim';this.time=0;this.shot=null;this.events=[];this.seed=level*12907;this.settleTime=0;this.winner=null;const ground=this.world.createBody();ground.createFixture(P.Box(40,.5,V(0,-.5)),{friction:.8});this.world.on('begin-contact',c=>{const a=c.getFixtureA().getBody().getUserData(),b=c.getFixtureB().getBody().getUserData();if(a?.kind==='shot')this.impact(a,b);if(b?.kind==='shot')this.impact(b,a);});
 if(save){this.restore(save);return;}
 for(let side=0;side<2;side++){const layout=side?opponent(level):cells,origin=side?10:-10;for(const c of layout.filter(c=>!(c.x===4&&c.y<2)))this.add({kind:'block',side,mat:c.mat,x:origin+c.x-4,y:c.y+.5,hp:materials[c.mat].hp,w:.98,h:.98});this.add({kind:'keep',side,x:origin,y:1,hp:side&&level<4?100:180,w:.96,h:1.98});const ids=side?['gunner','bomber',level>4?'mortar':'ranger',level>8?'alchemist':'engineer']:team;[1,3,5,7].forEach((col,i)=>{let top=layout.filter(c=>c.x===col).reduce((n,c)=>Math.max(n,c.y+1),0);this.add({kind:'crew',side,role:ids[i],slot:i,x:origin+col-4,y:top+.45,hp:side&&level<4?55:90,w:.55,h:.8});});}
 // Let the initial stack settle without dealing fall damage.
 for(let i=0;i<120;i++)this.world.step(1/60);for(const o of this.objects){o.lastY=o.body.getPosition().y;o.body.setAwake(false);}this.events=[];
 }
 random(){this.seed=(Math.imul(this.seed,1664525)+1013904223)>>>0;return this.seed/4294967296;}
 add(d){const o={id:this.nextId++,...d};const b=this.world.createDynamicBody({position:V(d.x,d.y),angle:d.angle||0,linearDamping:d.kind==='shot'?0:.12,angularDamping:.25,bullet:d.kind==='shot',fixedRotation:d.kind==='crew'});let shape=d.kind==='shot'?P.Circle(d.radius):P.Box(d.w/2,d.h/2);b.createFixture(shape,{density:d.kind==='shot'?5:d.kind==='crew'?1:d.kind==='keep'?3:materials[d.mat].density,friction:.65,restitution:d.kind==='shot'?.05:0});b.setUserData(o);o.body=b;o.maxHp=d.maxHp||d.hp;o.lastY=d.y;o.dead=false;this.objects.push(o);return o;}
 living(side,kind){return this.objects.filter(o=>!o.dead&&o.side===side&&o.kind===kind);}
 keep(side){return this.living(side,'keep')[0];}
 health(side){return Math.max(0,Math.round(this.keep(side)?.hp||0));}
 origin(unit){const p=unit.body.getPosition(),dir=unit.side?-1:1;return{x:p.x+dir*.6,y:p.y+.5};}
 velocity(side,angle,power){const speed=10+power*.24,a=angle*Math.PI/180;return V(Math.cos(a)*speed*(side?-1:1),Math.sin(a)*speed);}
 fire(id,angle,power){if(this.stage!=='aim'||this.winner!==null)return false;const u=this.objects.find(o=>o.id===id&&!o.dead&&o.side===this.turn&&o.kind==='crew');if(!u)return false;const weapon=crew.find(c=>c.id===u.role);if(u.role==='engineer'){const k=this.keep(u.side);if(k)k.hp=Math.min(k.maxHp,k.hp+16);}
 const start=this.origin(u);const shot=this.add({kind:'shot',side:u.side,role:u.role,x:start.x,y:start.y,radius:weapon.radius,hp:1});shot.body.setLinearVelocity(this.velocity(u.side,angle,power));this.shot=shot;this.stage='flight';this.time=0;this.settleTime=0;this.events.push({type:'fire'});return true;}
 impact(shot,other){if(shot.dead||shot.hit||other?.kind==='shot')return;shot.hit=true;shot.hitId=other?.id;}
 explode(shot){const p=shot.body.getPosition(),w=crew.find(c=>c.id===shot.role);this.effects.push({x:p.x,y:p.y,r:w.blast,life:1,color:shot.role==='alchemist'?'#eb8155':'#f2c475'});for(const o of this.objects){if(o.dead||o===shot||o.kind==='shot')continue;const q=o.body.getPosition(),dx=q.x-p.x,dy=q.y-p.y,d=Math.hypot(dx,dy),reach=w.blast+(o.kind==='keep'?1:.5);if(d>reach&&o.id!==shot.hitId)continue;const factor=o.id===shot.hitId?1:clamp(1-d/reach,.08,1);o.hp-=w.damage*factor;const impulse=9*factor;o.body.applyLinearImpulse(V(dx/(d||1)*impulse,Math.max(.4,dy/(d||1))*impulse),q,true);if(shot.role==='alchemist')o.hp-=15*factor;}this.remove(shot);this.events.push({type:'impact'});}
 remove(o){if(o.dead)return;o.dead=true;this.world.destroyBody(o.body);}
 step(dt=1/60){if(this.winner!==null||this.stage!=='flight')return;this.world.step(dt);for(const e of this.effects)e.life-=dt;this.effects=this.effects.filter(e=>e.life>0);if(this.stage!=='flight')return;this.time+=dt;const shot=this.shot;if(shot&&!shot.dead){const p=shot.body.getPosition();if(shot.hit)this.explode(shot);else if(this.time>8||p.y<-.5||Math.abs(p.x)>38)this.remove(shot);}
 for(const o of this.objects){if(o.dead||o.kind==='shot')continue;const p=o.body.getPosition();if(o.kind==='crew'){const drop=o.lastY-p.y;if(drop>1.5&&Math.abs(o.body.getLinearVelocity().y)<1)o.hp-=(drop-1.5)*30;if(Math.abs(o.body.getLinearVelocity().y)<.6)o.lastY=p.y;}if(o.hp<=0||p.y<-.4||Math.abs(p.x)>36){this.effects.push({x:p.x,y:p.y,r:.6,life:.5,color:o.kind==='crew'?'#e4d4aa':'#c8b89a'});this.remove(o);}}
 if(shot?.dead){this.settleTime+=dt;if(this.settleTime>2.8){const a=!this.keep(0)||!this.living(0,'crew').length,b=!this.keep(1)||!this.living(1,'crew').length;if(a||b){this.winner=a?(b?2:1):0;this.stage='over';}else{this.turn=1-this.turn;if(!this.turn)this.round++;this.stage='aim';}this.shot=null;this.events.push({type:'turn'});}}
 }
 aimAI(side=this.turn){const units=this.living(side,'crew');const u=units[Math.floor(this.random()*units.length)];if(!u)return null;const targets=[this.keep(1-side),...this.living(1-side,'crew')].filter(Boolean),target=targets[this.random()<.65?0:Math.floor(this.random()*targets.length)];const p=target.body.getPosition(),s=this.origin(u),dx=Math.abs(p.x-s.x),dy=p.y-s.y;let best=null;for(let angle=28;angle<=76;angle+=2){const a=angle*Math.PI/180,den=2*Math.cos(a)**2*(dx*Math.tan(a)-dy);if(den<=0)continue;const speed=Math.sqrt(10*dx*dx/den),power=(speed-10)/.24;if(power>=5&&power<=100&&(!best||angle>best.angle))best={id:u.id,angle,power};}if(!best)best={id:u.id,angle:52,power:55};const err=this.level<4?14:Math.max(1.4,9-this.level*.55);best.power=clamp(best.power+(this.random()-.5)*err,5,100);best.angle=clamp(best.angle+(this.random()-.5)*err*.5,12,80);return best;}
 snapshot(){return{level:this.level,roster:this.roster,turn:this.turn,round:this.round,seed:this.seed,stage:this.stage,winner:this.winner,objects:this.objects.filter(o=>!o.dead&&o.kind!=='shot').map(o=>{const p=o.body.getPosition(),v=o.body.getLinearVelocity();return{id:o.id,kind:o.kind,side:o.side,mat:o.mat,role:o.role,slot:o.slot,x:p.x,y:p.y,angle:o.body.getAngle(),vx:v.x,vy:v.y,av:o.body.getAngularVelocity(),w:o.w,h:o.h,hp:o.hp,maxHp:o.maxHp,lastY:o.lastY};})};}
 restore(s){this.roster=s.roster||s.objects.filter(o=>o.kind==='crew'&&o.side===0).map(o=>o.role);this.turn=s.turn;this.round=s.round;this.seed=s.seed;this.stage=s.stage==='over'?'over':'aim';this.winner=s.winner??null;for(const d of s.objects){const o=this.add(d);o.body.setLinearVelocity(V(d.vx||0,d.vy||0));o.body.setAngularVelocity(d.av||0);o.lastY=d.lastY??d.y;this.nextId=Math.max(this.nextId,d.id+1);}}
}
const api={Battle,crew,materials,design,cost,valid,opponent};root.FeudEngine=api;if(typeof module!=='undefined')module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
