import * as T from '../../shared/three.module.min.js';
import * as C from '../../shared/cannon-es.min.js';
(function(){
'use strict';
const $=id=>document.getElementById(id), store=Goobs.store('castle'), S=CCSound;
const legacy=store.get('meta',{})||{};
let prefs=Object.assign({sound:false,aim:'timed',motion:true,quality:true},store.get('havocSettings',{})||{});
if(matchMedia('(prefers-reduced-motion: reduce)').matches)prefs.motion=false;
let records={cannon:store.get('siege2',null)||{level:Math.max(1,Number(legacy.level)||1),open:Math.max(1,Number(legacy.open)||1),stars:{}},sling:store.get('sling2',null)||{level:1,open:1,stars:{}}};
for(const r of Object.values(records)){r.open=Math.max(1,Math.min(9999999,r.open|0));r.level=Math.max(1,Math.min(r.open,r.level|0));r.stars=r.stars&&typeof r.stars==='object'?r.stars:{}}
let sideX=4;
let mode='cannon',sim=null,level=null,SC,rig,sideCam,state='hub',phase='horizontal',aimClock=0,aimX=.5,aimY=.5,swing=12,yaw=.24,yawTarget=.24,flight=[],bombs=1,ammo='stone',sandbox=false,winAt=0,awarded=false,last=0,acc=0,elapsed=0,toastUntil=0,chain=0,chainUntil=0,page=0,drag=null;
const ray=new T.Raycaster(),v=new T.Vector3();
let trajectory=null,trailPoints=[],trailClock=0;
function clearTrail(){if(trajectory){SC.scene.remove(trajectory);trajectory.geometry.dispose();trajectory.material.dispose();trajectory=null;}trailPoints=[];}
function trackTrail(dt){if(mode!=='sling')return;const active=flight.find(f=>!f.ball.gone);if(!active)return;trailClock+=dt;if(trailClock<.04)return;trailClock=0;trailPoints.push(active.ball.b.position.clone());if(trailPoints.length>180)trailPoints.shift();if(!trajectory){trajectory=new T.Line(new T.BufferGeometry(),new T.LineBasicMaterial({color:0xe9d09b,transparent:true,opacity:.65,depthTest:false}));trajectory.renderOrder=5;SC.scene.add(trajectory);}trajectory.geometry.dispose();trajectory.geometry=new T.BufferGeometry().setFromPoints(trailPoints);}
let guidePoints=[],guideKey='';
function updateGuide(){const visible=mode==='sling'&&phase==='ready'&&!isPaused();show('trajectoryPreview',visible);if(!visible)return;const key=swing+':'+sim.shots+':'+level.n+':'+Math.floor(sim.t*2);if(guideKey!==key){guideKey=key;guidePoints=CastleSling.predict(swing,sim);}const d=guidePoints.map((p,i)=>{const v=new T.Vector3(p[0],p[1],.5).project(sideCam);return(i?'L':'M')+((v.x+1)*innerWidth/2).toFixed(1)+','+((1-v.y)*innerHeight/2).toFixed(1)}).join(' ');$('previewShadow').setAttribute('d',d);$('previewLine').setAttribute('d',d);}

function save(){store.set(mode==='cannon'?'siege2':'sling2',records[mode]);}
function savePrefs(){store.set('havocSettings',prefs);S.setEnabled(prefs.sound)}
function show(id,on){$(id).toggleAttribute('hidden',!on)}
function isPaused(){return !$('sheet').hidden||!$('hub').hidden||document.hidden}
function toast(text){$('impactText').textContent=text;$('impactText').classList.add('show');toastUntil=elapsed+2;}
function sheet(title,body,actions,eyebrow){$('sheetTitle').textContent=title;$('sheetEyebrow').textContent=eyebrow||'CASTLE HAVOC';$('sheetBody').innerHTML=body;$('sheetActions').replaceChildren();for(const [label,fn,primary] of actions){const b=document.createElement('button');b.textContent=label;if(primary)b.className='primary';b.onclick=()=>{close();fn()};$('sheetActions').append(b)}show('sheet',true);$('closeSheet').focus();}
function close(){show('sheet',false);last=0;$('fire').focus({preventScroll:true});}
function help(){sheet('Two ways to siege','<h3>Castle Crumble · 3D cannon</h3><p>Tap <b>Lock horizontal</b> when the moving sight lines up with your target. Tap <b>Fire cannon</b> to lock its height and fire. Aim at the red powder magazines or low supporting walls. Drag the battlefield or use the view arrows to inspect another side.</p><h3>Castle Sling · side-view trebuchet</h3><p>Set the <b>angle slider</b> or tap a castle target, check the dotted trajectory, then tap <b>Fire sling</b>. Low, Medium and High presets make quick adjustments easy. There is no timing window. Bring down every guard before ammunition runs out. Choose stone, triple shot, or your one explosive bomb.</p><p>Space/Enter operates the main action. Escape pauses. Arrow keys rotate the 3D view. Both campaigns continue offline.</p>',[['Got it',()=>{},true]]);}
function pause(){sheet('Take a breather','<div class="option"><div>Sound</div><input id="soundSetting" type="checkbox" '+(prefs.sound?'checked':'')+'></div><label class="option"><div>Cannon aiming<small>Timed sights or direct tap to shoot</small></div><select id="aimSetting"><option value="timed">Timed sights</option><option value="direct">Direct touch</option></select></label><label class="option"><div>Camera effects<small>Gentle movement and impact shake</small></div><input id="motionSetting" type="checkbox" '+(prefs.motion?'checked':'')+'></label><p>'+level.name+' · Level '+level.n+(sandbox?' · Free demolition':'')+'</p>',[['Resume',()=>{},true],['Levels',openLevels],['Restart',()=>start(mode,level.n)],['How to play',help],['Castle Havoc',hub]]);
$('aimSetting').value=prefs.aim;$('aimSetting').onchange=e=>{prefs.aim=e.target.value;resetAim();savePrefs()};$('soundSetting').onchange=e=>{prefs.sound=e.target.checked;savePrefs();S.unlock()};$('motionSetting').onchange=e=>{prefs.motion=e.target.checked;savePrefs()};}
function openLevels(){const r=records[mode];page=Math.max(0,Math.min(Math.floor((r.open-1)/16),page));let html='<p>'+ (mode==='cannon'?'Castle Crumble':'Castle Sling')+' · Choose a stronghold</p><div class="levels">';for(let i=page*16+1;i<=page*16+16;i++)html+='<button data-level="'+i+'" '+(i>r.open?'disabled':'')+' class="'+(i===level.n?'current':'')+'">'+i+'<small>'+(i>r.open?'Locked':('★'.repeat(r.stars[i]||0)||'—'))+'</small></button>';html+='</div>';sheet('The campaign',html,[['Previous',()=>{page--;openLevels()}],['Next',()=>{page++;openLevels()}],['Back to game',()=>{},true]]);$('sheetBody').querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{close();start(mode,+b.dataset.level)});}
function resetAim(){phase=mode==='sling'?'ready':'horizontal';aimClock=0;if(mode!=='sling')swing=12;aimY=.5;updateControls();}
function hub(){state='hub';show('hub',true);for(const id of ['hud','readout','controls','aim'])show(id,false);$('cannonResume').textContent='Continue · Level '+records.cannon.level+' ↗';$('slingResume').textContent='Continue · Level '+records.sling.level+' ↗';}
function start(which,n,preview){
clearTrail();guideKey='';mode=which;swing=12;sideX=4;sandbox=false;awarded=false;winAt=0;chain=0;bombs=1;ammo='stone';mode==='sling'?document.body.classList.add('side'):document.body.classList.remove('side');
level=mode==='cannon'?SiegeLevels.make(n):CastleSling.level(n);sim=CC.create(level);if(mode==='sling')CastleSling.constrain(sim);
flight.forEach(f=>SC.scene.remove(f.mesh));flight=[];SC.setPieces(level.pieces,level.theme);SC.addDetails(level);SC.fitView(level.pieces,.68);SC.view.zoom=0;SC.reticle.visible=false;SC.gun.visible=mode==='cannon';rig.group.visible=mode==='sling';SC.setEnvironment(mode==='sling');yaw=yawTarget=level.yaw||.24;
if(!preview){records[mode].level=n;save();}state='play';acc=0;resetAim();show('hub',false);close();for(const id of ['hud','readout','controls'])show(id,true);$('region').textContent=level.region.toUpperCase()+' / '+String(n).padStart(2,'0');$('levelTitle').textContent=level.name;$('goalLabel').textContent=mode==='cannon'?'DESTRUCTION · TARGET '+Math.round(level.target*100)+'%':'GUARDS DEFEATED';$('targetMark').style.left=(mode==='cannon'?level.target*100:100)+'%';resize();updateHud();if(!preview)toast(level.hint);if(preview)hub();}
function resize(){if(!SC)return;const w=innerWidth,h=innerHeight;SC.resize(w,h,{top:h>550?165:80,bottom:h>550?190:95,side:18});const aspect=w/h,halfW=aspect<1?9.5:Math.max(20.5,14*aspect),halfH=halfW/aspect;const controlsTop=$('controls').getBoundingClientRect().top;const groundY=Math.min(h*.63,controlsTop>0?controlsTop-18:h*.63);const centerY=mode==='sling'?(groundY/h*2-1)*halfH:Math.max(5,halfH*.26);sideCam.left=-halfW;sideCam.right=halfW;sideCam.top=halfH;sideCam.bottom=-halfH;sideCam.position.set(aspect<1?sideX:-1,centerY,45);sideCam.lookAt(aspect<1?sideX:-1,centerY,0);sideCam.updateProjectionMatrix();sideCam.updateMatrixWorld();}
function remainingGuards(){return sim.pieces.filter(p=>p.t==='guard'&&!p.down&&!p.gone).length;}
function updateHud(){const pct=mode==='cannon'?CC.progress(sim):1-remainingGuards()/level.guards.length;$('progress').style.width=Math.min(100,pct*100)+'%';$('percent').textContent=mode==='cannon'?Math.floor(pct*100)+'%':(level.guards.length-remainingGuards())+' / '+level.guards.length;$('shotCount').textContent=sandbox?'Unlimited shots':sim.ballsLeft+' shot'+(sim.ballsLeft===1?'':'')+' left';$('bestStars').textContent='★'.repeat(records[mode].stars[level.n]||0);}
function updateControls(){const sling=mode==='sling';show('orbit',!sling);show('ammo',sling);show('slingAim',sling);const ready=state==='play'||state==='sandbox';$('fire').disabled=!ready||phase==='flight';$('resetAim').hidden=sling||phase==='flight';show('aim',!sling&&prefs.aim==='timed'&&ready&&phase!=='flight'&&!isPaused());
let instruction,label;
if(phase==='flight'){instruction='Let the structure settle';label='Watching the fall…';}
else if(sling){instruction='Set the angle or tap a target · then fire';label='Fire sling ↗';}
else if(prefs.aim==='direct'){instruction='Tap the castle to fire · drag to orbit';label='Direct touch enabled';$('fire').disabled=true;}
else{instruction=phase==='horizontal'?'First: choose left / right':'Now: choose the height';label=phase==='horizontal'?'Lock horizontal →':'Fire cannon ↗';}
$('instruction').textContent=instruction;$('fire').textContent=label;$('ammo').querySelectorAll('button').forEach(b=>{b.classList.toggle('selected',b.dataset.ammo===ammo);b.disabled=phase==='flight'||phase==='swing'||(b.dataset.ammo==='bomb'&&bombs===0&&!sandbox)});$('ammo').querySelector('small').textContent=sandbox?'∞':bombs;}
function pointAt(nx,ny){ray.setFromCamera(new T.Vector2(nx*2-1,1-ny*2),SC.camera);const hit=SC.pickPiece(ray);if(hit)return[hit.x,hit.y,hit.z];const o=ray.ray.origin,d=ray.ray.direction,n=new T.Vector3(o.x,0,o.z).normalize(),den=d.x*n.x+d.z*n.z;if(Math.abs(den)<1e-5)return[0,0,0];const t=-(o.x*n.x+o.z*n.z)/den;return[o.x+d.x*t,Math.max(.15,o.y+d.y*t),o.z+d.z*t];}
function addBall(ball){const mesh=SC.ballMesh();if(ball.r)mesh.scale.setScalar(ball.r/CC.BALLR);flight.push({ball,mesh});}
function cannonFire(p){if(isPaused()||phase==='flight'||!['play','sandbox'].includes(state))return;if(sandbox)sim.ballsLeft=99;const o=SC.muzzle(new T.Vector3()),b=CC.shoot(sim,yaw,p,[o.x,o.y,o.z]);if(!b)return;addBall(b);SC.aimGun(...p);SC.fireGun();S.shoot();phase='flight';aimClock=0;updateControls();}
function action(){if(isPaused()||!['play','sandbox'].includes(state)||phase==='flight')return;S.unlock();if(mode==='cannon'){if(prefs.aim==='direct')return;if(phase==='horizontal'){phase='vertical';aimClock=0;updateControls();}else cannonFire(pointAt(aimX,aimY));}else if(phase==='ready'){if(sandbox)sim.ballsLeft=99;clearTrail();CastleSling.fire(C,sim,swing,ammo).forEach(addBall);rig.fire();if(ammo==='bomb'&&!sandbox){bombs--;ammo='stone'}S.shoot();phase='flight';updateControls();}}

function result(win){state=win?'won':'lost';phase='flight';show('aim',false);updateControls();const shots=sim.shots;let stars=shots<=level.bot?3:shots<=level.bot+2?2:1;
if(win&&!awarded){awarded=true;const r=records[mode];r.open=Math.max(r.open,Math.min(9999999,level.n+1));r.stars[level.n]=Math.max(r.stars[level.n]||0,stars);save();S.win();}else if(!win)S.lose();
const body=(win?'<div class="award">'+'★'.repeat(stars)+'<span style="opacity:.22">'+'★'.repeat(3-stars)+'</span></div>':'')+'<div class="resultstats"><div><b>'+Math.floor(CC.progress(sim)*100)+'%</b><small>Castle displaced</small></div><div><b>'+shots+'</b><small>Shots used</small></div></div><p>'+(win?'The stronghold is yours. Continue the campaign, or stay and finish the demolition.':mode==='sling'?remainingGuards()+' guards remain. Try a lower angle or a different projectile.':'Try the lower walls or a powder magazine to trigger a bigger collapse.')+'</p>';
sheet(win?'Stronghold conquered':'One more siege?',body,win?[['Next stronghold',()=>start(mode,Math.min(9999999,level.n+1)),true],['Keep demolishing',()=>{sandbox=true;state='sandbox';sim.ballsLeft=99;resetAim();updateHud()}],['Replay',()=>start(mode,level.n)]]:[['Try again',()=>start(mode,level.n),true],['Choose level',openLevels]],mode==='cannon'?'CASTLE CRUMBLE':'CASTLE SLING');}
function events(){let impacts=0;for(const e of CC.takeEvents(sim)){if(e.t==='boom'){SC.boom(e.x,e.y,e.z);S.boom();chain=elapsed<chainUntil?chain+1:1;chainUntil=elapsed+1.6;if(chain>1)toast('CHAIN REACTION ×'+chain)}else if(e.t==='hit'){if(e.ball&&impacts++<2){SC.impact(e.x,e.y,e.z,e.v,true);S.hit(e.m,e.v)}else if(e.v>5&&impacts++<3)SC.impact(e.x,e.y,e.z,e.v,false)}else if(e.t==='splash'){SC.splash(e.x,e.z);S.splash()}}}
function frame(ms){requestAnimationFrame(frame);if(!SC)return;const dt=Math.min(.05,last?(ms-last)/1000:0);last=ms;elapsed+=dt;const paused=isPaused();
if(!paused&&sim){acc+=dt;let count=0;while(acc>=1/60&&count++<3){CC.step(sim,1/60);if(mode==='sling')for(const b of sim.balls)if(b.explode&&!b.gone){b.explode=false;CastleSling.blast(sim,b)}events();acc-=1/60}if(count>3)acc=0;
if(phase==='flight'&&sim.t-sim.lastShotT>3.8){if(sim.ballsLeft>0||sandbox)resetAim();}
if(state==='play'){const win=mode==='cannon'?CC.won(sim):remainingGuards()===0;if(win){if(!winAt)winAt=sim.t;if(sim.t-winAt>2.5)result(true)}else if(sim.ballsLeft<=0&&!CC.flying(sim)&&(CC.settled(sim)||sim.t-sim.lastShotT>8))result(false)}
if((!winAt&&state==='play'||state==='sandbox')&&phase!=='flight'){aimClock+=dt;if(mode==='cannon'){if(phase==='horizontal')aimX=.5+Math.sin(aimClock*1.15)*.32;else aimY=.46+Math.sin(aimClock*1.3)*.24;}}
updateHud();}
if(!paused)trackTrail(dt);SC.syncPieces(sim,paused?0:dt);flight=flight.filter(f=>{f.mesh.position.copy(f.ball.b.position);f.mesh.quaternion.copy(f.ball.b.quaternion);if(f.ball.gone){SC.scene.remove(f.mesh);return false}return true});
if(mode==='cannon'){yaw+=(yawTarget-yaw)*Math.min(1,dt*8);SC.view.zoom=0;SC.aimCamera(yaw,1,dt);if(!paused&&phase!=='flight'){const p=pointAt(aimX,aimY);SC.aimGun(...p)}SC.gun.visible=true;}else{SC.gun.visible=false;rig.update(swing,phase==='ready',paused?0:dt);if(innerWidth<innerHeight){const ball=flight.find(f=>!f.ball.gone);const target=phase==='flight'&&ball?Math.max(-9,Math.min(5,ball.ball.b.position.x)):4;sideX+=(target-sideX)*Math.min(1,dt*4);sideCam.position.x=sideX;sideCam.updateMatrixWorld();}}
SC.view.reducedMotion=!prefs.motion;SC.update(paused?0:dt);
if(elapsed>toastUntil)$('impactText').classList.remove('show');
$('slingAngle').disabled=phase==='flight';$('slingAngle').value=swing;$('angleValue').textContent=Math.round(swing)+'°';updateGuide();
$('aimV').style.left=aimX*100+'%';$('aimH').style.top=aimY*100+'%';$('crosshair').style.left=aimX*100+'%';$('crosshair').style.top=aimY*100+'%';$('aimH').style.opacity=phase==='horizontal'?'.25':'1';show('aim',mode==='cannon'&&prefs.aim==='timed'&&!paused&&['play','sandbox'].includes(state)&&phase!=='flight');
SC.renderer.render(SC.scene,mode==='sling'?sideCam:SC.camera);
}
$('closeSheet').onclick=()=>{if(state==='won'||state==='lost'){close();hub()}else close()};$('back').onclick=hub;$('menu').onclick=pause;$('hubHelp').onclick=help;$('allGames').onclick=()=>Goobs.home();$('fire').onclick=action;$('resetAim').onclick=resetAim;$('left').onclick=()=>{yawTarget-=Math.PI/6;resetAim()};$('right').onclick=()=>{yawTarget+=Math.PI/6;resetAim()};$('cannonGame').onclick=()=>start('cannon',records.cannon.level);$('slingGame').onclick=()=>start('sling',records.sling.level);
$('slingAngle').oninput=e=>{swing=+e.target.value;updateControls()};
$('slingAim').querySelectorAll('[data-angle]').forEach(b=>b.onclick=()=>{if(phase==='flight')return;swing=+b.dataset.angle;updateControls()});
$('ammo').querySelectorAll('button').forEach(b=>b.onclick=()=>{ammo=b.dataset.ammo;updateControls()});
$('world').addEventListener('pointerdown',e=>{if(isPaused())return;S.unlock();drag={id:e.pointerId,x:e.clientX,y:e.clientY,yaw:yawTarget,moved:false};$('world').setPointerCapture(e.pointerId)});
$('world').addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId||mode!=='cannon')return;const d=e.clientX-drag.x;if(Math.abs(d)>9)drag.moved=true;if(drag.moved){yawTarget=drag.yaw-d*.006;resetAim()}});
$('world').addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const d=drag;drag=null;if(d.moved)return;if(mode==='cannon'&&prefs.aim==='direct')cannonFire(pointAt(e.clientX/innerWidth,e.clientY/innerHeight));else if(mode==='sling'&&phase==='ready'){ray.setFromCamera(new T.Vector2(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2),sideCam);const hit=ray.ray.at(-ray.ray.origin.z/ray.ray.direction.z,new T.Vector3());const angle=CastleSling.angleTo(hit.x,hit.y);if(angle!==null){swing=angle;updateControls()}else toast('Target out of range — adjust the angle slider.');}else action()});$('world').addEventListener('pointercancel',()=>drag=null);
addEventListener('keydown',e=>{if(['INPUT','SELECT','BUTTON'].includes(document.activeElement?.tagName)&&e.code!=='Escape')return;if(e.code==='Escape'){if(!$('sheet').hidden){close();if(state==='won'||state==='lost')hub();}else if($('hub').hidden)pause();return;}if(e.code==='Space'||e.code==='Enter'){e.preventDefault();action()}if(!isPaused()&&mode==='cannon'){if(e.code==='ArrowLeft')yawTarget-=.12;if(e.code==='ArrowRight')yawTarget+=.12}});
addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{last=0;acc=0});
try{CC.use(C);SC=CCScene.build(T,$('world'),CC,{fancy:prefs.quality});sideCam=new T.OrthographicCamera(-21,21,12,-12,.1,400);rig=CastleSling.rig(T,SC.scene);S.setEnabled(prefs.sound);start('cannon',1,true);show('loading',false);Goobs.markPlayed('castle');Goobs.initUpdates({onVersions:v=>$('version').textContent='Castle Havoc '+(v.castle||'2.1.0')});requestAnimationFrame(frame);}
catch(e){console.error(e);$('loading').innerHTML='<b>The battlefield could not load.</b><span>Open online once to download the game, then try again.</span><button class="gold" onclick="location.reload()">Try again</button><button class="textbutton" onclick="Goobs.home()">All games</button>';}
// Read-only state plus game actions for deterministic QA; no network dependency.
window.__havoc={get sim(){return sim},get level(){return level},get mode(){return mode},get phase(){return phase},get state(){return state},start,action,cannonFire,pointAt,get scene(){return SC},records};
})();
