/* Shapes is a separate saved puzzle mode. Classic/Daily/Levels state is untouched. */
(()=>{'use strict';const patterns=[['Bird',['......##.','.....####','..######.','.#######.','########.','..#####..','...#.#...','..##.##..']],['House',['....#....','...###...','..#####..','.#######.','#########','.#######.','.##..###.','.##..###.']],['Sailboat',['....#....','...##....','..###....','.####....','#####....','....#....','#########','.#######.','..#####..']],['Butterfly',['##.....##','###.#.###','#########','.#######.','..#####..','.#######.','###.#.###','##..#..##']],['Cat',['##....##.','###..###.','########.','.######..','..####...','..####..#','.######.#','#########']],['Rocket',['....#....','...###...','..#####..','..#####..','..#####..','.#######.','###...###','..##.##..','...#.#...']]];
const colors=['#ee7351','#328ce0','#aa65d8','#efb839','#e24f87','#28aab3','#9165de','#ec923f'];let state;try{state=JSON.parse(localStorage.getItem('woodpile.shapes.v1'));}catch{}let selected=-1,drag=null;
const panel=document.createElement('section');panel.id='shapeMode';panel.hidden=true;panel.innerHTML='<header><button id="shapeExit">‹ Exit Game</button><button id="shapeBack">‹ Woodpile modes</button><h2>Shapes</h2><select id="shapePick" aria-label="Choose shape"></select></header><p id="shapeInstruction">Choose a block, then tap its upper-left square in the silhouette. Or drag it into place.</p><div class="shapeLayout"><div id="shapeBoard" role="grid" aria-label="Shape puzzle"></div><div class="shapeSide"><div id="shapePieces"></div><p id="shapeStatus" role="status"></p><div class="shapeActions"><button id="shapeUndo">Undo</button><button id="shapeReset">Restart shape</button><button id="shapeNext">Next shape →</button></div></div></div>';document.body.append(panel);const $=id=>document.getElementById(id);patterns.forEach((p,i)=>{const o=new Option(p[0],i);$('shapePick').add(o);});
function make(level){const rows=patterns[level][1],cells=[];rows.forEach((r,y)=>[...r].forEach((v,x)=>{if(v==='#')cells.push([x,y]);}));let remaining=new Set(cells.map(c=>c.join(','))),pieces=[],seed=level+731;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)|0;return(seed>>>0)/4294967296;};while(remaining.size){const origin=[...remaining][0],group=[origin.split(',').map(Number)];remaining.delete(origin);let max=3+Math.floor(rand()*3);while(group.length<max){let candidates=[];for(const [x,y]of group)for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]])if(remaining.has([x+dx,y+dy].join(',')))candidates.push([x+dx,y+dy]);if(!candidates.length)break;let c=candidates[Math.floor(rand()*candidates.length)];group.push(c);remaining.delete(c.join(','));}const mx=Math.min(...group.map(c=>c[0])),my=Math.min(...group.map(c=>c[1]));pieces.push(group.map(c=>[c[0]-mx,c[1]-my]));}return{level,pieces,placed:[],completed:[]};}
if(!state||!Array.isArray(state.pieces)||!patterns[state.level])state=make(0);
function save(){localStorage.setItem('woodpile.shapes.v1',JSON.stringify(state));}
function target(){return new Set(patterns[state.level][1].flatMap((r,y)=>[...r].flatMap((v,x)=>v==='#'?[x+','+y]:[])));}
function draw(){const board=$('shapeBoard');board.replaceChildren();const rows=patterns[state.level][1],occupied=new Map;state.placed.forEach(p=>state.pieces[p.id].forEach(([dx,dy])=>occupied.set([p.x+dx,p.y+dy].join(','),p.id)));board.style.setProperty('--rows',rows.length);for(let y=0;y<rows.length;y++)for(let x=0;x<9;x++){const b=document.createElement('button');b.className='shapeCell';b.dataset.x=x;b.dataset.y=y;b.setAttribute('aria-label','Row '+(y+1)+', column '+(x+1));b.disabled=rows[y][x]!=='#';if(occupied.has(x+','+y)){b.style.background=colors[occupied.get(x+','+y)%colors.length];b.classList.add('filled');}b.onclick=()=>place(x,y);board.append(b);}
$('shapePieces').replaceChildren();state.pieces.forEach((piece,id)=>{if(state.placed.some(p=>p.id===id))return;const b=document.createElement('button');b.className='shapePiece'+(id===selected?' selected':'');b.setAttribute('aria-label','Block '+(id+1)+', '+piece.length+' squares');const w=1+Math.max(...piece.map(c=>c[0])),h=1+Math.max(...piece.map(c=>c[1]));b.style.width=w*22+12+'px';b.style.height=h*22+12+'px';for(const[x,y]of piece){const c=document.createElement('i');c.style.cssText=`left:${6+x*22}px;top:${6+y*22}px;background:${colors[id%colors.length]}`;b.append(c);}b.onclick=()=>{selected=id;draw();};b.onpointerdown=e=>{selected=id;drag={id,x:e.clientX,y:e.clientY};b.setPointerCapture(e.pointerId);};b.onpointerup=e=>{if(!drag)return;const moved=Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>8;drag=null;if(moved){const r=board.getBoundingClientRect();place(Math.floor((e.clientX-r.left)/(r.width/9)),Math.floor((e.clientY-r.top)/(r.height/rows.length)));}else draw();};$('shapePieces').append(b);});const won=occupied.size===target().size;$('shapeStatus').textContent=won?patterns[state.level][0]+' complete!':state.placed.length+' / '+state.pieces.length+' blocks placed';$('shapeNext').hidden=!won;$('shapeUndo').disabled=!state.placed.length;$('shapePick').value=state.level;if(won&&!state.completed.includes(state.level)){state.completed.push(state.level);save();}}
function place(x,y){if(selected<0)return;const piece=state.pieces[selected],t=target(),used=new Set;state.placed.forEach(p=>state.pieces[p.id].forEach(([dx,dy])=>used.add([p.x+dx,p.y+dy].join(','))));if(piece.some(([dx,dy])=>!t.has([x+dx,y+dy].join(','))||used.has([x+dx,y+dy].join(',')))){$('shapeStatus').textContent='That block does not fit there. Try another position.';return;}state.placed.push({id:selected,x,y});selected=-1;save();draw();}
function change(n){const done=state.completed;state=make(n);state.completed=done;selected=-1;save();draw();}
$('shapeExit').onclick=()=>document.getElementById('btnHome').click();$('shapePick').onchange=e=>change(+e.target.value);$('shapeUndo').onclick=()=>{const p=state.placed.pop();selected=p.id;save();draw();};$('shapeReset').onclick=()=>change(state.level);$('shapeNext').onclick=()=>change((state.level+1)%patterns.length);$('shapeBack').onclick=()=>{panel.hidden=true;document.body.classList.remove('shape-open');window.dispatchEvent(new Event('resize'));};const mode=document.createElement('button');mode.textContent='Shapes';mode.type='button';mode.onclick=e=>{e.stopPropagation();panel.hidden=false;document.body.classList.add('shape-open');draw();};mode.addEventListener('click',e=>e.stopPropagation());$('modes').append(mode);
window.WoodpileShapes={patterns,make,get state(){return state;}};
})();
