/* Standalone silhouette puzzles; classic Woodpile saves and rules are unchanged. */
(()=>{'use strict';
const patterns=[
{name:'Cat',path:'M1 5.8 L1 1.2 Q1 1 .2 .2 L2.4 1.4 L4 1.4 L5 .3 L5 3 Q7.8 2.2 7.7 5.8 Q9 6.6 7.7 7.5 L6.1 8 Q5.6 8 5.8 7.6 L7.2 6.8 Q7.7 6.4 7.1 6.3 L.8 6.3 Q.2 6.2 .5 5.9 Z',w:9,h:8},
{name:'Sailboat',path:'M4.4 .3 L4.4 5.2 L.6 5.2 Z M4.8 1.3 L7.7 5.2 L4.8 5.2 Z M.3 5.7 L8.4 5.7 L6.6 7.6 L2 7.6 Z',w:9,h:8},
{name:'Bird',path:'M.5 3.7 Q2.6 4.4 4.1 2.3 Q5.7 .2 7.1 1.8 L8.5 2.2 L7.1 2.7 Q7.2 5.5 4.4 6.3 L3 7.6 L3.1 6.1 Q1.6 5.8 .5 3.7 Z',w:9,h:8},
{name:'House',path:'M.4 3.5 L4.5 .4 L6 1.6 L6 .6 L7 .6 L7 2.4 L8.6 3.5 L7.6 3.5 L7.6 7.5 L1.4 7.5 L1.4 3.5 Z',w:9,h:8},
{name:'Pine tree',path:'M4.5 .2 L6.2 2.6 L5.4 2.6 L7.3 4.8 L6.1 4.8 L8.2 6.8 L5.2 6.8 L5.2 7.8 L3.8 7.8 L3.8 6.8 L.8 6.8 L2.9 4.8 L1.7 4.8 L3.6 2.6 L2.8 2.6 Z',w:9,h:8},
{name:'Heart',path:'M4.5 7.6 C3.7 6.7 .6 4.5 .6 2.7 C.6 .3 3.4 -.1 4.5 2 C5.6 -.1 8.4 .3 8.4 2.7 C8.4 4.5 5.3 6.7 4.5 7.6 Z',w:9,h:8}
];
const key='woodpile.shapes.v2';let state,drag=null,selected=-1,hint=-1,serial=0;const ctx=document.createElement('canvas').getContext('2d');
function make(level){const p=patterns[level],path=new Path2D(p.path),cells=[];for(let y=0;y<p.h;y++)for(let x=0;x<p.w;x++){let hit=false;for(let a=.1;a<1;a+=.2)for(let b=.1;b<1;b+=.2)if(ctx.isPointInPath(path,x+a,y+b))hit=true;if(hit)cells.push([x,y]);}
 const connected=(x,y,a,b)=>{for(let t=.05;t<1;t+=.1){const xx=x===a?x+t:Math.max(x,a), yy=y===b?y+t:Math.max(y,b);if(ctx.isPointInPath(path,xx-.015*(x!==a),yy-.015*(y!==b))&&ctx.isPointInPath(path,xx+.015*(x!==a),yy+.015*(y!==b)))return true;}return false;}; let remaining=new Set(cells.map(c=>c.join(','))),groups=[];while(remaining.size){let seed=[...remaining][0].split(',').map(Number),g=[seed];remaining.delete(seed.join(','));for(let i=0;i<g.length&&g.length<5;i++){const[x,y]=g[i];for(const[dx,dy]of [[1,0],[0,1],[-1,0],[0,-1]]){let n=[x+dx,y+dy];if(g.length<5&&remaining.has(n.join(','))&&connected(x,y,...n)){g.push(n);remaining.delete(n.join(','));}}}groups.push(g);}
 for(let i=groups.length-1;i>=0;i--)if(groups[i].length<3){const j=groups.findIndex((g,j)=>j!==i&&g.some(([x,y])=>groups[i].some(([a,b])=>Math.abs(a-x)+Math.abs(b-y)===1&&connected(x,y,a,b))));if(j>=0){groups[j].push(...groups[i]);groups.splice(i,1);}}
 if(level===0){let tail=[];groups=groups.map(g=>{tail.push(...g.filter(c=>c[1]>=5));return g.filter(c=>c[1]<5);}).filter(g=>g.length);groups.push(tail);}
 const pieces=groups.map(cells=>{let x=Math.min(...cells.map(c=>c[0])),y=Math.min(...cells.map(c=>c[1]));return{cells,x,y,w:Math.max(...cells.map(c=>c[0]))-x+1,h:Math.max(...cells.map(c=>c[1]))-y+1};});return{level,pieces,placed:[],completed:[]};}
try{state=JSON.parse(localStorage.getItem(key));}catch{}if(!state||!patterns[state.level]||!Array.isArray(state.pieces))state=make(0);
const panel=document.createElement('section');panel.id='shapeMode';panel.hidden=true;panel.innerHTML='<header><button id="shapeBack">‹ Modes</button><h2>Shapes</h2><select id="shapePick" aria-label="Choose shape"></select></header><p id="shapeInstruction">Drag the wooden pieces into the silhouette.</p><div class="shapeLayout"><div class="shapeCanvas"><svg id="shapeBoard" aria-label="Shape puzzle" role="img"></svg></div><aside class="shapeSide"><div class="shapeTrayTitle">YOUR PIECES <span>No rotation needed</span></div><div id="shapePieces"></div><p id="shapeStatus" role="status" aria-live="polite"></p><div class="shapeActions"><button id="shapeUndo">Undo</button><button id="shapeHint">Hint</button><button id="shapeReset">Restart</button><button id="shapeNext" hidden>Next shape →</button></div></aside></div>';document.body.append(panel);const $=id=>document.getElementById(id);patterns.forEach((p,i)=>$('shapePick').add(new Option(p.name,i)));
function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{}}
function art(id,ghost=false){const p=state.pieces[id],shape=patterns[state.level],uid='wood'+(++serial),rects=p.cells.map(([x,y])=>`<rect x="${x}" y="${y}" width="1" height="1"/>`).join('');return `<defs><clipPath id="${uid}s"><path d="${shape.path}"/></clipPath><clipPath id="${uid}p">${rects}</clipPath><linearGradient id="${uid}g" x2=".3" y2="1"><stop stop-color="#f4cd82"/><stop offset=".5" stop-color="#dba45e"/><stop offset="1" stop-color="#c28847"/></linearGradient><pattern id="${uid}grain" width=".7" height=".45" patternUnits="userSpaceOnUse"><path d="M0 .1 Q.35 .04 .7 .13 M0 .3 Q.4 .36 .7 .27" fill="none" stroke="#693d21" stroke-opacity=".1" stroke-width=".025"/></pattern></defs><g clip-path="url(#${uid}s)"><g clip-path="url(#${uid}p)"><path d="${shape.path}" fill="url(#${uid}g)"/><path d="${shape.path}" fill="url(#${uid}grain)"/><g fill="none" stroke="#68401f" stroke-opacity=".55" stroke-width=".028">${rects}</g><path d="${shape.path}" fill="none" stroke="#ffe3ad" stroke-width=".09"/></g></g>`;}
function occupied(except=-1){const s=new Set;state.placed.filter(p=>p.id!==except).forEach(p=>state.pieces[p.id].cells.forEach(([x,y])=>s.add([x+p.dx,y+p.dy].join(','))));return s;}
// Matching boundary geometry matters: a curved edge must align with its recess.
function fits(id,dx,dy){const p=state.pieces[id],shape=patterns[state.level],path=new Path2D(shape.path),used=occupied(id);for(const[x,y]of p.cells){if(used.has([x+dx,y+dy].join(',')))return false;for(let a=.08;a<1;a+=.14)for(let b=.08;b<1;b+=.14)if(ctx.isPointInPath(path,x+a,y+b)!==ctx.isPointInPath(path,x+dx+a,y+dy+b))return false;}return true;}
function draw(){const shape=patterns[state.level],board=$('shapeBoard');board.setAttribute('viewBox',`-.4 -.4 ${shape.w+.8} ${shape.h+.8}`);board.innerHTML=`<defs><pattern id="shapeGrid" width="1" height="1" patternUnits="userSpaceOnUse"><path d="M1 0 H0 V1" fill="none" stroke="#dfaf6e" stroke-opacity=".24" stroke-width=".025"/></pattern></defs><path d="${shape.path}" fill="#492b22" stroke="#ecbd79" stroke-width=".09" stroke-linejoin="round"/><path d="${shape.path}" fill="url(#shapeGrid)"/>`;
 for(const p of state.placed){const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.dataset.piece=p.id;g.setAttribute('transform',`translate(${p.dx} ${p.dy})`);g.innerHTML=art(p.id);g.style.cursor='grab';g.onpointerdown=e=>begin(e,p.id,true);board.append(g);}
 if(hint>=0&&!state.placed.some(p=>p.id===hint)){const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.innerHTML=art(hint);g.setAttribute('opacity','.42');g.style.pointerEvents='none';board.append(g);}
 $('shapePieces').replaceChildren();state.pieces.forEach((p,id)=>{if(state.placed.some(v=>v.id===id))return;const b=document.createElement('button');b.className='woodPiece'+(selected===id?' selected':'');b.dataset.piece=id;b.setAttribute('aria-label',`Piece ${id+1}. Drag into the silhouette.`);b.innerHTML=`<svg viewBox="${p.x-.06} ${p.y-.06} ${p.w+.12} ${p.h+.12}" style="width:${p.w*22}px;height:${p.h*22}px" aria-hidden="true">${art(id)}</svg>`;b.onpointerdown=e=>begin(e,id,false);b.onclick=()=>{selected=id;hint=-1;draw();};$('shapePieces').append(b);});
 const won=state.placed.length===state.pieces.length;$('shapeStatus').textContent=won?`${shape.name} complete! Beautifully fitted.`:`${state.placed.length} of ${state.pieces.length} pieces fitted`;$('shapeNext').hidden=!won;$('shapeUndo').disabled=!state.placed.length;$('shapePick').value=state.level;if(won&&!state.completed.includes(state.level)){state.completed.push(state.level);save();}}
function boardPoint(x,y){const p=new DOMPoint(x,y).matrixTransform($('shapeBoard').getScreenCTM().inverse());return p;}
function begin(e,id,placed){if(e.button!==0)return;e.preventDefault();cancel();selected=id;hint=-1;const piece=state.pieces[id],r=(placed?e.currentTarget:e.currentTarget.querySelector('svg')).getBoundingClientRect(),point=boardPoint(e.clientX,e.clientY),old=state.placed.find(p=>p.id===id),offset=placed?{x:point.x-piece.x-old.dx,y:point.y-piece.y-old.dy}:(()=>{const pt=new DOMPoint(e.clientX,e.clientY).matrixTransform(e.currentTarget.querySelector('svg').getScreenCTM().inverse());return{x:pt.x-piece.x,y:pt.y-piece.y};})();const ghost=document.createElement('div');ghost.className='shapeDrag';ghost.innerHTML=`<svg viewBox="${piece.x-.06} ${piece.y-.06} ${piece.w+.12} ${piece.h+.12}">${art(id,true)}</svg>`;document.body.append(ghost);drag={id,offset,ghost,startX:e.clientX,startY:e.clientY,moved:false,placed,source:e.currentTarget,pointer:e.pointerId,lift:e.pointerType==='touch'?26:0};e.currentTarget.setPointerCapture(e.pointerId);e.currentTarget.classList.add('dragging');update(e);}
function update(e){if(!drag||e.pointerId!==drag.pointer)return;const d=drag,p=state.pieces[d.id],m=$('shapeBoard').getScreenCTM(),scale=m.a,point=boardPoint(e.clientX,e.clientY-d.lift);d.moved ||= Math.hypot(e.clientX-d.startX,e.clientY-d.startY)>7;d.dx=Math.round(point.x-d.offset.x-p.x);d.dy=Math.round(point.y-d.offset.y-p.y);d.valid=fits(d.id,d.dx,d.dy);Object.assign(d.ghost.style,{width:(p.w+.12)*scale+'px',height:(p.h+.12)*scale+'px',left:e.clientX-(d.offset.x+.06)*scale+'px',top:e.clientY-d.lift-(d.offset.y+.06)*scale+'px'});d.ghost.classList.toggle('valid',d.valid);$('shapeBoard').querySelector('.dropPreview')?.remove();if(d.valid){const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.classList.add('dropPreview');g.setAttribute('transform',`translate(${d.dx} ${d.dy})`);g.innerHTML=art(d.id);g.setAttribute('opacity','.55');g.style.pointerEvents='none';$('shapeBoard').append(g);}}
function cancel(){if(!drag)return;drag.source.classList.remove('dragging');drag.ghost.remove();$('shapeBoard').querySelector('.dropPreview')?.remove();drag=null;}
window.addEventListener('pointermove',e=>{if(drag){e.preventDefault();update(e);}},{passive:false});window.addEventListener('pointerup',e=>{if(!drag||e.pointerId!==drag.pointer)return;const d=drag;update(e);cancel();if(d.moved&&d.valid){state.placed=state.placed.filter(p=>p.id!==d.id);state.placed.push({id:d.id,dx:d.dx,dy:d.dy});selected=-1;save();draw();}else{draw();if(d.moved)$('shapeStatus').textContent='Try another spot — match the edges to the silhouette.';}});window.addEventListener('pointercancel',()=>{cancel();draw();});window.addEventListener('blur',cancel);window.addEventListener('resize',cancel);
$('shapeBoard').onclick=e=>{if(selected<0||drag||e.target.closest('[data-piece]'))return;const p=boardPoint(e.clientX,e.clientY),piece=state.pieces[selected],dx=Math.round(p.x-piece.x-piece.w/2),dy=Math.round(p.y-piece.y-piece.h/2);if(fits(selected,dx,dy)){state.placed.push({id:selected,dx,dy});selected=-1;save();draw();}};
function change(n){cancel();const done=state.completed;state=make(n);state.completed=done;selected=hint=-1;save();draw();}
$('shapePick').onchange=e=>change(+e.target.value);$('shapeUndo').onclick=()=>{state.placed.pop();selected=hint=-1;save();draw();};$('shapeReset').onclick=()=>change(state.level);$('shapeNext').onclick=()=>change((state.level+1)%patterns.length);$('shapeHint').onclick=()=>{hint=selected>=0?selected:state.pieces.findIndex((_,id)=>!state.placed.some(p=>p.id===id));draw();};$('shapeBack').onclick=()=>{cancel();panel.hidden=true;document.body.classList.remove('shape-open');window.dispatchEvent(new Event('resize'));};const mode=document.createElement('button');mode.id='shapeModeShortcut';mode.textContent='Shapes';mode.type='button';mode.onclick=e=>{e.stopPropagation();panel.hidden=false;document.body.classList.add('shape-open');draw();};$('modes').append(mode);
window.WoodpileShapes={open:()=>mode.click(),patterns,make,fits,get state(){return state;}};
})();
