(function(root){'use strict';const W=1000,H=500,R=12,POCKETS=[[0,0],[500,0],[1000,0],[0,500],[500,500],[1000,500]];function rack(){let balls=[{n:0,x:250,y:250,vx:0,vy:0,off:false}],order=[1,9,2,3,8,10,11,4,12,5,6,13,7,14,15],k=0;for(let row=0;row<5;row++)for(let j=0;j<=row;j++)balls.push({n:order[k++],x:690+row*21.3,y:250+(j-row/2)*24.6,vx:0,vy:0,off:false});return balls}function group(n){return n>0&&n<8?1:n>8?2:0}function remaining(s,p){return s.balls.filter(b=>!b.off&&group(b.n)===s.groups[p]).length}function target(s,p=s.turn){return s.groups[p]?(remaining(s,p)?s.groups[p]:8):0}function fresh(mode='solo',difficulty='medium'){return{balls:rack(),turn:0,groups:[0,0],mode,difficulty,phase:'aim',shot:null,break:true,hand:false,over:false,winner:null,message:'Your break. Aim on the table, then choose power and shoot.',shots:0}}
function shoot(s,angle,power){if(s.phase!=='aim'||s.over||s.hand)return false;let cue=s.balls.find(b=>b.n===0);s.shot={first:0,pots:[],rail:false,target:target(s)};cue.vx=Math.cos(angle)*power;cue.vy=Math.sin(angle)*power;s.phase='rolling';s.shots++;return true}
function step(s,dt){if(s.phase!=='rolling')return false;const live=s.balls.filter(b=>!b.off);for(const b of live){b.x+=b.vx*dt;b.y+=b.vy*dt;let pocket=POCKETS.some(([x,y])=>Math.hypot(x-b.x,y-b.y)<27);if(pocket){b.off=true;b.vx=b.vy=0;s.shot.pots.push(b.n);continue}let rail=false;if(b.x<R){b.x=R;b.vx=Math.abs(b.vx)*.84;rail=true}if(b.x>W-R){b.x=W-R;b.vx=-Math.abs(b.vx)*.84;rail=true}if(b.y<R){b.y=R;b.vy=Math.abs(b.vy)*.84;rail=true}if(b.y>H-R){b.y=H-R;b.vy=-Math.abs(b.vy)*.84;rail=true}if(rail&&s.shot.first)s.shot.rail=true;let speed=Math.hypot(b.vx,b.vy),newSpeed=Math.max(0,speed-(40+speed*.36)*dt),f=speed?newSpeed/speed:0;b.vx*=f;b.vy*=f;if(newSpeed<2)b.vx=b.vy=0}
 for(let i=0;i<live.length;i++)for(let j=i+1;j<live.length;j++){let a=live[i],b=live[j];if(a.off||b.off)continue;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d>=2*R||d<.001)continue;let nx=dx/d,ny=dy/d,ov=(2*R-d)/2;a.x-=nx*ov;a.y-=ny*ov;b.x+=nx*ov;b.y+=ny*ov;let dv=(a.vx-b.vx)*nx+(a.vy-b.vy)*ny;if(dv>0){a.vx-=dv*nx*.98;a.vy-=dv*ny*.98;b.vx+=dv*nx*.98;b.vy+=dv*ny*.98;if(!s.shot.first&&(a.n===0||b.n===0))s.shot.first=a.n===0?b.n:a.n}}
 return !s.balls.some(b=>!b.off&&Math.hypot(b.vx,b.vy)>0)}
function spot(s,n){const b=s.balls.find(b=>b.n===n);for(let x=700;x>=80;x-=30)for(let y of [250,210,290,170,330,130,370])if(s.balls.every(a=>a===b||a.off||Math.hypot(a.x-x,a.y-y)>R*2+2)){Object.assign(b,{x,y,vx:0,vy:0,off:false});return}}
function resolve(s){const q=s.shot,p=s.turn;let foul=q.pots.includes(0)||!q.first||(q.target===8?q.first!==8:q.target?group(q.first)!==q.target:q.first===8)||(!q.pots.length&&!q.rail);if(s.break&&q.pots.includes(8))spot(s,8);else if(q.pots.includes(8)){const won=!foul&&q.target===8;s.over=true;s.winner=won?p:1-p;s.phase='aim';s.message=(s.winner===0?'Player 1':'Player 2')+' wins '+(won?'with the 8-ball!':'— early 8-ball or scratch.');return}
 if(!foul&&!s.groups[p]){const n=q.pots.find(n=>group(n));if(n){s.groups[p]=group(n);s.groups[1-p]=3-group(n)}}let keep=!foul&&q.pots.some(n=>group(n)&&(s.groups[p]===group(n)||!s.groups[p]));s.break=false;s.turn=keep?p:1-p;s.phase='aim';s.hand=foul;if(q.pots.includes(0))spot(s,0);s.message=foul?'Foul. Ball in hand: tap a clear spot for the cue ball.':keep?'Pocketed! Shoot again.':'Next player’s turn.';s.shot=null}
function place(s,x,y){if(!s.hand||x<R+2||x>W-R-2||y<R+2||y>H-R-2||POCKETS.some(([px,py])=>Math.hypot(x-px,y-py)<35)||s.balls.some(b=>b.n&&!b.off&&Math.hypot(x-b.x,y-b.y)<R*2+2))return false;Object.assign(s.balls[0],{x,y,vx:0,vy:0,off:false});s.hand=false;s.message='Cue ball placed. Aim and shoot.';return true}
function distSegment(p,a,b){let dx=b.x-a.x,dy=b.y-a.y,t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy||1)));return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy)}function rollDistance(v){return v/.36-40/(.36*.36)*Math.log1p(.36*v/40)}function speedFor(d){let lo=0,hi=2400;for(let k=0;k<24;k++){let m=(lo+hi)/2;if(rollDistance(m)<d)lo=m;else hi=m}return hi}function plan(s){if(s.break)return{angle:0,power:1150};let cue=s.balls[0],t=target(s),choices=s.balls.filter(b=>!b.off&&b.n&&(t===8?b.n===8:t?group(b.n)===t:b.n!==8)),best=null,bestScore=-Infinity;for(const b of choices)for(const[px,py]of POCKETS){let d=Math.hypot(px-b.x,py-b.y),nx=(px-b.x)/d,ny=(py-b.y)/d,ghost={x:b.x-nx*R*2,y:b.y-ny*R*2};if(ghost.x<R||ghost.x>W-R||ghost.y<R||ghost.y>H-R)continue;let dc=Math.hypot(ghost.x-cue.x,ghost.y-cue.y),dot=((ghost.x-cue.x)*nx+(ghost.y-cue.y)*ny)/dc;if(dot<.25)continue;let blockers=s.balls.filter(a=>!a.off&&a.n!==0&&a.n!==b.n);if(blockers.some(a=>distSegment(a,cue,ghost)<R*2.1||distSegment(a,b,{x:px,y:py})<R*2.05))continue;let score=dot*1500-d-dc*.4;if(score>bestScore){bestScore=score;best={angle:Math.atan2(ghost.y-cue.y,ghost.x-cue.x),power:Math.min(1200,Math.max(250,speedFor(dc+rollDistance(speedFor(d+50)/(.98*dot)))))}}}if(!best){let b=choices.sort((a,b)=>Math.hypot(a.x-cue.x,a.y-cue.y)-Math.hypot(b.x-cue.x,b.y-cue.y))[0];best={angle:Math.atan2(b.y-cue.y,b.x-cue.x),power:500}}return best}
const api={W,H,R,POCKETS,rack,group,remaining,target,fresh,shoot,step,resolve,place,plan};root.Pool=api;if(typeof module!=='undefined')module.exports=api})(typeof window!=='undefined'?window:globalThis);
