/* Batch 2 presentation only. Original mode handlers and save formats retained. */
(function(){'use strict';
const base=new URL('.',document.currentScript.src),root=new URL('../',base),path=location.pathname;
const configs={casino:["Captain's Casino",'0.2.0'],solitaire:['Card Table','1.2.0'],farkle:['Farkle','1.5.0'],blockparty:['Block Party','1.5.0'],screwball:['Screwball','4.3.0'],pinball:['Goober Ball','2.2.0'],siege:['Neon Siege','1.4.0'],bridge:['Bridge Works','1.4.0'],hexslide:['Hex Slide','1.3.0'],dice:['Yacht!','1.3.0']};
const key=Object.keys(configs).find(k=>path.includes('/games/'+k+'/'));if(!key)return;
const [title,version]=configs[key],$=id=>document.getElementById(id);
function el(tag,cls,text){let n=document.createElement(tag);if(cls)n.className=cls;if(text)n.textContent=text;return n;}
function setup(){document.documentElement.classList.add('collection-ui','gg-landscape','batch2-ui');document.body.classList.add('collection-page');document.body.dataset.collection=key;
const nav=el('nav','collection-nav');nav.setAttribute('aria-label','Game navigation');const exit=el('button','collection-exit','Exit');exit.id='collectionExit';exit.type='button';exit.onclick=()=>{$('btnHome')?$('btnHome').click():location.href=new URL('index.html',root).href;};
const choose=el('button','collection-choose','Choose Game');choose.id='collectionChoose';choose.type='button';choose.hidden=true;nav.append(exit,el('span','collection-nav-title',title),choose);document.body.append(nav);
if(key==='casino'){choose.hidden=false;choose.onclick=()=>{$('ovHelp')?.classList.remove('show');$('ggMenu')?.classList.remove('show');$('btnLobby').click();};const sync=()=>choose.hidden=$('vLobby').classList.contains('on');new MutationObserver(sync).observe($('vLobby'),{attributes:true,attributeFilter:['class']});sync();}
if(key==='screwball'){choose.hidden=/\/(classic|timber)\.html$/.test(path)===false;choose.onclick=()=>location.href='index.html';}
if(key==='blockparty'){choose.hidden=false;choose.onclick=()=>$('menu').click();const sync=()=>choose.hidden=!!$('colorMode')&&!$('sheet').hidden;new MutationObserver(sync).observe($('panel'),{childList:true});new MutationObserver(sync).observe($('sheet'),{attributes:true,attributeFilter:['hidden']});sync();}
if(key==='pinball'){choose.hidden=false;choose.onclick=()=>{$('ovHelp')?.classList.remove('show');$('btnPause').click();$('machinePicker').scrollIntoView({block:'nearest'});};const sync=()=>choose.hidden=$('ovPause').classList.contains('show');new MutationObserver(sync).observe($('ovPause'),{attributes:true,attributeFilter:['class']});sync();document.querySelectorAll('[data-machine]').forEach(b=>{const im=el('img','machine-art');im.alt='';im.src=new URL('collection-art-b2/'+b.dataset.machine+'.svg',base).href;b.prepend(im);});}
if(key==='siege'){choose.hidden=false;choose.onclick=()=>{$('bPause').click();$('bQuit').focus();};const sync=()=>choose.hidden=!$('menu').classList.contains('hidden');new MutationObserver(sync).observe($('menu'),{attributes:true,attributeFilter:['class']});sync();$('bQuit').textContent='Choose Game · end this battle';}
let selector=null;
if(key==='solitaire'){
 const modes=[['klondike','Klondike','The familiar seven-column classic.'],['spider','Spider','Build complete runs, king to ace.'],['freecell','FreeCell','Plan your moves with four free cells.'],['tripeaks','TriPeaks','Clear three peaks, one card at a time.'],['pyramid','Pyramid','Pair cards that add up to thirteen.']];
 selector=el('section','collection-selector');selector.setAttribute('role','dialog');selector.setAttribute('aria-modal','true');selector.setAttribute('aria-labelledby','collectionTitle');const inner=el('div','collection-lobby'),intro=el('div','collection-intro');intro.append(el('span','collection-eyebrow','FIVE CLASSICS · YOUR TABLE IS READY'));let h=el('h1','',title);h.id='collectionTitle';intro.append(h,el('p','','Choose a game. Pick up where you left off.'));inner.append(intro);let grid=el('div','collection-grid');
 const close=()=>{selector.hidden=true;choose.hidden=false;document.documentElement.classList.remove('collection-open');window.dispatchEvent(new Event('resize'));};
 const open=()=>{selector.hidden=false;choose.hidden=true;document.documentElement.classList.add('collection-open');selector.querySelector('button').focus({preventScroll:true});};
 for(const [id,name,desc]of modes){let b=el('button','collection-card');b.type='button';b.dataset.pick=id;let im=el('img','collection-art');im.alt='';im.src=new URL('collection-art-b2/'+id+'.svg',base).href;let copy=el('span','collection-card-body');copy.append(el('strong','collection-card-title',name),el('span','collection-description',desc),el('span','collection-play','Play / Resume →'));b.append(im,copy);b.onclick=()=>{close();document.querySelectorAll('.overlay.show').forEach(o=>o.classList.remove('show'));$('ggMenu')?.classList.remove('show');document.querySelector('#modes button[data-g="'+id+'"]').click();};grid.append(b);}inner.append(grid,el('p','collection-note','Each game keeps its own saved progress.'));selector.append(inner);document.body.append(selector);choose.onclick=open;open();document.addEventListener('keydown',e=>{if(selector.hidden)return;if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();close();choose.focus();}if(e.key==='Tab'){let a=[exit,...selector.querySelectorAll('button')],i=a.indexOf(document.activeElement);if(e.shiftKey&&i<=0){e.preventDefault();a.at(-1).focus();}else if(!e.shiftKey&&i===a.length-1){e.preventDefault();exit.focus();}}},true);
}
// Keep a build label on static help sheets, below their content.
const help=document.querySelector('#ovHelp .sheet,#ovHelp .card,#how .card');if(help)help.append(el('p','collection-build',title+' · Version '+version));
document.querySelectorAll('#panel,#sheet #card,#dialogContent').forEach(panel=>{const label=()=>{if(!panel.querySelector('.collection-build'))panel.append(el('p','collection-build',title+' · Version '+version));};new MutationObserver(label).observe(panel,{childList:true});label();});
document.querySelectorAll('dialog').forEach(d=>{let row=el('nav','collection-nav collection-dialog-nav'),ex=el('button','collection-exit','Exit'),ch=el('button','collection-choose','Choose Game');ex.onclick=exit.onclick;ch.onclick=()=>location.href='index.html';row.append(ex,el('span','collection-nav-title',title),ch);d.append(row);});
const hideExtraExits=()=>document.querySelectorAll('.overlay button').forEach(b=>{if(/^(All games|Exit to Games|Exit to main menu)$/i.test(b.textContent.trim()))b.hidden=true;});document.querySelectorAll('.overlay').forEach(o=>new MutationObserver(hideExtraExits).observe(o,{childList:true,subtree:true}));hideExtraExits();
window.GoobsCollection={version,isOpen:()=>!!selector&&!selector.hidden};window.dispatchEvent(new Event('resize'));
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
})();
