(()=>{'use strict';function setup(){const root=document.documentElement;root.classList.add('correction-ui');const key=location.pathname.split('/games/')[1]?.split('/')[0],$=id=>document.getElementById(id);const versions={"getout": "0.24.4", "getout2": "1.6.4", "farkle": "1.6.4", "screwball": "4.4.4", "siege": "1.5.4", "bridge": "1.5.4", "hexslide": "1.4.4", "dice": "1.4.5", "mines": "1.4.4", "woodpile": "1.7.0", "zoodoku": "1.12.4", "huddle": "0.4.4", "patchwork": "3.2.4", "spotdiff": "0.6.4", "perch": "1.2.4", "hidden": "1.2.4", "shelf": "2.2.4", "match3": "2.2.4", "barrage": "1.8.4", "bricks": "1.5.4", "digger": "1.4.4", "maze": "1.4.4", "snake": "1.4.4", "triple": "2.2.4", "homerun": "1.9.4", "meanbirds": "1.4.5", "beacon": "0.7.4", "stranded": "1.2.4", "containment": "1.2.4", "golf": "0.7.4", "minigolf": "2.3.4", "skeehop": "1.6.4", "buzz": "2.4.4", "spin": "0.3.4", "topple": "1.11.4"};function refreshBuild(){document.querySelectorAll('.collection-build').forEach(el=>{const t=el.textContent.replace(/Version [0-9.]+/,'Version '+versions[key]).replace(key==='golf'?'Pin High':'\u0000',key==='golf'?'18 Holes':'');if(t!==el.textContent)el.textContent=t;});}refreshBuild();for(const id of ['panel','ovHelp','sheet']){const box=$(id);if(box)new MutationObserver(refreshBuild).observe(box,{childList:true,subtree:true});}const nav=document.querySelector('.collection-nav');if(key==='golf')document.querySelectorAll('.collection-build').forEach(e=>e.textContent=e.textContent.replace('Pin High','18 Holes'));
if(['golf','minigolf'].includes(key)){const list=document.querySelector('#ggMenu .ggmenu-list,#ovMenu .actions');if(list){const go=document.createElement('button');go.className='btn';go.textContent='Golf · Choose game';go.onclick=()=>location.href='../golf/';list.append(go);}}
if(key==='getout'||key==='getout2'){const b=$('btnLane');if(b){const s=b.querySelector('span');if(s)s.textContent='Choose Room';else b.textContent='Choose Room';b.setAttribute('aria-label','Choose Room');}}
if(key==='siege'){for(const [v,desc]of [['tower','Build defenses and hold back the waves.'],['swarm','Build a maze of towers across an open field.']]){const b=document.querySelector('#segMode [data-v="'+v+'"]');if(b&&!b.querySelector('small')){const s=document.createElement('small');s.textContent=desc;b.append(s);}}}
if(['patchwork','spotdiff','hidden'].includes(key)){const b=document.createElement('button');b.className='focus-toggle';b.textContent='⛶ Full screen';b.type='button';b.onclick=()=>{const on=document.body.classList.toggle('focus-view');b.textContent=on?'×':'⛶ Full screen';b.setAttribute('aria-label',on?'Return to regular view':'Full screen puzzle');if(key==='spotdiff'){(on?document.body:document.querySelector('.toolbar')).append(b);}if(key==='hidden')document.body.style.setProperty('--focus-tray',$('tray').getBoundingClientRect().height+'px');window.dispatchEvent(new Event('resize'));};if(key==='spotdiff'){const bar=document.querySelector('.toolbar');bar.append(b);if(nav)bar.append(nav);}else document.body.append(b);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('focus-view'))b.click();});}
const full=document.createElement('button');full.type='button';full.className='fullscreen-return';full.textContent='×';full.setAttribute('aria-label','Leave full screen');full.hidden=true;document.body.append(full);full.onclick=()=>{if(document.exitFullscreen)document.exitFullscreen();else document.webkitExitFullscreen?.();};const syncFull=()=>{const target=document.fullscreenElement||document.webkitFullscreenElement;full.hidden=!target;if(target){target.append(full);if(nav)target.append(nav);}else{document.body.append(full);if(nav)document.body.append(nav);}window.dispatchEvent(new Event('resize'));};document.addEventListener('fullscreenchange',syncFull);document.addEventListener('webkitfullscreenchange',syncFull);
if(key==='stranded'){const btn=document.createElement('button');btn.className='focus-toggle';btn.textContent='⛶ Full screen';btn.onclick=async()=>{const frame=$('frame');try{if(frame.requestFullscreen)await frame.requestFullscreen();else if(frame.webkitRequestFullscreen)frame.webkitRequestFullscreen();else{document.body.classList.toggle('stranded-expanded');btn.textContent=document.body.classList.contains('stranded-expanded')?'× Return':'⛶ Full screen';}}catch{btn.textContent='Full screen unavailable';}};document.body.append(btn);}

window.dispatchEvent(new Event('resize'));}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();})();
