/* Layout-only completion pass. Existing handlers own gameplay and saved state.
   Preserve Roll Call, Garden Swap, Double Take and all pause-only exceptions. */
(function(){'use strict';var key=(location.pathname.split('/games/')[1]||'').split('/')[0],root=document.documentElement;
var oldTargets={farkle:'#app footer',huddle:'#controls',spin:'.topbtns',barrage:'.toolbar',hexslide:'footer',mines:'.toolbar',screwball:'.collection-lobby',bricks:'.toolbar',snake:'.topbtns',topple:'.hudr',maze:'.topbtns'};
function visible(e){return e&&e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden'}
window.GoobsLayoutNavigation=function(o){var target=oldTargets[o.key];if(!target)return false;var dock=o.dock,body=o.body;body.classList.add('finished-inline');root.style.setProperty('--bottom-nav-space','0px');
function sync(){var full=document.fullscreenElement||document.webkitFullscreenElement,dialogs=Array.from(document.querySelectorAll('dialog[open],.overlay.show,#sheet:not([hidden]),#modal:not([hidden])')).filter(visible),modal=dialogs[dialogs.length-1];var home=document.querySelector(target);if(o.key==='huddle'&&home&&!visible(home))home=document.querySelector('.donebar')||home;if(home&&!visible(home)&&!modal&&o.key!=='screwball'){var fallback=document.getElementById('finishGameActions');if(!fallback){fallback=document.createElement('div');fallback.id='finishGameActions';fallback.className='finished-controls';(document.querySelector('.app,#app')||body).appendChild(fallback)}home=fallback;}if(o.key==='screwball')home=document.querySelector('.collection-selector:not([hidden]) .collection-lobby')||document.querySelector('.collection-main')||document.querySelector('.tools,.toolbar')||home;var dest=modal?(modal.querySelector('.card,.sheet,#panel')||modal):full&&!full.contains(home)?full:home;if(!dest)return;dock.classList.toggle('finished-menu',!!modal||dest.matches('.collection-lobby,.collection-main'));if(o.key==='maze'&&dest===home){var sound=document.getElementById('btnSound');if(sound&&sound.parentNode===dest&&dock.previousSibling!==sound)dest.insertBefore(dock,sound.nextSibling)}else if(dock.parentNode!==dest){if(modal||dest.matches('.collection-lobby,.collection-main'))dest.insertBefore(dock,dest.firstChild);else dest.appendChild(dock)}if(!modal&&!dest.matches('.collection-lobby,.collection-main'))dest.classList.add('finished-controls');if(o.key==='farkle'&&home)home.removeAttribute('aria-hidden')}
var queued=false;function schedule(){if(queued)return;queued=true;requestAnimationFrame(function(){queued=false;sync()})}new MutationObserver(function(r){if(r.some(function(x){return x.type==='attributes'||Array.from(x.addedNodes).some(function(n){return n.nodeType===1&&n!==dock})}))schedule()}).observe(body,{subtree:true,childList:true,attributes:true,attributeFilter:['open','hidden','class']});window.addEventListener('resize',schedule);document.addEventListener('fullscreenchange',schedule);document.addEventListener('webkitfullscreenchange',schedule);sync();return true};
function setup(){root.classList.add('layout-finish');document.body.setAttribute('data-layout-game',key);
// Keep entry prompts escapable without committing a recovery or starting-level choice.
var prompts={zoodoku:'#ovStart .card',homerun:'#ovRecovery .recovery-card',bridge:'#sheet #panel,#sheet #card,#modal #panel,#modal .card'};
function promptExits(){if(!prompts[key])return;document.querySelectorAll(prompts[key]).forEach(function(panel){if(panel.querySelector('.entry-exit'))return;var a=document.createElement('a');a.className='entry-exit';a.textContent='Exit';a.href=new URL('../../index.html',location.href).href;panel.insertBefore(a,panel.firstChild)})}
promptExits();if(prompts[key])new MutationObserver(promptExits).observe(document.body,{childList:true,subtree:true});
if(key==='trivia'){var hud=document.querySelector('.qchud'),top=document.querySelector('.top');if(hud&&top)top.insertBefore(hud,top.firstChild)}
if(key==='pegs'){var h=document.getElementById('tHelp');if(h)h.classList.add('finish-duplicate-help')}
if(key==='containment'||key==='stranded'){var lp=document.getElementById('lobbyPause');if(lp)lp.style.zIndex='100';}
if(key==='farkle'){
 var dice=document.getElementById('dice'),table=document.getElementById('table');function sizeDice(){if(!dice||!table)return;if(!window.CSS||!CSS.supports('height','100dvh'))document.getElementById('app').style.setProperty('height',innerHeight+'px','important');var short=innerHeight<=480,cols=short?6:3,rows=short?1:2,gap=short?8:12;var size=Math.floor(Math.max(24,Math.min(short?64:82,(table.clientWidth-34-gap*(cols-1))/cols,(table.clientHeight-(short?88:100)-gap*(rows-1))/rows)));dice.style.gridTemplateColumns='repeat('+cols+','+size+'px)';dice.style.gridTemplateRows='repeat('+rows+','+size+'px)';dice.style.gap=gap+'px'}window.addEventListener('resize',sizeDice);if(window.ResizeObserver)new ResizeObserver(sizeDice).observe(table);sizeDice();
}
window.dispatchEvent(new Event('resize'));
}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(setup,0)});else setup();})();
