/* Tactile workshop materials. The puzzle geometry and hit areas remain owned by Knotty. */
(function(){'use strict';
var A=KA,photos=[],wood,ropePhoto,tiles={},patterns=new WeakMap(),active=0;
A.SCENES=[{name:'The Sail Loft'},{name:'Lakeside Workshop'},{name:'Lantern Room'}];
function load(src){return new Promise(function(ok,no){var im=new Image();im.onload=function(){ok(im)};im.onerror=function(){no(Error('Unable to load '+src))};im.src=src})}
var jobs=A.SCENES.map(function(_,i){return load('assets/workshop-'+i+'.webp').then(function(im){photos[i]=im})});jobs.push(load('assets/maple.webp').then(function(im){wood=im}));
jobs.push(load('assets/cotton-rope.png').then(function(im){ropePhoto=im}));
var bases=['#bd3945','#346bb7','#d6ac35','#458452','#815ca8','#cf783b','#288e91','#bf648e','#855738','#e4ddca','#354457','#91ac43'];
bases.forEach(function(c,i){A.COLORS[i][0]=c});
function path(c,p,dx,dy){c.beginPath();c.moveTo(p[0][0]+(dx||0),p[0][1]+(dy||0));for(var i=1;i<p.length;i++)c.lineTo(p[i][0]+(dx||0),p[i][1]+(dy||0))}
function rr(c,x,y,w,h,r){A.roundRect(c,x,y,w,h,Math.min(r,14))}
function disk(c,x,y,r,col){c.fillStyle=col;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill()}
function texture(id){if(tiles[id])return tiles[id];var cv=document.createElement('canvas');cv.width=ropePhoto.width;cv.height=ropePhoto.height;var c=cv.getContext('2d');c.drawImage(ropePhoto,0,0);c.globalCompositeOperation='multiply';c.fillStyle=bases[id];c.fillRect(0,0,cv.width,cv.height);c.globalCompositeOperation='destination-in';c.drawImage(ropePhoto,0,0);return tiles[id]=cv}
A.rope=function(c,p,w,id,o){if(p.length<2)return;o=o||{};id=id%12;c.save();c.lineCap='round';c.lineJoin='round';c.globalAlpha=o.alpha===undefined?1:o.alpha;
 if(o.shadow!==false){c.strokeStyle='rgba(15,9,5,.28)';c.lineWidth=w*1.15;path(c,p,w*.07,w*.27);c.stroke();c.strokeStyle='rgba(15,9,5,.17)';c.lineWidth=w*1.35;path(c,p,w*.09,w*.36);c.stroke()}
 if(o.free&&o.glow){c.strokeStyle='rgba(244,226,170,'+(o.glow*.45)+')';c.lineWidth=w*1.6;path(c,p);c.stroke()}
 c.strokeStyle=A.COLORS[id][1];c.lineWidth=w*.82;path(c,p);c.stroke();
 var pc=patterns.get(c);if(!pc){pc={};patterns.set(c,pc)}var pat=pc[id]||(pc[id]=c.createPattern(texture(id),'repeat')),acc=0;
 for(var i=1;i<p.length;i++){var a=p[i-1],b=p[i],dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy);if(len<.01)continue;c.save();c.translate(a[0],a[1]);c.rotate(Math.atan2(dy,dx));pat.setTransform(new DOMMatrix().translate(-acc,-w/2).scale(w/ropePhoto.height,w/ropePhoto.height));c.fillStyle=pat;c.fillRect(-.25,-w/2,len+.5,w);c.restore();acc+=len}
 c.restore();};
// Reuse rasterized ropes while their geometry is unchanged. Moving ends redraw only their rope.
var rawRope=A.rope,ropeCaches=new WeakMap();
A.rope=function(c,p,w,id,o){o=o||{};var d=Math.min(3,Math.abs(c.getTransform().a)||1),key=w.toFixed(2)+':'+d+':'+(o.alpha===undefined?1:o.alpha)+':'+(o.shadow!==false)+':'+Math.round((o.free?o.glow||0:0)*5)+':'+p.map(function(v){return Math.round(v[0]*2)+','+Math.round(v[1]*2)}).join(';'),cache=ropeCaches.get(c);if(!cache){cache={};ropeCaches.set(c,cache)}var hit=cache[id];if(!hit||hit.key!==key){var xs=p.map(function(v){return v[0]}),ys=p.map(function(v){return v[1]}),left=Math.floor(Math.min.apply(null,xs)-w*2),top=Math.floor(Math.min.apply(null,ys)-w*2),ww=Math.ceil(Math.max.apply(null,xs)-left+w*2),hh=Math.ceil(Math.max.apply(null,ys)-top+w*2),im=hit?hit.im:document.createElement('canvas');im.width=Math.ceil(ww*d);im.height=Math.ceil(hh*d);var cc=im.getContext('2d');cc.setTransform(d,0,0,d,-left*d,-top*d);rawRope(cc,p,w,id,o);hit=cache[id]={key:key,im:im,x:left,y:top,w:ww,h:hh}}c.drawImage(hit.im,hit.x,hit.y,hit.w,hit.h)};
A.panel=function(c,x,y,w,h,r,dark,skin){c.save();r=Math.min(14,r);c.shadowColor='rgba(0,0,0,.55)';c.shadowBlur=18;c.shadowOffsetY=12;c.fillStyle='#503723';rr(c,x,y+5,w,h,r);c.fill();c.shadowColor='transparent';c.fillStyle='#916947';rr(c,x,y,w,h,r);c.fill();c.save();rr(c,x+4,y+4,w-8,h-8,r-3);c.clip();if(wood)c.drawImage(wood,x+4,y+4,w-8,h-8);else{c.fillStyle='#c7ab80';c.fillRect(x,y,w,h)}var g=c.createLinearGradient(x,y,x+w,y+h);g.addColorStop(0,'rgba(255,243,206,.15)');g.addColorStop(.6,'rgba(97,66,28,.03)');g.addColorStop(1,'rgba(60,34,12,.19)');c.fillStyle=g;c.fillRect(x,y,w,h);if(dark){c.fillStyle='rgba(22,17,13,.17)';c.fillRect(x,y,w,h)}c.restore();c.lineWidth=1;c.strokeStyle='rgba(255,229,172,.65)';rr(c,x+1,y+1,w-2,h-2,r);c.stroke();c.strokeStyle='rgba(64,38,17,.32)';rr(c,x+8,y+8,w-16,h-16,r-4);c.stroke();
 [[x+13,y+13],[x+w-13,y+13],[x+13,y+h-13],[x+w-13,y+h-13]].forEach(function(p){disk(c,p[0],p[1]+.7,3.7,'#654c2d');var g=c.createLinearGradient(p[0]-3,p[1]-3,p[0]+3,p[1]+3);g.addColorStop(0,'#eedaa8');g.addColorStop(.5,'#ab9060');g.addColorStop(1,'#665130');disk(c,p[0],p[1],3.2,g);c.strokeStyle='#5d492d';c.lineWidth=.7;c.beginPath();c.moveTo(p[0]-1.5,p[1]+1);c.lineTo(p[0]+1.5,p[1]-1);c.stroke()});c.restore()};
A.peg=function(c,x,y,r){c.save();disk(c,x,y+.8,r*1.18,'rgba(255,241,200,.4)');var g=c.createLinearGradient(x,y-r,x,y+r);g.addColorStop(0,'#70562f');g.addColorStop(.45,'#c9ad72');g.addColorStop(1,'#e1c997');disk(c,x,y,r*1.05,g);disk(c,x,y,r*.75,'#392b1d');var sh=c.createRadialGradient(x,y+r*.4,0,x,y,r*.75);sh.addColorStop(0,'#786047');sh.addColorStop(1,'#1b1510');disk(c,x,y,r*.70,sh);c.restore()};
A.knob=function(c,x,y,r,id,o){o=o||{};id=id%12;r*=(o.pop||1)*(1+.12*(o.lift||0));c.save();if(o.dim)c.globalAlpha=.5;c.shadowColor='rgba(18,10,4,.5)';c.shadowBlur=r*.3;c.shadowOffsetY=r*(.20+.3*(o.lift||0));disk(c,x,y,r*.99,'#564630');c.shadowColor='transparent';var edge=c.createLinearGradient(x-r,y-r,x+r,y+r);edge.addColorStop(0,'#efe0b8');edge.addColorStop(.3,'#ad9260');edge.addColorStop(.6,'#74603e');edge.addColorStop(1,'#ccb183');disk(c,x,y,r*.97,edge);
 // Dyed rope wound around a low metal spool, instead of a plastic ball.
 for(var q=0;q<2;q++){var pts=[],rad=r*(.81-q*.18);for(var j=0;j<=40;j++){var a=j*Math.PI/20;pts.push([x+Math.cos(a)*rad,y+Math.sin(a)*rad])}A.rope(c,pts,r*.22,id,{shadow:false})}
 var g=c.createLinearGradient(x-r*.4,y-r*.4,x+r*.4,y+r*.4);g.addColorStop(0,'#eadbbc');g.addColorStop(.4,'#b9a88a');g.addColorStop(1,'#80725c');disk(c,x,y,r*.42,g);c.strokeStyle='rgba(53,39,22,.4)';c.lineWidth=.8;c.beginPath();c.arc(x,y,r*.42,0,Math.PI*2);c.stroke();
 if(o.pinned){c.fillStyle='#5a5144';c.beginPath();for(var h=0;h<6;h++){var a=h*Math.PI/3;c.lineTo(x+Math.cos(a)*r*.28,y+Math.sin(a)*r*.28)}c.closePath();c.fill();c.strokeStyle='#eee1c9';c.lineWidth=r*.05;c.beginPath();c.moveTo(x-r*.16,y);c.lineTo(x+r*.16,y);c.stroke()}else if(o.sym)A.symbol(c,id,x,y,r*.39,'#40392f');else{disk(c,x,y,r*.10,'#5a4d39');disk(c,x-r*.025,y-r*.025,r*.045,'#eadfc6')}
 if(o.pinned&&o.sym)A.symbol(c,id,x+r*.69,y-r*.69,r*.26,'#fff7de');if(o.lift||o.glow){c.strokeStyle='rgba(255,235,174,.85)';c.lineWidth=1.4;c.beginPath();c.arc(x,y,r*1.08,0,Math.PI*2);c.stroke()}c.restore()};
// Cache the detailed wound grips; only their position and lift animate each frame.
var rawKnob=A.knob,grips={};
A.knob=function(c,x,y,r,id,o){o=o||{};var key=(id%12)+':'+!!o.pinned+':'+!!o.sym,im=grips[key];if(!im){im=document.createElement('canvas');im.width=im.height=256;rawKnob(im.getContext('2d'),128,128,96,id,{pinned:o.pinned,sym:o.sym});grips[key]=im}r*=(o.pop||1)*(1+.12*(o.lift||0));c.save();if(o.dim)c.globalAlpha=.5;if(o.lift){c.fillStyle='rgba(25,16,8,.18)';c.beginPath();c.ellipse(x,y+r*.55,r,r*.75,0,0,Math.PI*2);c.fill()}var sz=r*256/96;c.drawImage(im,x-sz/2,y-sz/2,sz,sz);if(o.lift||o.glow){c.strokeStyle='rgba(255,235,174,.85)';c.lineWidth=1.4;c.beginPath();c.arc(x,y,r*1.08,0,Math.PI*2);c.stroke()}c.restore()};
A.scene=function(c,w,h,i,theme,skin){active=i%3;var im=photos[active];c.save();if(im){var s=Math.max(w/im.width,h/im.height);c.drawImage(im,(w-im.width*s)/2,(h-im.height*s)/2,im.width*s,im.height*s)}else{c.fillStyle='#302b23';c.fillRect(0,0,w,h)}var v=c.createRadialGradient(w*.5,h*.45,w*.12,w*.5,h*.5,Math.max(w,h)*.73);v.addColorStop(0,'rgba(12,10,7,0)');v.addColorStop(1,'rgba(12,10,7,.45)');c.fillStyle=v;c.fillRect(0,0,w,h);if(theme==='dark'||skin){c.fillStyle=skin?'rgba(41,17,7,.23)':'rgba(7,14,25,.28)';c.fillRect(0,0,w,h)}var top=window.__knotty?__knotty.L.top:150;if(top>145){c.textAlign='center';c.fillStyle='#f7ead2';c.shadowColor='rgba(0,0,0,.7)';c.shadowBlur=6;c.font='32px Georgia,serif';c.fillText('Knotty',w/2,99);c.font='10px system-ui,sans-serif';c.letterSpacing='2px';c.fillText(A.SCENES[active].name.toUpperCase(),w/2,120)}c.restore()};
A.fxInit=function(){};A.fxDraw=function(){};
window.KnottyWorkshop={ready:Promise.all(jobs)};
})();
