(()=>{'use strict';const B=BP,$=id=>document.getElementById(id),store=Goobs.store('blockparty'),canvas=$('board'),ctx=canvas.getContext('2d'),colors=['#f17459','#429fdf','#efba3e','#38b69d','#9b77d9','#e877a8'],darks=['#bc514e','#387db9','#c38d29','#348977','#7356a7','#b25782'],names=['coral','blue','gold','mint','violet','pink'],symbols=['●','◆','▲','■','★','✚'];let mode='color',s=null,trail=[],undos=[],moves=0,remaining=180,timed=false,started=false,complete=false,selected=null,hintMove=null,drag=null,busy=false,sound=store.get('sound',true),clockOn=store.get('clock',true),meta=store.get('meta',{color:1,shape:1,best:{}})||{color:1,shape:1,best:{}},W=1,H=1,cell=1,ox=0,oy=0,effects=[],particles=[],lastTime=performance.now(),saveAt=0,audio,lastFocus=null;meta.best=meta.best||{};if(meta.revision!==3){for(const m of ['color','shape'])for(let l=11;l<=18;l++)delete meta.best[m+l];meta.revision=3;store.set('meta',meta);}
function active(){return s&&!complete&&!busy&&$('sheet').hidden;}function bankSave(){if(!s)return;store.set(mode+'.save',{version:3,s,trail,undos:undos.slice(-60),moves,remaining,timed,started,complete,clockSetting:clockOn});store.set('meta',meta);}function beep(exit=false){if(!sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.setValueAtTime(exit?480:245,audio.currentTime);o.frequency.exponentialRampToValueAtTime(exit?800:300,audio.currentTime+.12);g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.15);o.start();o.stop(audio.currentTime+.16);}catch(e){}}
function show(html,home=false){if(drag)finishDrag();lastFocus=document.activeElement;$('panel').className=home?'home':'';$('panel').innerHTML=html;$('sheet').hidden=false;$('panel').querySelector('button,a,input')?.focus();}function close(){$('sheet').hidden=true;lastTime=performance.now();canvas.focus();resize();}
function openMenu(){bankSave();show('<div class="eyebrow">GOOBS PUZZLES · TWO WAYS OUT</div><h1 id="dialogTitle">BLOCK <span>PARTY</span></h1><p class="intro">A little space. A clever shuffle. A colorful way out.</p><div class="modes"><button id="colorMode" class="modeCard"><span class="tag">OPTIONAL CLOCK</span><span class="miniBlocks" aria-hidden="true"><i></i><i></i><i></i></span><strong>Color Rush</strong><small>Match the exits.<br>Level '+(meta.color||1)+' · 48 + endless</small></button><button id="shapeMode" class="modeCard shapeCard"><span class="tag">ALWAYS UNTIMED</span><span class="miniBlocks" aria-hidden="true"><i></i><i></i><i></i></span><strong>Shape Escape</strong><small>Untangle every shape.<br>Level '+(meta.shape||1)+' · 48 + endless</small></button></div><div class="menuOptions"><label><input id="clockOption" type="checkbox" '+(clockOn?'checked':'')+'>Color Rush clock</label><button id="levels">Choose level</button></div><a class="exit" href="../../index.html">Exit to Games</a>',true);$('colorMode').onclick=()=>loadMode('color');$('shapeMode').onclick=()=>loadMode('shape');$('clockOption').onchange=()=>{clockOn=$('clockOption').checked;store.set('clock',clockOn);};$('levels').onclick=()=>levelMenu(mode,0);}
function loadMode(m){mode=m;const save=store.get(m+'.save',null);if((save?.version===3||save?.version===2&&(save.s?.level<11||save.s?.level>18))&&save.s?.mode===m&&B.valid(save.s)&&!save.complete){s=save.s;trail=save.trail||[];undos=save.undos||[];moves=save.moves||0;remaining=save.remaining;timed=m==='color'&&(save.clockSetting!==clockOn?clockOn:save.timed);started=save.started;complete=false;if(timed&&remaining<=0)remaining=timeLimit(s);selected=null;hintMove=null;effects=[];particles=[];applyMode();close();hud();message('Resumed. Drag blocks to matching exits.');}else start(m,(save&&!save.complete?save.s?.level:0)||meta[m]||1);}
function timeLimit(x){return Math.max(150,Math.min(360,110+x.pieces.length*15+x.solution.length*1.5));}
function start(m,level){mode=m;busy=true;s=B.copy(BP_LEVELS[m][level-1]||B.generate(m,level));trail=[];undos=[];moves=0;timed=m==='color'&&clockOn;remaining=timeLimit(s);started=false;complete=false;selected=null;hintMove=null;effects=[];particles=[];busy=false;applyMode();close();dockAll();bankSave();hud();message(level===1?'Drag a block toward the exit with its color & symbol.':level===7?'Arrow-marked pieces move only along their rail.':'Make room, then slide each block out.');if(s.pieces.every(p=>p.gone))win();}
function applyMode(){document.body.classList.toggle('shape',mode==='shape');document.querySelector('meta[name="theme-color"]').content=mode==='shape'?'#a6e9df':'#ffb79b';}
function levelMenu(m,page){show('<button id="back" class="close" aria-label="Back to menu">×</button><div class="eyebrow">YOUR PUZZLE COLLECTION</div><h2 id="dialogTitle">'+(m==='color'?'Color Rush':'Shape Escape')+'</h2><div class="menuOptions"><button id="switchMode">'+(m==='color'?'Show Shape Escape':'Show Color Rush')+'</button><span>48 boards + endless</span></div><div class="levelGrid">'+Array.from({length:12},(_,i)=>{const n=page*12+i+1,b=meta.best[m+n];return '<button data-level="'+n+'" class="'+(b?'done ':'')+((meta[m]||1)===n?'current':'')+'">'+n+(b?'<small>✓ '+b.moves+' moves</small>':'')+'</button>';}).join('')+'</div><div class="pages"><button id="prev" '+(page===0?'disabled':'')+'>←</button><span>'+(page+1)+' / 4</span><button id="nextPage" '+(page===3?'disabled':'')+'>→</button></div><div class="buttons"><button id="endless">Endless · board '+Math.max(49,meta[m]||49)+'</button></div>');$('back').onclick=openMenu;$('switchMode').onclick=()=>levelMenu(m==='color'?'shape':'color',0);$('prev').onclick=()=>levelMenu(m,page-1);$('nextPage').onclick=()=>levelMenu(m,page+1);$('endless').onclick=()=>start(m,Math.max(49,meta[m]||49));$('panel').querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>start(m,+b.dataset.level));}
function help(){show('<button id="back" class="close" aria-label="Close help">×</button><div class="eyebrow">MAKE ROOM FOR A GOOD IDEA</div><h2 id="dialogTitle">Slide your way out.</h2><div class="helpRows"><div><b>Drag any piece</b> up, down, left, or right. It snaps to the grid and cannot pass through other pieces. You can change direction during a drag.</div><div><b>Match the exit.</b> Each block and gate share a color and symbol. Line up the whole piece with the opening, and it exits automatically on contact. You may need to move another block first.</div><div><b>No rotation.</b> L, T, and zigzag pieces keep their shape. Blocks marked ↔ or ↕ move only in that direction.</div><div><b>Two modes.</b> Color Rush adds an optional clock, starting with your first move. Shape Escape is always untimed and features more intricate pieces.</div><div><b>Take a hint.</b> Highlight a suggested move whenever you like. Undo restores a whole drag. Restart is always free.</div><div><b>Alternative controls:</b> tap a block or choose it below the board, then use the arrow buttons or keyboard arrows. Escape opens the menu.</div></div><div class="buttons"><button id="ready" class="primary">Got it</button></div>');$('back').onclick=close;$('ready').onclick=close;}
function message(t){$('message').textContent=t;}
function hud(){const x=s||BP_LEVELS.color[0];$('modeLabel').textContent=(mode==='color'?'COLOR RUSH':'SHAPE ESCAPE')+' · '+x.n+'×'+x.n;$('level').textContent=(x.level>48?'Endless ':'Level ')+x.level;$('level').title=x.n+' × '+x.n+' board · '+x.pieces.length+' blocks';$('cleared').textContent=x.pieces.filter(p=>p.gone).length+' / '+x.pieces.length;$('moveCount').textContent=moves+' move'+(moves===1?'':'s');$('clockLabel').textContent=timed?(started?'TIME LEFT':'STARTS ON FIRST MOVE'):'TAKE YOUR TIME';$('clock').textContent=timed?Math.max(0,Math.ceil(remaining/60)-1)+':'+String(Math.max(0,Math.ceil(remaining))%60).padStart(2,'0'):'∞';if(timed){const secs=Math.max(0,Math.ceil(remaining));$('clock').textContent=Math.floor(secs/60)+':'+String(secs%60).padStart(2,'0');}$('clock').classList.toggle('urgent',timed&&remaining<30);$('sound').textContent='Sound '+(sound?'on':'off');$('undo').disabled=!undos.length||complete;$('hint').disabled=!s||complete;$('pieceSelect').innerHTML='<option value="">Select block…</option>'+x.pieces.filter(p=>!p.gone).map(p=>'<option value="'+p.id+'">'+symbols[p.color]+' '+names[p.color]+' '+(p.id+1)+(p.axis?' '+(p.axis==='h'?'↔':'↕'):'')+'</option>').join('');$('pieceSelect').value=selected===null?'':String(selected);}
function win(){complete=true;const k=mode+s.level,old=meta.best[k];if(!old||moves<old.moves)meta.best[k]={moves,timed};meta[mode]=Math.max(meta[mode]||1,s.level+1);bankSave();setTimeout(()=>{if(!complete)return;show('<div class="eyebrow">EVERY BLOCK FOUND ITS WAY</div><div class="winArt">✦ ✧ ✦</div><h2 id="dialogTitle">Beautifully untangled.</h2><div class="resultStats"><div><strong>'+moves+'</strong>moves</div><div><strong>'+s.pieces.length+'</strong>blocks freed</div><div><strong>'+s.level+'</strong>level complete</div></div><div class="buttons"><button class="primary" id="nextLevel">'+(s.level===48?'Enter endless play':'Next level')+' →</button><button id="again">Play this board again</button><button id="home">Choose a mode</button></div><a class="exit" href="../../index.html">Exit to Games</a>');$('nextLevel').onclick=()=>start(mode,s.level+1);$('again').onclick=()=>start(mode,s.level);$('home').onclick=openMenu;},350);}
function timeout(){if(complete)return;if(drag)finishDrag();if(complete)return;bankSave();show('<div class="eyebrow">NO LIVES TO LOSE</div><h2 id="dialogTitle">Take your time.</h2><p>The clock ran out. Keep solving this board without a timer, or try it again.</p><div class="buttons"><button id="continue" class="primary">Keep playing · no clock</button><button id="retry">Try again</button><button id="home">Game menu</button></div>');$('continue').onclick=()=>{timed=false;close();hud();bankSave();};$('retry').onclick=()=>start(mode,s.level);$('home').onclick=openMenu;}
function snapshot(){return {pieces:B.copy(s.pieces),trailLen:trail.length,moves};}
function burst(p,dx,dy){effects.push({p:B.copy(p),dx,dy,age:0});const z=B.size(p);for(let i=0;i<12;i++)particles.push({x:p.x+z.w/2,y:p.y+z.h/2,vx:(Math.random()-.5)*3+dx*2,vy:(Math.random()-.5)*3+dy*2,c:colors[p.color],age:0});}
function move(id,dx,dy){const p=s.pieces.find(p=>p.id===id),before=B.copy(p),a=B.step(s,id,dx,dy);if(!a)return null;trail.push(a);started=true;hintMove=null;if(a.exit){burst(before,dx,dy);selected=null;beep(true);return a;}
// A moved piece docks as soon as its entire profile meets a matching gate.
for(const [ex,ey] of B.dirs){const z=B.size(p),touch=ex===-1?p.x===0:ex===1?p.x+z.w===s.n:ey===-1?p.y===0:p.y+z.h===s.n;if(!touch||!B.gateFor(s,p,ex,ey))continue;const docked=B.copy(p),out=B.step(s,id,ex,ey);if(out){trail.push(out);burst(docked,ex,ey);selected=null;beep(true);return {...a,exit:true};}}
return a;}

function dockAll(){let changed=true;while(changed){changed=false;for(const p of s.pieces){if(p.gone)continue;for(const [dx,dy] of B.dirs){const z=B.size(p),touch=dx===-1?p.x===0:dx===1?p.x+z.w===s.n:dy===-1?p.y===0:p.y+z.h===s.n;if(!touch||!B.gateFor(s,p,dx,dy))continue;const before=B.copy(p),out=B.step(s,p.id,dx,dy);if(out){trail.push(out);burst(before,dx,dy);if(selected===p.id)selected=null;changed=true;break;}}}}}
function commit(before){dockAll();if(B.key({pieces:before.pieces})===B.key(s))return;undos.push(before);if(undos.length>60)undos.shift();moves++;beep();hud();bankSave();if(s.pieces.every(p=>p.gone))win();else message('Make room, then match the exit.');}
function nudge(dx,dy){if(!active()||selected===null)return;const before=snapshot(),a=move(selected,dx,dy);if(a)commit(before);else{const p=s.pieces.find(p=>p.id===selected);message(p.axis?'This piece follows its arrow rail.':'Blocked. Make space or line up with a matching gate.');}}
function undo(){if(!active()||!undos.length)return;const u=undos.pop();s.pieces=u.pieces;trail.length=u.trailLen;moves=u.moves;selected=null;hintMove=null;effects=[];particles=[];bankSave();hud();message('Last drag undone.');}
function hint(){if(!active())return;try{const route=B.plan(s,trail),a=route[0];if(!a)return;selected=a.id;let count=1;while(count<route.length&&route[count].id===a.id&&route[count].dx===a.dx&&route[count].dy===a.dy)count++;hintMove={...a,count};const p=s.pieces.find(p=>p.id===a.id);hud();message('Hint: '+names[p.color]+' '+(p.id+1)+' '+(a.dx===1?'right':a.dx===-1?'left':a.dy===1?'down':'up')+' '+count+' space'+(count===1?'':'s')+'.');}catch(e){message('Undo your last move to return to the previous position.');}}
function restart(){if(!s)return;show('<h2 id="dialogTitle">Restart this board?</h2><p>Your other levels and best scores are saved.</p><div class="buttons"><button id="yes" class="primary">Restart level '+s.level+'</button><button id="no">Keep playing</button></div>');$('yes').onclick=()=>start(mode,s.level);$('no').onclick=close;}
function point(e){const r=canvas.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};}
function hit(x,y){const gx=(x-ox)/cell,gy=(y-oy)/cell;let p=s.pieces.slice().reverse().find(p=>!p.gone&&p.cells.some(([a,b])=>gx>=p.x+a&&gx<p.x+a+1&&gy>=p.y+b&&gy<p.y+b+1));if(p)return p;let near=null,dist=.16;for(const p of s.pieces)if(!p.gone)for(const [a,b] of p.cells){const d=Math.hypot(Math.max(p.x+a-gx,0,gx-p.x-a-1),Math.max(p.y+b-gy,0,gy-p.y-b-1));if(d<dist){near=p;dist=d;}}return near;}
canvas.addEventListener('pointerdown',e=>{if(!active()||drag||e.button>0)return;const pt=point(e),p=hit(pt.x,pt.y);if(!p)return;e.preventDefault();selected=p.id;hintMove=null;drag={id:p.id,pointer:e.pointerId,x:pt.x,y:pt.y,before:snapshot()};canvas.setPointerCapture(e.pointerId);hud();message(names[p.color]+' '+(p.id+1)+(p.axis?' · '+(p.axis==='h'?'horizontal':'vertical')+' only':' · drag to a matching exit'));});
canvas.addEventListener('pointermove',e=>{if(!drag||drag.pointer!==e.pointerId||!active())return;e.preventDefault();const pt=point(e);for(let k=0;k<20&&drag;k++){const dx=pt.x-drag.x,dy=pt.y-drag.y,ax=Math.abs(dx),ay=Math.abs(dy);if(Math.max(ax,ay)<cell*.58)break;let sx=ax>=ay?Math.sign(dx):0,sy=ay>ax?Math.sign(dy):0;const a=move(drag.id,sx,sy);if(a){drag.x+=sx*cell;drag.y+=sy*cell;if(a.exit){finishDrag();break;}}else{if(sx)drag.x=pt.x;else drag.y=pt.y;break;}}});
function finishDrag(){if(!drag)return;const d=drag;drag=null;try{canvas.releasePointerCapture(d.pointer);}catch(e){}commit(d.before);}
canvas.addEventListener('pointerup',finishDrag);canvas.addEventListener('pointercancel',finishDrag);canvas.addEventListener('lostpointercapture',finishDrag);
$('controlsToggle').onclick=()=>{const on=$('play').classList.toggle('arrowsOpen');$('controlsToggle').setAttribute('aria-expanded',on);};$('pieceSelect').onchange=()=>{selected=$('pieceSelect').value===''?null:+$('pieceSelect').value;hintMove=null;};document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>nudge(...b.dataset.dir.split(',').map(Number)));$('undo').onclick=undo;$('hint').onclick=hint;$('restart').onclick=restart;$('help').onclick=help;$('menu').onclick=openMenu;$('sound').onclick=()=>{sound=!sound;store.set('sound',sound);beep();hud();};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if($('sheet').hidden)openMenu();else if(s&&!complete)close();return;}if(!active()||e.target.tagName==='SELECT')return;const d={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(d){e.preventDefault();nudge(...d);}else if(e.key.toLowerCase()==='h')hint();else if(e.key.toLowerCase()==='z')undo();});
document.addEventListener('visibilitychange',()=>{if(document.hidden){finishDrag();bankSave();}lastTime=performance.now();});window.addEventListener('pagehide',bankSave);
// Original vector rendering: beveled silhouettes, recessed grid, colored exit rails.
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);}
const outlines=new Map();function outline(p){const key=JSON.stringify(p.cells);if(outlines.has(key))return outlines.get(key);const map=new Map();for(const [x,y] of p.cells)for(const [a,b] of [[[x,y],[x+1,y]],[[x+1,y],[x+1,y+1]],[[x+1,y+1],[x,y+1]],[[x,y+1],[x,y]]]){const k=a.join(',')+'>'+b.join(','),rev=b.join(',')+'>'+a.join(',');if(map.has(rev))map.delete(rev);else map.set(k,[a,b]);}const edges=[...map.values()],vertices=[edges[0][0]];let next=edges[0][1];while(next.join(',')!==vertices[0].join(',')){vertices.push(next);const e=edges.find(e=>e[0][0]===next[0]&&e[0][1]===next[1]);next=e[1];}outlines.set(key,vertices);return vertices;}
function silhouette(p,x,y){const v=outline(p),r=.105*cell;ctx.beginPath();for(let i=0;i<v.length;i++){const a=v[(i+v.length-1)%v.length],b=v[i],c=v[(i+1)%v.length],bx=x+b[0]*cell,by=y+b[1]*cell,al=Math.hypot(a[0]-b[0],a[1]-b[1]),cl=Math.hypot(c[0]-b[0],c[1]-b[1]);const ax=bx+(a[0]-b[0])*r/al,ay=by+(a[1]-b[1])*r/al,cx=bx+(c[0]-b[0])*r/cl,cy=by+(c[1]-b[1])*r/cl;if(i===0)ctx.moveTo(ax,ay);else ctx.lineTo(ax,ay);ctx.quadraticCurveTo(bx,by,cx,cy);}ctx.closePath();}
function piece(p,offsetX=0,offsetY=0,alpha=1){const x=ox+(p.x+offsetX)*cell,y=oy+(p.y+offsetY)*cell,z=B.size(p),gap=.045*cell;ctx.save();ctx.globalAlpha=alpha;ctx.translate(x+gap,y+gap);ctx.scale((z.w*cell-2*gap)/(z.w*cell),(z.h*cell-2*gap)/(z.h*cell));const lift=Math.min(8,cell*.15);silhouette(p,0,lift);ctx.fillStyle=darks[p.color];ctx.shadowColor='#102b4850';ctx.shadowBlur=cell*.16;ctx.shadowOffsetY=5;ctx.fill();ctx.shadowColor='transparent';silhouette(p,0,0);const g=ctx.createLinearGradient(0,0,z.w*cell,z.h*cell);g.addColorStop(0,colors[p.color]);g.addColorStop(.65,colors[p.color]);g.addColorStop(1,darks[p.color]);ctx.fillStyle=g;ctx.fill();ctx.lineWidth=1.5;ctx.strokeStyle='#ffffff6b';ctx.stroke();ctx.save();ctx.clip();const gloss=ctx.createLinearGradient(0,0,cell,cell*1.8);gloss.addColorStop(0,'#ffffff25');gloss.addColorStop(.5,'#ffffff00');ctx.fillStyle=gloss;ctx.fillRect(0,0,z.w*cell,z.h*cell);ctx.restore();
// Raised, cylindrical studs on every grid unit: one connected molded brick.
for(const [a,b] of p.cells){const cx=(a+.5)*cell,cy=(b+.47)*cell,r=cell*.255,depth=cell*.065;ctx.beginPath();ctx.ellipse(cx,cy+depth,r,r*.9,0,0,Math.PI*2);ctx.fillStyle=darks[p.color];ctx.shadowColor='#19364c35';ctx.shadowBlur=cell*.06;ctx.shadowOffsetY=2;ctx.fill();ctx.shadowColor='transparent';ctx.beginPath();ctx.ellipse(cx,cy,r,r*.9,0,0,Math.PI*2);const top=ctx.createLinearGradient(cx-r,cy-r,cx+r,cy+r);top.addColorStop(0,'#ffffff');top.addColorStop(.045,colors[p.color]);top.addColorStop(.8,colors[p.color]);top.addColorStop(1,darks[p.color]);ctx.fillStyle=top;ctx.fill();ctx.lineWidth=1;ctx.strokeStyle='#ffffff55';ctx.stroke();ctx.beginPath();ctx.ellipse(cx,cy,r*.83,r*.74,0,Math.PI*1.1,Math.PI*1.8);ctx.strokeStyle='#ffffff50';ctx.stroke();}
if(p.id===selected&&!p.gone){silhouette(p,0,0);ctx.lineWidth=3;ctx.strokeStyle='#fff8cb';ctx.shadowColor='#fff5b6';ctx.shadowBlur=8;ctx.stroke();ctx.shadowBlur=0;}const center=p.cells.reduce((a,c)=>[a[0]+c[0]+.5,a[1]+c[1]+.5],[0,0]).map(n=>n/p.cells.length),label=p.cells.slice().sort((a,b)=>Math.hypot(a[0]+.5-center[0],a[1]+.5-center[1])-Math.hypot(b[0]+.5-center[0],b[1]+.5-center[1]))[0],lx=(label[0]+.5)*cell,ly=(label[1]+.47)*cell;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#ffffffed';ctx.font='800 '+Math.max(11,cell*.24)+'px system-ui';ctx.fillText(p.axis?(p.axis==='h'?'↔':'↕'):symbols[p.color],lx,ly);ctx.font='800 '+Math.max(7,cell*.13)+'px system-ui';ctx.fillStyle='#ffffffc0';ctx.fillText(p.id+1,lx,ly+cell*.36);ctx.restore();}

function resize(){const r=canvas.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1);W=r.width;H=r.height;canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw();}new ResizeObserver(resize).observe($('boardWrap'));
function draw(){ctx.clearRect(0,0,W,H);const q=s||BP_LEVELS.color[0],n=q.n;cell=Math.min(W/(n+.9),H/(n+.9),94);ox=(W-cell*n)/2;oy=(H-cell*n)/2-3;const edge=.28*cell;ctx.save();ctx.shadowColor='#856f6640';ctx.shadowBlur=18;ctx.shadowOffsetY=10;roundRect(ox-edge,oy-edge,cell*n+edge*2,cell*n+edge*2,cell*.33);ctx.fillStyle=mode==='shape'?'#e2ebf2':'#e9edf4';ctx.fill();ctx.shadowColor='transparent';ctx.lineWidth=2;ctx.strokeStyle='#ffffff';ctx.stroke();roundRect(ox-2,oy-2,cell*n+4,cell*n+4,cell*.16);ctx.fillStyle=mode==='shape'?'#819dac':'#8494a8';ctx.fill();roundRect(ox,oy,cell*n,cell*n,cell*.13);const floor=ctx.createLinearGradient(ox,oy,ox,oy+cell*n);floor.addColorStop(0,mode==='shape'?'#a7c0ca':'#acbacd');floor.addColorStop(1,mode==='shape'?'#c9dce1':'#d7e1eb');ctx.fillStyle=floor;ctx.fill();for(let y=0;y<n;y++)for(let x=0;x<n;x++){roundRect(ox+x*cell+2,oy+y*cell+2,cell-4,cell-4,cell*.1);ctx.strokeStyle='#ffffff32';ctx.lineWidth=1;ctx.stroke();ctx.fillStyle=(x+y)%2?'#ffffff08':'#4c606008';ctx.fill();}
for(const g of q.gates){const horizontal=g.side==='T'||g.side==='B',gx=horizontal?ox+g.at*cell:ox+(g.side==='L'?-edge:cell*n+.05*cell),gy=horizontal?oy+(g.side==='T'?-edge:cell*n+.05*cell):oy+g.at*cell,gw=horizontal?g.len*cell:edge*.8,gh=horizontal?edge*.8:g.len*cell;roundRect(gx,gy,gw,gh,cell*.09);ctx.fillStyle=darks[g.color];ctx.fill();roundRect(gx+2,gy+2,gw-4,gh-4,cell*.07);ctx.fillStyle=colors[g.color];ctx.fill();if(selected!==null&&q.pieces.find(p=>p.id===selected)?.color===g.color){ctx.lineWidth=2.5;ctx.strokeStyle='#fff';ctx.stroke();}ctx.fillStyle='#fff';ctx.font='900 '+Math.max(9,cell*.2)+'px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(symbols[g.color],gx+gw/2,gy+gh/2);}
for(const p of q.pieces)if(!p.gone)piece(p);for(const e of effects)piece(e.p,e.dx*e.age*3,e.dy*e.age*3,Math.max(0,1-e.age*2));if(hintMove&&s){const p=s.pieces.find(p=>p.id===hintMove.id);if(p&&!p.gone){const c=p.cells[0],x=ox+(p.x+c[0]+.5)*cell,y=oy+(p.y+c[1]+.5)*cell,dx=hintMove.dx,dy=hintMove.dy,l=cell*.9;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+dx*l,y+dy*l);ctx.lineWidth=5;ctx.strokeStyle='#fffcc6';ctx.lineCap='round';ctx.stroke();ctx.beginPath();ctx.moveTo(x+dx*l,y+dy*l);ctx.lineTo(x+dx*l-dx*10+dy*8,y+dy*l-dy*10-dx*8);ctx.lineTo(x+dx*l-dx*10-dy*8,y+dy*l-dy*10+dx*8);ctx.closePath();ctx.fillStyle='#fffcc6';ctx.fill();}}
for(const p of particles){ctx.globalAlpha=Math.max(0,1-p.age*1.5);ctx.fillStyle=p.c;ctx.fillRect(ox+p.x*cell,oy+p.y*cell,4,5);}ctx.restore();}
function tick(now){const dt=Math.min(.1,(now-lastTime)/1000);lastTime=now;if(!document.hidden){if(active()&&timed&&started){remaining=Math.max(0,remaining-dt);const secs=Math.ceil(remaining);$('clock').textContent=Math.floor(secs/60)+':'+String(secs%60).padStart(2,'0');$('clock').classList.toggle('urgent',remaining<30);if(!remaining)timeout();}effects.forEach(e=>e.age+=dt);effects=effects.filter(e=>e.age<.5);particles.forEach(p=>{p.age+=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=dt*3;});particles=particles.filter(p=>p.age<.7);draw();if(active()&&now-saveAt>5000){bankSave();saveAt=now;}}requestAnimationFrame(tick);}
window.__blockparty={B,start,loadMode,get state(){return s;},get trail(){return trail;},get selected(){return selected;},get remaining(){return remaining;},set remaining(v){remaining=v;},get geometry(){return {cell,ox,oy};},hint,nudge,undo,get moves(){return moves;},get timed(){return timed;},get complete(){return complete;}};hud();openMenu();requestAnimationFrame(tick);
})();
