/* Original Block Party puzzles. Integer-grid movement, matching exits, reverse-built solutions. */
(function(root){'use strict';const copy=x=>JSON.parse(JSON.stringify(x)),dirs=[[1,0],[-1,0],[0,1],[0,-1]];
const shapes=[[[0,0],[1,0]],[[0,0],[0,1]],[[0,0],[1,0],[2,0]],[[0,0],[0,1],[0,2]],[[0,0],[1,0],[0,1],[1,1]],[[0,0],[0,1],[1,1]],[[0,0],[1,0],[0,1]],[[1,0],[0,1],[1,1]],[[0,0],[1,0],[1,1]],[[0,0],[1,0],[2,0],[1,1]],[[0,0],[0,1],[0,2],[1,2]],[[1,0],[2,0],[0,1],[1,1]],[[0,0],[1,0],[1,1],[2,1]]];
function rng(seed){let a=seed>>>0;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
const size=p=>({w:1+Math.max(...p.cells.map(c=>c[0])),h:1+Math.max(...p.cells.map(c=>c[1]))});
function occupied(s,except){const a=new Set((s.walls||[]).map(c=>c.join(',')));for(const p of s.pieces)if(!p.gone&&p.id!==except)for(const [x,y] of p.cells)a.add((p.x+x)+','+(p.y+y));return a;}
function fits(s,p,x,y){const used=occupied(s,p.id);return p.cells.every(([a,b])=>x+a>=0&&x+a<s.n&&y+b>=0&&y+b<s.n&&!used.has((x+a)+','+(y+b)));}
function gateFor(s,p,dx,dy){const side=dx===-1?'L':dx===1?'R':dy===-1?'T':'B',z=size(p),lo=dx?p.y:p.x,hi=lo+(dx?z.h:z.w);return s.gates.find(g=>g.side===side&&g.color===p.color&&lo>=g.at&&hi<=g.at+g.len);}
function step(s,id,dx,dy,allowExit=true){if(Math.abs(dx)+Math.abs(dy)!==1)return null;const p=s.pieces.find(p=>p.id===id);if(!p||p.gone||p.axis==='h'&&dy||p.axis==='v'&&dx)return null;const x=p.x+dx,y=p.y+dy;if(fits(s,p,x,y)){p.x=x;p.y=y;return {id,dx,dy,exit:false};}const outside=p.cells.some(([a,b])=>x+a<0||x+a>=s.n||y+b<0||y+b>=s.n);if(!allowExit||!outside)return null;const g=gateFor(s,p,dx,dy);if(!g)return null;const used=occupied(s,p.id);for(let k=1;k<=s.n+3;k++){let inside=0;for(const [a,b] of p.cells){const xx=p.x+a+dx*k,yy=p.y+b+dy*k;if(xx>=0&&xx<s.n&&yy>=0&&yy<s.n){inside++;if(used.has(xx+','+yy))return null;}}if(!inside){p.gone=true;return {id,dx,dy,exit:true};}}return null;}
function key(s){return s.pieces.map(p=>p.gone?'x':p.x+','+p.y).join('|');}
function valid(s){const seen=new Set((s.walls||[]).map(c=>c.join(',')));for(const p of s.pieces){if(p.gone)continue;for(const [a,b] of p.cells){const x=p.x+a,y=p.y+b,k=x+','+y;if(x<0||y<0||x>=s.n||y>=s.n||seen.has(k))return false;seen.add(k);}}return true;}
function generate(mode,level=1,salt=0){level=Math.max(1,level|0);const r=rng(level*92821+salt*7529+(mode==='shape'?61543:13007)),n=level<5?5:level<17?6:7;
const goal=Math.min(mode==='shape'?9:10,level<3?3:level<7?4:level<13?6:level<25?7:9);let best=null;
for(let attempt=0;attempt<35;attempt++){let s={version:1,mode,level,n,pieces:[],gates:[],walls:[],solution:[],moves:0},history=[];
for(let id=0;id<goal;id++){let placed=false;for(let t=0;t<110;t++){let si=mode==='shape'?(level<3?5+Math.floor(r()*4):5+Math.floor(r()*8)):(level<6?Math.floor(r()*2):level<17?Math.floor(r()*5):Math.floor(r()*9));const cells=copy(shapes[si]),p={id,color:id%6,cells,x:0,y:0,gone:false,axis:null},z=size(p),side=['T','R','B','L'][Math.floor(r()*4)],len=(side==='T'||side==='B')?z.w:z.h,at=Math.floor(r()*(n-len+1));if(s.gates.some(g=>g.side===side&&at<g.at+g.len&&at+len>g.at))continue;p.x=side==='L'?0:side==='R'?n-z.w:at;p.y=side==='T'?0:side==='B'?n-z.h:at;if(!fits(s,p,p.x,p.y))continue;
// Directional rails appear gradually and are always solvable.
if(level>=13&&r()<.22)p.axis=side==='L'||side==='R'?'h':'v';
s.pieces.push(p);s.gates.push({side,at,len,color:p.color});const out=side==='L'?[-1,0]:side==='R'?[1,0]:side==='T'?[0,-1]:[0,1];if(!step(copy(s),id,...out)){s.pieces.pop();s.gates.pop();continue;}history.push({id,dx:out[0],dy:out[1]});for(let k=0;k<n;k++){const m=step(s,id,-out[0],-out[1],false);if(!m)break;history.push({id,dx:out[0],dy:out[1]});}placed=true;break;}
if(!placed)break;
// Reverse legal slides scramble the board while retaining a proven route out.
let last='';for(let k=0;k<35+level*2;k++){const p=s.pieces[Math.floor(r()*s.pieces.length)],d=dirs[Math.floor(r()*4)];if(last===p.id+','+(-d[0])+','+(-d[1]))continue;const m=step(s,p.id,...d,false);if(m){history.push({id:p.id,dx:-d[0],dy:-d[1]});last=p.id+','+d.join(',');}}
}
// Collapse loops in the certified forward route, preserving useful shuffling.
const route=history.reverse(),sim=copy(s),states=[key(sim)],actions=[],index=new Map([[states[0],0]]);for(const a of route){if(!step(sim,a.id,a.dx,a.dy))throw Error('Invalid generated route '+JSON.stringify({level,mode,a,sim}));const k=key(sim);if(index.has(k)){const j=index.get(k);while(states.length>j+1)index.delete(states.pop());actions.length=j;}else{actions.push(a);states.push(k);index.set(k,states.length-1);}}
s.solution=actions;if(!best||s.pieces.length>best.pieces.length||s.pieces.length===best.pieces.length&&actions.length>best.solution.length)best=s;if(s.pieces.length===goal&&actions.length>=goal*4)break;}
return best;}
function trace(s){const t=copy(s),a=[key(t)];for(const m of s.solution){if(!step(t,m.id,m.dx,m.dy))return null;a.push(key(t));}return {states:a,won:t.pieces.every(p=>p.gone)};}
function exitPath(s,id){const p=s.pieces.find(p=>p.id===id);if(!p||p.gone)return null;const queue=[{x:p.x,y:p.y,path:[]}],seen=new Set([p.x+','+p.y]),sim=copy(s),q=sim.pieces.find(p=>p.id===id);for(let i=0;i<queue.length;i++){const a=queue[i];for(const [dx,dy] of dirs){q.x=a.x;q.y=a.y;q.gone=false;const m=step(sim,id,dx,dy);if(!m)continue;const path=a.path.concat({id,dx,dy});if(m.exit)return path;const k=q.x+','+q.y;if(!seen.has(k)){seen.add(k);queue.push({x:q.x,y:q.y,path});}}}return null;}
function plan(s,trail=[]){const sim=copy(s),raw=[];for(const a of trail.slice().reverse()){const p=sim.pieces.find(p=>p.id===a.id);if(!p||p.gone||a.exit)continue;const m={id:a.id,dx:-a.dx,dy:-a.dy};if(!step(sim,m.id,m.dx,m.dy))throw Error('Invalid breadcrumb');raw.push(m);}for(const a of s.solution){if(sim.pieces.find(p=>p.id===a.id).gone)continue;if(!step(sim,a.id,a.dx,a.dy))throw Error('Invalid reference solution');raw.push(a);}
// Prefer immediately reachable exits, then follow the certified path when a shuffle is needed.
const t=copy(s),out=[];let at=0;while(t.pieces.some(p=>!p.gone)){let best=null;for(const p of t.pieces){const path=exitPath(t,p.id);if(path&&(!best||path.length<best.length))best=path;}if(best){for(const a of best){step(t,a.id,a.dx,a.dy);out.push(a);}continue;}while(at<raw.length&&t.pieces.find(p=>p.id===raw[at].id).gone)at++;if(at>=raw.length)throw Error('No route');const a=raw[at++];if(!step(t,a.id,a.dx,a.dy))throw Error('Blocked route');out.push(a);}
// Erase excursions which return to the same complete board.
const u=copy(s),states=[key(u)],actions=[],idx=new Map([[states[0],0]]);for(const a of out){step(u,a.id,a.dx,a.dy);const k=key(u);if(idx.has(k)){const j=idx.get(k);while(states.length>j+1)idx.delete(states.pop());actions.length=j;}else{actions.push(a);states.push(k);idx.set(k,states.length-1);}}return actions;}
const api={copy,dirs,size,occupied,fits,gateFor,step,key,valid,generate,trace,exitPath,plan};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.BP=api;
})(typeof window!=='undefined'?window:globalThis);
