/* Original handheld-inspired games. Rendering, storage and sound stay outside these rules. */
(function(root){'use strict';
class Football {
 constructor(skill='classic',rng=Math.random){this.rng=rng;this.mode='football';this.skill=skill;this.you=0;this.cpu=0;this.time=180;this.yard=20;this.line=30;this.down=1;this.phase='ready';this.player={x:1,y:1};this.defenders=[];this.moves=0;this.tick=0;this.cool=0;this.event=0;this.message='1st & 10 — press SNAP';this.delay=0;}
 say(text){this.message=text;this.event++;}
 startPlay(){if(this.phase!=='ready')return;this.phase='live';this.player={x:1,y:1};this.startYard=this.yard;this.tick=0;this.cool=0;this.moves=0;this.defenders=[{x:5,y:Math.floor(this.rng()*3)},{x:7,y:Math.floor(this.rng()*3)},{x:9,y:Math.floor(this.rng()*3)}];if(this.skill==='pro')this.defenders.push({x:8,y:(this.defenders[1].y+1)%3});this.say('Find a gap. Run toward the right →');}
 move(dx,dy){if(this.phase!=='live'||this.cool>0)return;this.cool=.115;const x=Math.max(0,Math.min(9,this.player.x+dx)),y=Math.max(0,Math.min(2,this.player.y+dy));if(x===this.player.x&&y===this.player.y)return;this.player={x,y};this.moves++;if(dx){this.yard=Math.max(1,this.yard+dx);if(this.yard>=100){this.you+=7;this.say('TOUCHDOWN! +7');this.possession();return;}}
 if(this.defenders.some(d=>d.x===x&&d.y===y)){this.tackle();return;}
 if(x>=7&&dx>0){this.player.x--;this.defenders.forEach(d=>d.x--);this.defenders=this.defenders.filter(d=>d.x>=0);while(this.defenders.length<(this.skill==='pro'?4:3)){if(this.defenders.filter(d=>d.x===9).length>=2)break;let d={x:9,y:Math.floor(this.rng()*3)};if(!this.defenders.some(v=>v.x===d.x&&v.y===d.y))this.defenders.push(d);else break;}}}
 tackle(){if(this.phase!=='live')return;const gain=this.yard-this.startYard;if(this.time<=0){this.finish();return;}if(this.yard>=this.line){this.down=1;this.line=Math.min(100,this.yard+10);this.say('FIRST DOWN! '+gain+' yards');}else{this.down++;this.say('Tackled · '+(gain>=0?'+':'')+gain+' yards');}if(this.down>4){this.say('Turnover on downs');this.possession();}else this.phase='ready';}
 possession(){if(this.time<=0){this.finish();return;}this.phase='computer';this.delay=2.2;}
 computerDrive(){const roll=this.rng();if(roll<.28)this.cpu+=7;else if(roll<.48)this.cpu+=3;this.time=Math.max(0,this.time-(12+Math.floor(this.rng()*13)));if(this.time<=0){this.finish();return;}this.yard=20;this.line=30;this.down=1;this.phase='ready';this.say(roll<.28?'Computer touchdown. Your ball at the 20.':roll<.48?'Computer field goal. Your ball at the 20.':'Defense holds! Your ball at the 20.');}
 kick(){if(this.phase!=='ready')return;const distance=117-this.yard;if(distance<=55){const good=this.rng()<Math.max(.2,.98-(distance-20)*.018);if(good)this.you+=3;this.say(distance+'-yard field goal '+(good?'GOOD! +3':'missed'));}else this.say('Punt — computer possession');this.possession();}
 update(dt){this.cool=Math.max(0,this.cool-dt);if(this.phase==='computer'){this.delay-=dt;if(this.delay<=0)this.computerDrive();return;}if(this.phase!=='live')return;this.time=Math.max(0,this.time-dt);this.tick+=dt;const pace=this.skill==='pro'?.38:.62;if(this.tick>=pace){this.tick-=pace;for(const d of this.defenders){let x=d.x,y=d.y;if(y!==this.player.y&&this.rng()<.42)y+=Math.sign(this.player.y-y);else if(x!==this.player.x)x+=Math.sign(this.player.x-x);if(!this.defenders.some(v=>v!==d&&v.x===x&&v.y===y)){d.x=x;d.y=y;}if(d.x===this.player.x&&d.y===this.player.y){this.tackle();break;}}}}
 finish(){this.phase='over';this.say(this.you>this.cpu?'YOU WIN!':this.you<this.cpu?'COMPUTER WINS':'TIE GAME');}
}
class Baseball {
 constructor(skill='classic',innings=3,rng=Math.random){this.rng=rng;this.mode='baseball';this.skill=skill;this.innings=innings;this.inning=1;this.half='top';this.you=0;this.cpu=0;this.outs=0;this.strikes=0;this.balls=0;this.bases=[false,false,false];this.phase='ready';this.pitchType='fast';this.lastType='';this.repeats=0;this.elapsed=0;this.duration=1.35;this.delay=0;this.event=0;this.message='You pitch first. Choose a pitch, then PITCH.';this.lastHit=0;}
 say(t){this.message=t;this.event++;}
 pitch(){if(this.phase!=='ready')return;if(this.half==='bottom')this.pitchType=this.rng()<.55?'fast':'curve';this.repeats=this.lastType===this.pitchType?this.repeats+1:0;this.lastType=this.pitchType;this.duration=(this.pitchType==='fast'?1.25:1.7)*(this.skill==='pro'?.83:1);this.wide=this.rng()<.23;this.elapsed=0;this.phase='pitch';this.swung=false;this.lastHit=0;this.say(this.half==='bottom'?'Watch the pitch. Time your SWING!':'Pitch away…');}
 swing(){if(this.phase!=='pitch'||this.half!=='bottom'||this.swung)return;this.swung=true;const err=Math.abs(this.elapsed-this.duration)/this.duration,window=this.skill==='pro'?.125:.18;if(err>window){this.strike('Swing and a miss');return;}if(this.wide||err>window*.78){this.strikes=Math.min(2,this.strikes+1);this.result('Foul ball');return;}const quality=err/window;const hit=quality<.16?4:quality<.32?3:quality<.60?2:1;this.hit(hit);}
 strike(text){this.strikes++;if(this.strikes>=3){this.outs++;this.balls=this.strikes=0;this.result('Strike three — OUT');}else this.result(text);}
 walk(){let carry=true;for(let i=0;i<3;i++){if(!carry)break;const had=this.bases[i];this.bases[i]=true;carry=had;}if(carry)this.run();this.balls=this.strikes=0;this.result('Ball four — walk');}
 run(){if(this.half==='bottom')this.you++;else this.cpu++;}
 hit(n){let next=[false,false,false];for(let i=2;i>=0;i--)if(this.bases[i]){if(i+n>=3)this.run();else next[i+n]=true;}if(n===4)this.run();else next[n-1]=true;this.bases=next;this.lastHit=n;this.balls=this.strikes=0;this.result(['','SINGLE!','DOUBLE!','TRIPLE!','HOME RUN!'][n]);}
 result(text){this.phase='result';this.delay=1.5;this.say(text);if(this.half==='bottom'&&this.inning>=this.innings&&this.you>this.cpu){this.phase='over';this.say('WALK-OFF! YOU WIN');}}
 resolvePitch(){if(this.half==='bottom'){if(this.wide){this.balls++;if(this.balls===4)this.walk();else this.result('Ball '+this.balls);}else this.strike('Called strike');return;}
 // Repeating one pitch makes it easier for the opposing batter to read.
 const r=this.rng(),hitChance=.23+Math.min(.12,this.repeats*.025);if(this.wide&&r<.8){this.balls++;if(this.balls===4)this.walk();else this.result('Ball '+this.balls);}else if(r<hitChance){const h=this.rng();this.hit(h<.70?1:h<.90?2:h<.95?3:4);}else if(r<.68){this.outs++;this.strikes=this.balls=0;this.result('Fly ball — OUT');}else this.strike('Swing and a miss');}
 next(){if(this.outs>=3){if(this.inning>=this.innings&&((this.half==='top'&&this.you>this.cpu)||(this.half==='bottom'&&this.you!==this.cpu))){this.phase='over';this.say(this.you>this.cpu?'YOU WIN!':'COMPUTER WINS');return;}this.outs=0;this.bases=[false,false,false];this.balls=this.strikes=0;this.repeats=0;this.lastType='';if(this.half==='top')this.half='bottom';else{this.half='top';this.inning++;}this.say(this.half==='bottom'?'Your turn to bat. Press PITCH when ready.':'Your turn to pitch. Mix fastballs and curves.');}this.phase='ready';}
 update(dt){if(this.phase==='pitch'){this.elapsed+=dt;if(this.elapsed>=this.duration*(this.half==='bottom'?1.20:1.02))this.resolvePitch();}else if(this.phase==='result'){this.delay-=dt;if(this.delay<=0)this.next();}}
}
const api={Football,Baseball};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.HandheldRules=api;
})(typeof window!=='undefined'?window:globalThis);
