(()=>{'use strict';
const $=id=>document.getElementById(id),store=Goobs.store('handheld');let game=null,mode='',paused=false,held=null,holdTime=0,last=performance.now(),saveClock=0,lastEvent=-1,audio=null,lastTackle=0,lastTouchdown=0,batTime=0;const voices=new Set;let sound=store.get('sound',true),records=store.get('records',{}),saved=store.get('games',{}),prefs=store.get('prefs',{skill:'classic',innings:3});$('skill').value=prefs.skill;$('innings').value=String(prefs.innings);
function setText(id,text){if($(id).textContent!==text)$(id).textContent=text;}
function unlockSound(){if(!sound)return;try{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();}catch{}}
function tone(freq=440,duration=.07,delay=0){if(!sound||!audio)return;try{const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+delay;o.type='square';o.frequency.value=freq;g.gain.setValueAtTime(.025,t);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(audio.destination);voices.add(o);o.onended=()=>voices.delete(o);o.start(t);o.stop(t+duration);}catch{}}
function silence(){for(const o of voices){try{o.stop();}catch{}}voices.clear();}
function touchdownSound(){
 // Two bright ascending calls followed by a held victory cadence.
 const notes=[[523,.12,0],[659,.12,.14],[784,.22,.28],[523,.12,.56],[659,.12,.70],[784,.22,.84],[1047,.18,1.10],[988,.12,1.30],[784,.12,1.44],[1047,.42,1.60]];
 for(const [hz,duration,delay] of notes)tone(hz,duration,delay);
 tone(262,.25,1.60);
}
function tackleSound(){
 // A short, raspy square-wave trill recalls a vintage handheld's tackle buzzer.
 if(!sound||!audio)return;
 for(let i=0;i<7;i++)tone(i%2?110:165,.043,i*.045);
 tone(82,.12,.315);
}
function save(){if(game){saved[mode]=JSON.parse(JSON.stringify(game));store.set('games',saved);}store.set('records',records);}
function record(){if(!game||game.phase!=='over'||game.recorded)return;game.recorded=true;const r=records[mode]||{played:0,wins:0,best:0};r.played++;if(game.you>game.cpu)r.wins++;r.best=Math.max(r.best,game.you);records[mode]=r;save();}
function lobbyRecords(){for(const m of ['football','baseball']){const r=records[m],s=saved[m];$(m+'Record').textContent=s&&s.phase!=='over'?'Resume saved game':r?r.wins+' wins · best '+r.best+' '+(m==='football'?'points':'runs'):m==='football'?'4 quarters · classic LED action':'Pitch, bat, and run the bases';}}
function fresh(){return mode==='football'?new HandheldRules.Football($('skill').value):new HandheldRules.Baseball($('skill').value,+$('innings').value);}
function openSport(m){unlockSound();mode=m;game=fresh();const s=saved[m];if(s&&s.mode===m&&s.phase!=='over')Object.assign(game,s);paused=false;held=null;lastEvent=game.event;lastTackle=game.tackleSerial||0;lastTouchdown=game.touchdownSerial||0;batTime=0;$('game').dataset.sport=m;$('lobby').hidden=true;$('game').hidden=false;$('footballControls').hidden=m!=='football';$('baseballControls').hidden=m!=='baseball';setText('sportTitle',m.toUpperCase());Goobs.markPlayed('handheld');resize();paint();save();tone(600);}
function toLobby(){save();held=null;paused=false;if($('menu').open)$('menu').close();$('game').hidden=true;$('lobby').hidden=false;game=null;lobbyRecords();}
function dialog(title,body,actions){held=null;paused=true;setText('menuTitle',title);$('menuBody').innerHTML=body;$('menuActions').replaceChildren();for(const [label,fn]of actions){const b=document.createElement('button');b.textContent=label;b.onclick=fn;$('menuActions').append(b);}if(!$('menu').open)$('menu').showModal();}
function closeDialog(){if($('menu').open)$('menu').close();paused=false;held=null;last=performance.now();}
function pause(){if(!game)return;dialog('Paused','<p>Your game is saved. Take your time.</p>',[['Resume',closeDialog],['Choose Sport',toLobby]]);save();}
const instructions={football:'<p><b>You are the bright LED.</b> Press SNAP, then use the arrows to dodge the dimmer defenders. Hold an arrow to keep moving. Right gains yards; left gives ground.</p><p>Gain 10 yards within four downs. Reach the end zone for 7 points, including the extra point. Before a snap, KICK attempts a field goal from 55 yards or closer; farther out it punts. Shorter kicks are more reliable.</p><p>The computer’s possessions are simulated. Four 45-second quarters; the clock runs during plays and advances during computer drives. Finish the current play when time expires.</p><p><b>Keyboard:</b> arrow keys move; Space snaps or runs right; K kicks; P pauses. Pro has faster defenders.</p>',baseball:'<p><b>You are the home team.</b> You pitch in the top half and bat in the bottom. Three outs switch sides. Choose a 3- or 9-inning game on the opening screen; tied games go to extra innings.</p><p><b>Pitching:</b> switch between FASTBALL and CURVE, then press PITCH. Mixing pitches makes you harder to hit. Fielding is automatic.</p><p><b>Batting:</b> press PITCH when ready. Watch the bright ball approach the home-plate marker, then press SWING as it reaches the plate. Centered timing hits farther—a perfect swing can hit a home run. Let wide pitches pass for a ball.</p><p>Three strikes: out. Four balls: walk. A foul cannot be strike three. Runners advance automatically, shown by lit bases.</p><p><b>Keyboard:</b> Space pitches or swings; C changes your pitch; P pauses. Pro makes batting timing tighter.</p>'};
function help(){const body=mode&&game?instructions[mode]:'<p>Choose Football or Baseball to play. Each sport keeps its own saved game. Sound, New Game, How to Play and Exit are built into the handheld.</p><h3>Football</h3>'+instructions.football+'<h3>Baseball</h3>'+instructions.baseball;dialog('How to Play',body,[['Back',closeDialog]]);}
$('menu').addEventListener('cancel',e=>{e.preventDefault();closeDialog();});$('pause').onclick=pause;$('menuExit').onclick=()=>{save();Goobs.home();};$('exit').onclick=()=>{save();Goobs.home();};$('lobbyExit').onclick=()=>Goobs.home();$('help').onclick=help;$('lobbyHelp').onclick=help;
$('newGame').onclick=()=>dialog('New game?','<p>Start a fresh '+mode+' game? Your current game will be replaced. Challenge: <b>'+$('skill').selectedOptions[0].textContent+'</b>'+(mode==='baseball'?' · '+$('innings').value+' innings':'')+'.</p>',[['Cancel',closeDialog],['New Game',()=>{game=fresh();lastEvent=game.event;lastTackle=0;lastTouchdown=0;batTime=0;closeDialog();save();paint();}],['Choose Sport',toLobby]]);
function act(action){if(!game||paused)return;unlockSound();if(action==='snap')game.startPlay();else if(action==='kick')game.kick();else if(action==='pitch')game.pitch();else if(action==='swing'){if(game.phase==='pitch'&&game.half==='bottom')batTime=.24;game.swing();}else if(action==='type'&&game.mode==='baseball'&&game.phase==='ready'&&game.half==='top'){game.pitchType=game.pitchType==='fast'?'curve':'fast';tone(420);}paint();save();}
$('snap').onclick=()=>act('snap');$('kick').onclick=()=>act('kick');$('pitch').onclick=()=>act('pitch');$('swing').onclick=()=>act('swing');$('pitchType').onclick=()=>act('type');
const directions={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]};
function move(dir){if(!game||mode!=='football'||paused)return;const before=game.yard;game.move(...directions[dir]);if(game.yard!==before)tone(250,.025);paint();}
document.querySelectorAll('[data-dir]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();unlockSound();held=b.dataset.dir;holdTime=0;b.setPointerCapture(e.pointerId);move(held);};b.onpointerup=b.onpointercancel=()=>{held=null;};b.onclick=e=>{if(e.detail===0)move(b.dataset.dir);};});
window.addEventListener('keydown',e=>{if(!game||$('menu').open)return;const dir={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'}[e.key];if(dir&&mode==='football'){e.preventDefault();if(!e.repeat){held=dir;holdTime=0;move(dir);}return;}if([' ','k','K','c','C','p','P'].includes(e.key)){e.preventDefault();if(e.repeat)return;if(e.key.toLowerCase()==='p')pause();else if(e.key===' '){if(mode==='football'){if(game.phase==='ready')act('snap');else move('right');}else act(game.phase==='ready'?'pitch':'swing');}else if(e.key.toLowerCase()==='k'&&mode==='football')act('kick');else if(e.key.toLowerCase()==='c'&&mode==='baseball')act('type');}});window.addEventListener('keyup',()=>{held=null;});window.addEventListener('blur',()=>{held=null;if(game&&!paused)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&game&&!paused)pause();});window.addEventListener('pagehide',save);
function soundLabel(){setText('sound',sound?'Sound On':'Sound Off');$('sound').setAttribute('aria-pressed',String(sound));}soundLabel();$('sound').onclick=()=>{sound=!sound;if(!sound)silence();store.set('sound',sound);soundLabel();unlockSound();if(sound)tone(660);};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>openSport(b.dataset.mode));for(const id of ['skill','innings'])$(id).onchange=()=>{prefs={skill:$('skill').value,innings:+$('innings').value};store.set('prefs',prefs);};
const canvas=$('field'),ctx=canvas.getContext('2d');let w=300,h=200;
function resize(){const r=canvas.getBoundingClientRect();if(!r.width||!r.height)return;w=r.width;h=r.height;const d=Math.min(3,devicePixelRatio||1);canvas.width=Math.round(w*d);canvas.height=Math.round(h*d);ctx.setTransform(d,0,0,d,0,0);draw();}new ResizeObserver(resize).observe(canvas.parentElement);window.addEventListener('resize',()=>{held=null;resize();});
function led(x,y,bright=false,size=8){ctx.save();ctx.fillStyle=mode==='football'?(bright?'#c3ffae':'#50e65b'):(bright?'#ffb596':'#f14634');ctx.shadowColor=mode==='football'?'#40ff59':'#ff382b';ctx.shadowBlur=bright?12:5;ctx.fillRect(x-size/2,y-size*.3,size,size*.6);if(bright){ctx.fillStyle=mode==='football'?'#edffe5':'#fff0ca';ctx.fillRect(x-size*.22,y-size*.14,size*.44,size*.28);}ctx.restore();}
function drawFootball(){const mx=w*.08,my=h*.22,dx=(w-2*mx)/9,dy=(h-2*my)/2;ctx.strokeStyle='#285d37';ctx.lineWidth=1;ctx.strokeRect(mx-dx*.45,my-dy*.48,w-2*mx+dx*.9,h-2*my+dy*.96);for(let x=0;x<10;x++){ctx.beginPath();ctx.moveTo(mx+x*dx,my-dy*.45);ctx.lineTo(mx+x*dx,my+dy*2.45);ctx.stroke();for(let y=0;y<3;y++){ctx.fillStyle='#183924';ctx.fillRect(mx+x*dx-4,my+y*dy-2,8,4);}}
 const live=game.phase==='live',p=live?game.player:{x:1,y:1},def=live?game.defenders:[{x:5,y:0},{x:7,y:1},{x:8,y:2}];def.forEach(d=>led(mx+d.x*dx,my+d.y*dy,false,Math.min(17,dx*.65)));led(mx+p.x*dx,my+p.y*dy,true,Math.min(21,dx*.82));}
function drawBaseball(){
 const size=Math.min(w*.36,h*.40),cx=w/2,cy=h*.49;
 const points=[[cx,cy+size],[cx+size,cy],[cx,cy-size],[cx-size,cy],[cx,cy+size]];
 const visual=game.visual,anim=visual&&visual.elapsed<1.5,progress=anim?Math.min(1,visual.elapsed/1.5):1;
 ctx.strokeStyle='#7e3835';ctx.lineWidth=1.5;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.stroke();
 ctx.strokeStyle='#49222b';ctx.beginPath();ctx.moveTo(cx-size*1.3,cy-size*.4);ctx.lineTo(cx,cy+size);ctx.lineTo(cx+size*1.3,cy-size*.4);ctx.stroke();
 let shown=game.bases;if(anim&&visual.runners.length)shown=visual.before.map((v,i)=>v&&!visual.runners.some(r=>r.from===i+1));
 points.slice(0,4).forEach(([x,y],i)=>{ctx.save();ctx.translate(x,y);ctx.rotate(Math.PI/4);ctx.fillStyle=i>0&&shown[i-1]?'#ff7857':'#77362f';ctx.shadowColor='#ff482e';ctx.shadowBlur=i>0&&shown[i-1]?8:0;ctx.fillRect(-5,-5,10,10);ctx.restore();});
 led(cx,cy-size*.05,false,9);
 if(!(anim&&visual.runners.some(r=>r.from===0)))led(cx-15,cy+size-2,true,11);
 // The bat sweeps across the plate without changing the timing window.
 if(batTime>0){const a=-2.4+(1-batTime/.24)*2.9;ctx.save();ctx.strokeStyle='#ffba8a';ctx.shadowColor='#ff4938';ctx.shadowBlur=6;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(cx-14,cy+size-2);ctx.lineTo(cx-14+Math.cos(a)*22,cy+size-2+Math.sin(a)*22);ctx.stroke();ctx.restore();}
 const flight=anim&&['hit','fly','foul'].includes(visual.kind),f=flight?Math.min(1,visual.elapsed/.9):0;
 [[-.9,-.55],[.8,-.5],[0,-1.18]].forEach(([x,y],i)=>{const chase=flight&&i===1?Math.sin(Math.PI*f)*.28:0;led(cx+size*(x-chase),cy+size*(y+chase),false,8);});
 if(game.phase==='pitch'){const t=Math.min(1.2,game.elapsed/game.duration),x=cx+(game.pitchType==='curve'?Math.sin(t*Math.PI)*size*.22:0)+(game.wide?Math.pow(Math.min(1,t),3)*size*.27:0),y=cy-size*.05+t*size*1.05;led(x,y,true,8);}
 else if(flight&&f<1){const side=visual.kind==='foul'?-1.25:.7,dist=visual.hit===4?2.5:1.7;for(let j=2;j>=0;j--){const t=Math.max(0,f-j*.055);ctx.globalAlpha=j? .25:1;led(cx+t*size*side,cy+size-t*size*dist-Math.sin(t*Math.PI)*size*.35,true,j?4:8);}ctx.globalAlpha=1;}
 if(anim)for(const runner of visual.runners){const travel=runner.from+(runner.to-runner.from)*progress,k=Math.min(3,Math.floor(travel)),t=travel-k,a=points[k],b=points[k+1];led(a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t,true,9);}
 if(anim&&visual.hit===4){ctx.save();ctx.strokeStyle='#ff6b45';ctx.globalAlpha=.3+.35*Math.sin(visual.elapsed*10)**2;ctx.lineWidth=2;ctx.strokeRect(5,5,w-10,h-10);ctx.restore();}
 ctx.fillStyle='#d2695b';ctx.font='9px monospace';ctx.textAlign='center';ctx.fillText('HOME',cx,Math.min(h-2,cy+size+18));
}
function draw(){ctx.clearRect(0,0,w,h);if(!game)return;if(mode==='football')drawFootball();else drawBaseball();}
function paint(){if(!game)return;const scored=(game.touchdownSerial||0)!==lastTouchdown;if(scored){lastTouchdown=game.touchdownSerial;touchdownSound();}const tackled=(game.tackleSerial||0)!==lastTackle;if(tackled){lastTackle=game.tackleSerial;tackleSound();}setText('you',String(game.you).padStart(2,'0'));setText('cpu',String(game.cpu).padStart(2,'0'));setText('message',game.message);if(game.event!==lastEvent){lastEvent=game.event;if(!scored&&/HOME RUN|WIN/.test(game.message)){[523,659,784].forEach((n,i)=>tone(n,.13,i*.13));}else if(!tackled&&!scored)tone(/OUT|Tackled|miss/.test(game.message)?180:480,.08);}if(mode==='football'){const q=Math.min(4,1+Math.floor((180-game.time)/45)),secs=Math.ceil(game.time%45)|| (game.time>0?45:0);setText('period','Q'+q+' · 0:'+String(secs).padStart(2,'0'));setText('detail',game.phase==='over'?'FINAL':game.down+(['','st','nd','rd','th'][game.down]||'th')+' & '+Math.max(1,game.line-game.yard));setText('readout',game.phase==='computer'?'COMPUTER DRIVE…':game.yard<=50?'BALL ON YOUR '+Math.floor(game.yard):'BALL ON CPU '+Math.floor(100-game.yard));$('snap').disabled=game.phase!=='ready';$('kick').disabled=game.phase!=='ready';$('kick').textContent=117-game.yard<=55?'FIELD GOAL':'PUNT';document.querySelectorAll('[data-dir]').forEach(b=>b.disabled=game.phase!=='live');}else{setText('period',(game.half==='top'?'TOP ':'BOT ')+game.inning+' / '+game.innings);setText('detail',game.phase==='over'?'FINAL':game.outs+' OUT · '+game.balls+'–'+game.strikes);setText('readout',game.half==='top'?'YOU PITCH · CPU BATS':'YOU BAT · TIME YOUR SWING');setText('pitchType',game.pitchType==='fast'?'FASTBALL':'CURVE');setText('pitchCaption',game.half==='top'?'Change pitch':'Watch the ball');$('pitchType').disabled=game.half!=='top'||game.phase!=='ready';$('pitch').disabled=game.phase!=='ready';$('swing').disabled=game.half!=='bottom'||game.phase!=='pitch';}record();draw();}
function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(game&&!paused){batTime=Math.max(0,batTime-dt);if(held){holdTime+=dt;if(holdTime>=.13){holdTime=0;move(held);}}game.update(dt);paint();saveClock+=dt;if(saveClock>=1){saveClock=0;save();}}requestAnimationFrame(frame);}requestAnimationFrame(frame);lobbyRecords();Goobs.initUpdates({beforeReload:save,onVersions:v=>setText('version','Handheld Sports '+(v.handheld||'1.1.1'))});
// Read-only handles help validate rendering and rules together.
window.HandheldSports={get game(){return game},get paused(){return paused}};
})();
